'use strict';
(() => {
const A=window.Aura, $=A.$, esc=A.escape, icon=A.icon;
const now=new Date();
const dayKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
// Calendar: real month arithmetic and locally persisted events.
let calendarDate=new Date(now.getFullYear(),now.getMonth(),1),selectedDate=dayKey(now);
let events=A.load('events',[{id:'welcome-event',date:dayKey(now),time:'15:00',title:'ひと息つく時間',place:'お気に入りのカフェ'}]);
function calendar(){
 const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),start=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate();
 let cells=['日','月','火','水','木','金','土'].map((d,i)=>`<span class="weekday" style="${i===0?'color:#e18484':i===6?'color:#7397bd':''}">${d}</span>`).join('');
 for(let i=0;i<start;i++)cells+='<span></span>';
 for(let d=1;d<=count;d++){const key=dayKey(new Date(y,m,d));cells+=`<button class="month-day ${key===dayKey(now)?'today':''} ${key===selectedDate?'selected':''} ${events.some(e=>e.date===key)?'has-event':''}" data-action="calendarSelect" data-date="${key}">${d}</button>`;}
 const daily=events.filter(e=>e.date===selectedDate).sort((a,b)=>a.time.localeCompare(b.time));
 A.view(A.nav('カレンダー',`<button data-action="calendarAdd" aria-label="予定を追加">${icon('plus')}</button>`)+`<div class="app-content"><div class="calendar-month-head"><h3>${y}<span style="font-weight:400;font-size:18px">年</span> ${m+1}<span style="font-weight:400;font-size:18px">月</span></h3><div><button data-action="calendarMove" data-value="-1" aria-label="前の月">‹</button><button data-action="calendarMove" data-value="1" aria-label="次の月">›</button></div></div><div class="month-grid">${cells}</div><div class="calendar-agenda"><h3>${new Date(selectedDate+'T12:00:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'long'})}</h3>${daily.map(e=>`<article class="event-card"><div class="event-time">${esc(e.time)}<br>予定</div><button class="event-info ev-calendar-edit" data-action="calendarEdit" data-id="${esc(e.id)}" aria-label="${esc(e.title)}を編集"><strong>${esc(e.title)}</strong><small>${esc(e.place||'')}</small></button><button data-action="calendarDelete" data-id="${e.id}" aria-label="予定を削除">×</button></article>`).join('')||A.empty('予定なし','sun')}</div><button class="secondary-button" data-action="calendarToday" style="width:100%;margin-top:16px;color:#e96867;background:#f6e6e5">今日に戻る</button></div>`);
}
A.apps.calendar.render=calendar;
A.todayEvents=date=>events.filter(event=>event.date===date);
A.allEvents=()=>events.map(event=>({...event}));
A.eventModel={get:()=>events,replace:list=>{if(!A.save('events',list))return false;events=list;return true;}};
A.actions.calendarMove=el=>{calendarDate.setMonth(calendarDate.getMonth()+ +el.dataset.value);calendar();};
A.actions.calendarSelect=el=>{selectedDate=el.dataset.date;calendar();};
A.actions.calendarToday=()=>{calendarDate=new Date(now.getFullYear(),now.getMonth(),1);selectedDate=dayKey(new Date());calendar();};
function eventEditor(event){A.form(event?'予定を編集':'新しい予定',`<label class="form-label">タイトル</label><input class="text-input" name="title" required maxlength="80" value="${esc(event?.title||'')}"><label class="form-label">日付</label><input class="text-input" type="date" name="date" value="${event?.date||selectedDate}" required><label class="form-label">時間</label><input class="text-input" type="time" name="time" value="${event?.time||'15:00'}" required><label class="form-label">場所</label><input class="text-input" name="place" maxlength="80" value="${esc(event?.place||'')}">`,v=>{if(!v.title.trim())return false;const next={id:event?.id||A.id(),...v,title:v.title.trim()},list=event?events.map(e=>e.id===event.id?next:e):[...events,next];if(!A.save('events',list))return false;events=list;selectedDate=v.date;calendarDate=new Date(v.date+'T12:00:00');calendarDate.setDate(1);calendar();});}
A.actions.calendarAdd=()=>eventEditor();
A.actions.calendarEdit=el=>{const event=events.find(e=>e.id===el.dataset.id);if(event)eventEditor(event);};
A.actions.calendarDelete=el=>A.confirm('予定を削除','この予定を削除しますか？',()=>{events=events.filter(e=>e.id!==el.dataset.id);A.save('events',events);calendar();});
// Notes — autosave each edit, no network or accounts.
let notes=A.load('notes',[
{id:'note-1',title:'週末にしたいこと',body:'朝、いつもより少し早く起きる。\n\n☐ 気になっていたパン屋さんへ\n☐ 本を一冊、読み終える\n☐ フィルムみたいな写真を撮る\n\n何もしない時間も、大切に。',updated:Date.now()},
{id:'note-2',title:'ふと思いついたこと',body:'日常の小さな発見を、\nここに集めていこう。\n\n光の入り方。\nコーヒーの香り。\n帰り道で聴いた音楽。',updated:Date.now()-86400000},
{id:'note-3',title:'買いものリスト',body:'オーツミルク\n季節のフルーツ\nコーヒー豆\n小さな花束',updated:Date.now()-172800000},
{id:'note-4',title:'auraへようこそ',body:'ここは、あなたのもう一台。\n\nメモは自動的に、このブラウザに保存されます。\n\n右上のペンから、新しいメモを書いてみてください。',updated:Date.now()-259200000}]);
A.searchableNotes=()=>notes;
A.noteModel={get:()=>notes,replace:(list,related={})=>{if(!A.saveBatch({...related,notes:list}))return false;notes=list;return true;}};
let currentNote=null,noteQuery='';
let noteSort=A.load('noteSort','updated');
if(!['updated','title'].includes(noteSort))noteSort='updated';
function renderNoteList(q=noteQuery){
 const el=$('#notes-grid');if(!el)return;noteQuery=q;
 const query=q.trim().toLocaleLowerCase('ja');
 const list=notes.filter(n=>(n.title+'\n'+n.body).toLocaleLowerCase('ja').includes(query)).sort((a,b)=>{
  const pinned=Number(!!b.pinned)-Number(!!a.pinned);
  return pinned||(noteSort==='title'?(a.title||'新しいメモ').localeCompare(b.title||'新しいメモ','ja'):b.updated-a.updated);
 });
 el.innerHTML=list.map(n=>`<button class="note-card ${n.pinned?'is-pinned':''}" data-action="noteOpen" data-id="${esc(n.id)}">${n.pinned?`<span class="note-pin-label">${icon('pin')}ピン留め</span>`:''}<h3>${esc(n.title||'新しいメモ')}</h3><p>${esc(n.body)||'空のメモ'}</p><small>${new Date(n.updated).toLocaleDateString('ja-JP',{month:'short',day:'numeric'})}</small></button>`).join('')||'<p class="empty-state" style="grid-column:span 2">メモなし</p>';
 $('#notes-count').textContent=query?`${list.length} / ${notes.length}件`:`${notes.length}件のメモ`;
}
function noteList(){
 currentNote=null;
 A.view(A.nav('メモ',`<button data-action="noteNew" aria-label="新規メモ">${icon('edit')}</button>`)+`<div class="app-content">${A.search('notes-search','メモを検索')}<div class="notes-toolbar"><span id="notes-count" role="status"></span><select id="notes-sort" aria-label="メモの並べ替え"><option value="updated">更新順</option><option value="title">タイトル順</option></select></div><div class="notes-grid" id="notes-grid"></div></div>`);
 $('#notes-search').value=noteQuery;$('#notes-sort').value=noteSort;renderNoteList();
 $('#notes-search').oninput=e=>renderNoteList(e.target.value);
 $('#notes-sort').onchange=e=>{noteSort=e.target.value;A.save('noteSort',noteSort);renderNoteList();};
}
const noteLength=body=>Array.from(body).length;
function noteEdit(id){
 const n=notes.find(n=>n.id===id);if(!n)return;currentNote=id;
 A.view(A.nav('メモ',`<button data-action="noteDelete" aria-label="削除">${icon('trash')}</button>`,'noteList','メモ')+`<div class="app-content"><small id="note-save-status" role="status">自動保存</small><div class="note-editor-tools"><button class="note-pin-button" data-action="notePin" aria-pressed="${!!n.pinned}">${icon('pin')}<span>${n.pinned?'ピン留め':'ピン留め'}</span></button><span id="note-length">本文 ${noteLength(n.body)}文字</span></div><input class="note-title-input" id="note-title" aria-label="メモのタイトル" placeholder="タイトル" maxlength="120" value="${esc(n.title)}"><textarea class="note-body-input" id="note-body" aria-label="メモ本文" placeholder="本文">${esc(n.body)}</textarea></div>`);
 const save=()=>{n.title=$('#note-title').value;n.body=$('#note-body').value;n.updated=Date.now();const ok=A.save('notes',notes);$('#note-save-status').textContent=ok?'保存しました':'保存できませんでした';$('#note-length').textContent=`本文 ${noteLength(n.body)}文字`;};
 $('#note-title').oninput=save;$('#note-body').oninput=save;
}
A.apps.notes.render=noteList;A.actions.noteList=noteList;A.actions.noteOpen=el=>noteEdit(el.dataset.id);
A.actions.noteNew=()=>{const id=A.id();notes.unshift({id,title:'',body:'',updated:Date.now(),pinned:false});A.save('notes',notes);noteQuery='';noteEdit(id);$('#note-title').focus();};
A.actions.notePin=()=>{
 const n=notes.find(n=>n.id===currentNote);if(!n)return;
 n.pinned=!n.pinned;const ok=A.save('notes',notes);
 if(!ok)n.pinned=!n.pinned;
 const button=$('[data-action="notePin"]');button.setAttribute('aria-pressed',String(!!n.pinned));button.querySelector('span').textContent=n.pinned?'ピン留め':'ピン留め';
 $('#note-save-status').textContent=ok?'保存しました':'保存できませんでした';
};
A.actions.noteDelete=()=>A.confirm('メモを削除','このメモは元に戻せません。',()=>{notes=notes.filter(n=>n.id!==currentNote);A.save('notes',notes);noteList();});
// Reminders
let reminders=A.load('reminders',[{id:'r1',text:'朝のストレッチ',done:true},{id:'r2',text:'お気に入りの音楽を聴く',done:true},{id:'r3',text:'コーヒー豆を買う',done:false},{id:'r4',text:'本を20ページ読む',done:false},{id:'r5',text:'夕暮れの空を撮る',done:false}]);
A.searchableReminders=()=>reminders;
A.reminderModel={get:()=>reminders,replace:list=>{if(!A.save('reminders',list))return false;reminders=list;return true;}};
let reminderFilter='all';
function reminderApp(){const done=reminders.filter(r=>r.done).length, today=dayKey(new Date()),filtered=reminders.filter(r=>reminderFilter==='all'||(reminderFilter==='done'?r.done:reminderFilter==='today'?!r.done&&r.due&&r.due<=today:!r.done)).sort((a,b)=>Number(a.done)-Number(b.done)||Number(!!b.priority)-Number(!!a.priority)||(a.due||'9999').localeCompare(b.due||'9999'));
A.view(A.nav('リマインダー',`<button data-action="reminderDetails" aria-label="タスクを追加">${icon('plus')}</button>`)+`<div class="app-content"><div class="reminder-progress"><small>完了</small><strong>${done} <span style="font-size:16px;opacity:.6">/ ${reminders.length}</span></strong><div class="progress-track"><span style="width:${reminders.length?done/reminders.length*100:0}%"></span></div></div><div class="ev-reminder-tools"><div class="ev-chips">${[['all','すべて'],['pending','未完了'],['today','今日'],['done','完了']].map(([id,label])=>`<button class="${reminderFilter===id?'selected':''}" data-action="reminderFilter" data-value="${id}">${label}</button>`).join('')}</div></div>${filtered.map(r=>`<div class="reminder-row ${r.done?'done':''}"><button class="check-circle ${r.done?'checked':''}" data-action="reminderToggle" data-id="${r.id}" aria-label="${esc(r.text)}" aria-pressed="${r.done}">${r.done?'✓':''}</button><button class="ev-plain" data-action="reminderDetails" data-id="${r.id}">${esc(r.text)}<small class="ev-reminder-meta">${r.priority?'優先 ':''}${r.due?esc(r.due):''}${r.due&&r.due<today&&!r.done?' · 期限超過':''}</small></button><button class="delete-small" data-action="reminderDelete" data-id="${r.id}" aria-label="削除">×</button></div>`).join('')}<form class="add-inline" id="reminder-form"><input class="text-input" name="text" placeholder="タスクを追加" aria-label="新しいリマインダー" required maxlength="100"><button type="submit" aria-label="追加">+</button></form>${done?'<button class="ev-text-button" data-action="reminderClearDone">完了済みを削除</button>':''}</div>`);
$('#reminder-form').onsubmit=e=>{e.preventDefault();const text=e.currentTarget.elements.text.value.trim();if(!text)return;const list=[...reminders,{id:A.id(),text,done:false}];if(A.save('reminders',list)){reminders=list;reminderApp();}};}
A.apps.reminders.render=reminderApp;
A.actions.reminderFilter=el=>{reminderFilter=el.dataset.value;reminderApp();};
A.actions.reminderToggle=el=>{const list=reminders.map(r=>r.id===el.dataset.id?{...r,done:!r.done}:r);if(A.save('reminders',list)){reminders=list;A.haptic();reminderApp();}};
A.actions.reminderDelete=el=>{const list=reminders.filter(r=>r.id!==el.dataset.id);if(A.save('reminders',list)){reminders=list;reminderApp();}};
A.actions.reminderClearDone=()=>A.confirm('完了済みを削除？','未完了のタスクは残ります。',()=>{const list=reminders.filter(r=>!r.done);if(A.save('reminders',list)){reminders=list;reminderApp();}});
A.actions.reminderDetails=el=>{const r=reminders.find(r=>r.id===el?.dataset?.id);A.form(r?'タスクを編集':'タスクを追加',`<label class="form-label">タスク</label><input class="text-input" name="text" required maxlength="100" value="${esc(r?.text||'')}"><label class="form-label">期限</label><input class="text-input" type="date" name="due" value="${r?.due||''}"><label class="form-label">優先度</label><select class="text-input" name="priority"><option value="0">通常</option><option value="1" ${r?.priority?'selected':''}>優先</option></select>`,v=>{if(!v.text.trim())return false;const next={id:r?.id||A.id(),text:v.text.trim(),due:v.due,priority:v.priority==='1',done:r?.done||false},list=r?reminders.map(x=>x.id===r.id?next:x):[...reminders,next];if(!A.save('reminders',list))return false;reminders=list;reminderApp();});};
// Settings
function settingToggle(key,label,ic,color){return `<div class="list-row"><span class="row-icon" style="background:${color};color:white">${icon(ic)}</span><span class="row-main"><strong>${label}</strong></span><button class="toggle ${A.settings[key]?'on':''}" data-action="settingToggle" data-key="${key}" aria-label="${label}" aria-pressed="${A.settings[key]}"></button></div>`;}
function settings(){A.statusTheme(false);A.view(A.nav('設定')+`<div class="app-content"><button class="profile-card" data-action="settingsProfile" style="width:100%;text-align:left"><span class="avatar">a.</span><div><h3>${esc(A.load('profileName','あなたのaura'))}</h3></div><span class="chevron" style="margin-left:auto">›</span></button><div class="group-card">${settingToggle('airplane','機内モード','airplane','#efa557')}${settingToggle('wifi','Wi-Fi','wifi','#508af0')}${settingToggle('bluetooth','Bluetooth','bluetooth','#508af0')}</div><div class="group-card">${A.row('globe','接続とプライバシー','対応状況','connectionCenter','','#508af0')}${A.row('grid','全画面で使う','','fullscreen','','#697287')}${A.row('sun','画面表示と明るさ','','settingsDisplay','','#528be5')}${A.row('layers','光と奥行き','','settingsAppearance','','#9981b4')}${A.row('photos','壁紙とホーム画面','','personalize','','#b094cf')}${A.row('messages','通知センター','','showNotifications','','#e88192')}${settingToggle('dark','ダークモード','moon','#697287')}${settingToggle('focus','集中モード','moon','#8b75c0')}${settingToggle('sound','触覚フィードバック','volume','#e88192')}</div><div class="group-card">${A.row('grid','操作ガイド','','gestureGuide','','#6d9aab')}${A.row('user','このデバイスについて','','settingsAbout','','#8d939c')}${A.row('trash','データをリセット','','settingsReset','','#db7777')}</div><p class="setting-description">通信設定はデモ・実端末には反映しません</p><p class="notes-footer">auraOS 4.6</p></div>`);}
A.apps.settings.render=settings;A.actions.settingsHome=settings;A.actions.settingToggle=el=>{A.settings[el.dataset.key]=!A.settings[el.dataset.key];A.applySettings();if($('#settings-brightness'))A.actions.settingsDisplay();else settings();};
A.actions.settingsProfile=()=>A.form('あなたの名前',`<label class="form-label">表示名</label><input class="text-input" name="name" required maxlength="24" value="${esc(A.load('profileName','あなたのaura'))}">`,v=>{if(!A.save('profileName',v.name))return false;A.actions.settingsHome();});
A.actions.settingsDisplay=()=>{A.view(A.nav('画面表示と明るさ','','settingsHome','設定')+`<div class="app-content"><p class="app-subtitle">aura内の明るさ</p><div class="group-card" style="padding:25px 20px;display:flex;align-items:center;gap:15px">${icon('sun','style="width:25px;flex-shrink:0;color:#aaa"')}<input id="settings-brightness" style="width:100%;accent-color:#6588c7" type="range" min="10" max="100" value="${A.settings.brightness}" aria-label="画面の明るさ"></div><div class="group-card">${settingToggle('dark','ダークモード','moon','#697287')}</div></div>`);$('#settings-brightness').oninput=e=>{A.settings.brightness=+e.target.value;A.applySettings();};};
A.actions.settingsAppearance=()=>A.view(A.nav('光と奥行き','','settingsHome','設定')+`<div class="app-content">${A.appearancePanel()}</div>`);
A.actions.settingsWallpaper=()=>{A.view(A.nav('壁紙','','settingsHome','設定')+`<div class="app-content"><div class="wallpaper-options">${[['default','Dusk'],['ocean','Ocean'],['forest','Forest'],['mono','Stone']].map(([v,n])=>`<button class="wallpaper-option ${v} ${A.settings.wallpaper===v?'active':''}" data-action="wallpaperSet" data-value="${v}" aria-label="壁紙 ${n}"></button>`).join('')}</div><div style="display:flex;justify-content:space-around;font-size:10px;color:#9b95a1"><span>Dusk</span><span>Ocean</span><span>Forest</span><span>Stone</span></div></div>`);};
A.actions.wallpaperSet=el=>{A.settings.wallpaper=el.dataset.value;A.applySettings();A.actions.settingsWallpaper();A.toast('壁紙を変更済み');};
A.actions.settingsAbout=()=>A.view(A.nav('情報','','settingsHome','設定')+`<div class="app-content"><div class="about-hero" style="text-align:center;margin:35px 0">aura.</div><div class="group-card">${A.row('','名前','',null,'aura Phone')}${A.row('','OSバージョン','',null,'auraOS 4.6')}${A.row('','モデル','',null,'Browser Edition')}${A.row('','アプリ','',null,String(Object.keys(A.apps).length))}${A.row('','ゲーム','',null,'8')}</div><p class="setting-description">ブラウザ内のシミュレーター。実端末は変更しません。</p></div>`);
A.actions.settingsReset=()=>A.confirm('auraのデータをリセット','aura内の全データを削除。復元不可',()=>{try{Object.keys(localStorage).filter(k=>k.startsWith('aura.')).forEach(k=>localStorage.removeItem(k));location.reload();}catch{A.toast('データを削除できません');}});
// Local message simulation.
const contacts=[{id:'misaki',name:'美咲',initial:'美',color:'linear-gradient(140deg,#d6b6a5,#ad897f)',time:'10:24',preview:'週末は、どこか出かけよう ☀',messages:[{text:'おはよう！今日はいい天気だね ☀',sent:false},{text:'本当だね。窓を開けたら気持ちいい。',sent:true},{text:'週末は、どこか出かけよう ☀',sent:false}]},{id:'haru',name:'陽',initial:'陽',color:'linear-gradient(140deg,#aac2b2,#738e85)',time:'昨日',preview:'この曲、きっと気に入ると思う。',messages:[{text:'最近、どんな音楽を聴いてる？',sent:false},{text:'ゆっくりした曲が多いかな。',sent:true},{text:'この曲、きっと気に入ると思う。ミュージックアプリの「Golden Hour」を聴いてみて 🎧',sent:false}]},{id:'aura',name:'aura studio',initial:'a.',color:'linear-gradient(140deg,#b6abd0,#8a80a2)',time:'金曜日',preview:'小さな世界へ、ようこそ。',messages:[{text:'auraへようこそ。ここはあなたのもう一台のスマートフォンです。',sent:false},{text:'この会話はローカルデモです。メッセージを送ると、用意された返信が届きます。外部への送信はありません。',sent:false}]}];
let chats=A.load('chats',Object.fromEntries(contacts.map(c=>[c.id,c.messages]))),activeChat=null;
const pendingReplies={};
A.actions.showNotifications=()=>A.notifications();
let chatUnread=A.load('chatUnread',{misaki:1,haru:1,aura:0});
A.messageUnread=()=>Object.values(chatUnread).reduce((a,b)=>a+b,0);
function messages(arg){if(arg&&contacts.some(c=>c.id===arg))return chat(arg);A.view(A.nav('メッセージ',`<button data-action="messageCompose" aria-label="新しい会話">${icon('edit')}</button>`)+`<div class="app-content"><p class="demo-label">DEMO</p>${A.search('chat-search','人やメッセージを検索')}<div id="chat-list"></div><p class="notes-footer">デモ・外部送信なし</p></div>`);const list=q=>{$('#chat-list').innerHTML=contacts.filter(c=>(c.name+chats[c.id].map(m=>m.text).join('')).includes(q)).map(c=>`<button class="chat-row" data-action="chatOpen" data-id="${c.id}"><span class="avatar" style="background:${c.color}">${c.initial}</span><div class="chat-preview"><header>${c.name}${chatUnread[c.id]?'<span class="chat-unread-dot" aria-label="未読"></span>':''}<time>${chats[c.id].at(-1)?.time?new Date(chats[c.id].at(-1).time).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}):c.time} ›</time></header><p>${esc(chats[c.id].at(-1)?.text||c.preview)}</p></div></button>`).join('')||A.empty('会話なし','messages');};list('');$('#chat-search').oninput=e=>list(e.target.value);}
function chat(id){activeChat=id;chatUnread[id]=0;A.save('chatUnread',chatUnread);const c=contacts.find(c=>c.id===id);A.view(A.nav(c.name,'<span class="demo-label">ローカルデモ</span>','messagesList','戻る')+`<div class="app-content chat-area" id="chat-area"><p class="chat-date">デモ・外部送信なし</p><div id="chat-bubbles"></div></div><form class="chat-composer" id="chat-form"><input name="message" placeholder="メッセージ" aria-label="メッセージ" required maxlength="1000" autocomplete="off"><button type="submit" aria-label="送信">↑</button></form>`);renderChat();$('#chat-form').onsubmit=e=>{e.preventDefault();const input=e.currentTarget.elements.message;const text=input.value.trim();if(!text)return;chats[id].push({text,sent:true,time:Date.now()});pendingReplies[id]=(pendingReplies[id]||0)+1;A.save('chats',chats);input.value='';renderChat();const replies=id==='aura'?['気になるアプリを、自由に開いてみてください ✨','メモや写真は端末内に保存。あなたらしく使ってみてください。']:['いいね！楽しみにしてる 😊','うん、ゆっくり過ごそう。','そうだね！あとでまた話そう ☀','わかった！素敵な一日になりますように。'];const count=chats[id].filter(m=>m.sent).length;setTimeout(()=>{const reply=replies[(count-1)%replies.length];chats[id].push({text:reply,sent:false,time:Date.now()});pendingReplies[id]=Math.max(0,(pendingReplies[id]||1)-1);A.save('chats',chats);if(A.current==='messages'&&activeChat===id&&$('#chat-bubbles'))renderChat();else{chatUnread[id]=(chatUnread[id]||0)+1;A.save('chatUnread',chatUnread);if(!A.current)A.renderHome();A.notify({app:'messages',arg:id,title:c.name,body:reply});}},1200);};}
function renderChat(){
 if(!$('#chat-bubbles'))return;
 const messages=chats[activeChat],lastSent=messages.map(m=>m.sent).lastIndexOf(true);
 $('#chat-bubbles').innerHTML=messages.map((m,i)=>`<div class="message-bubble ${m.sent?'sent':''}">${esc(m.text)}${m.time?`<time class="bubble-time">${new Date(m.time).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</time>`:''}</div>${m.sent&&i===lastSent?`<span class="message-delivery">${pendingReplies[activeChat]?'送信済み':'既読'} · デモ</span>`:''}`).join('')+(pendingReplies[activeChat]?'<div class="typing-indicator" role="status" aria-label="デモ返信を入力中"><i></i><i></i><i></i></div>':'');
 $('#chat-area').scrollTop=$('#chat-area').scrollHeight;
}
A.apps.messages.render=messages;A.actions.messagesList=()=>{activeChat=null;messages();};A.actions.chatOpen=el=>chat(el.dataset.id);A.actions.messageCompose=()=>A.overlay(`${A.overlayTitle('会話をはじめる')}<div class="group-card">${contacts.map(c=>`<button class="list-row" data-action="chooseChat" data-id="${c.id}"><span class="avatar" style="background:${c.color}">${c.initial}</span><span class="row-main"><strong>${c.name}</strong><small>デモ</small></span><span class="chevron">›</span></button>`).join('')}</div>`);A.actions.chooseChat=el=>{A.closeOverlay();chat(el.dataset.id);};
// Mail — seeded inbox and explicitly local drafts/outbox.
let mails=A.load('mails',[
{id:'mail-1',sender:'aura studio',initial:'a.',subject:'小さな世界へ、ようこそ。',preview:'あなたのもう一台が、ここにあります。',body:'こんにちは。\n\nauraへようこそ。\n\n日々の小さな発見や、ふと浮かんだ思いつき。お気に入りの景色と、心地よい音楽。\n\nこの小さな世界が、あなたの日常に、少しの余白を届けられますように。\n\nまずは、気になるアプリをタップしてみてください。きっと、あなたのお気に入りが見つかります。\n\n心をこめて、\naura studio\n\n※ このメールはシミュレーター内のサンプルです。',time:'10:00',read:false,folder:'inbox'},
{id:'mail-2',sender:'THE SLOW LETTER',initial:'S',subject:'日曜日の、ちょうどいい過ごし方。',preview:'急がなくていい朝。コーヒーを淹れながら、読む手紙。',body:'SUNDAY, AT YOUR OWN PACE.\n\n目覚ましをかけない朝。\nお気に入りのカップ。\n読みかけの本。\n\n何かを「しなければ」ではなく、何かを「したい」と思うまで待ってみる。\n\n今週は、そんな休日のご提案です。\n\n1. 近所の知らない道を歩いてみる\n2. 一枚だけ、写真を撮る\n3. 自分に短い手紙を書く\n\n素敵な日曜日を。\nTHE SLOW LETTER',time:'8:30',read:false,folder:'inbox'},
{id:'mail-3',sender:'緑のある暮らし',initial:'葉',subject:'窓辺の植物と、小さな変化。',preview:'季節が少しずつ、移り変わっています。',body:'窓から入る光が、少し柔らかくなりました。\n\n植物たちも、季節の変化を感じているようです。新しい葉が開く瞬間は、何度見ても嬉しいものですね。\n\n今日の小さなヒント：\n朝、カーテンを開けたら、葉っぱの裏も覗いてみましょう。\n\n小さな発見があるかもしれません。',time:'昨日',read:false,folder:'inbox'},
{id:'mail-4',sender:'美咲',initial:'美',subject:'行ってみたいお店、見つけたよ',preview:'この前話していたカフェ、週末に行かない？',body:'この前話していたカフェ、覚えてる？\n\n静かな路地にあって、窓が大きくて、コーヒーがおいしそうなお店。\n\n週末に行かない？\n午後なら空いてるよ ☀\n\n美咲',time:'金曜日',read:true,folder:'inbox'}]);
let mailFolder='inbox';
A.mailUnread=()=>mails.filter(m=>m.folder==='inbox'&&!m.read).length;
function mailApp(){A.view(A.nav('メール',`<button data-action="mailCompose" aria-label="作成">${icon('edit')}</button>`)+`<div class="app-content"><h1 class="app-title">${{inbox:'受信トレイ',sent:'デモ送信済み',draft:'下書き'}[mailFolder]} <span class="demo-label">LOCAL</span></h1>${A.search('mail-search','メールを検索')}<div id="mail-list"></div></div>`+A.tabs([{id:'inbox',icon:'mail',name:'受信',action:'mailFolder',value:'inbox'},{id:'sent',icon:'share',name:'デモ送信済み',action:'mailFolder',value:'sent'},{id:'draft',icon:'document',name:'下書き',action:'mailFolder',value:'draft'}],mailFolder));const render=q=>{$('#mail-list').innerHTML=mails.filter(m=>m.folder===mailFolder&&(m.sender+m.subject+m.body).includes(q)).map(m=>`<button class="inbox-row" data-action="mailOpen" data-id="${m.id}"><span class="inbox-unread ${m.read?'read':''}"></span><div class="inbox-body"><header><strong>${esc(m.sender)}</strong><time>${esc(m.time)} ›</time></header><h3>${esc(m.subject)}</h3><p>${esc(m.preview||m.body)}</p></div></button>`).join('')||A.empty('メールがありません。','mail');};render('');$('#mail-search').oninput=e=>render(e.target.value);}
A.apps.mail.render=mailApp;A.actions.mailList=mailApp;A.actions.mailFolder=el=>{mailFolder=el.dataset.value;mailApp();};
let openMail=null;
A.actions.mailOpen=el=>{const m=mails.find(m=>m.id===el.dataset.id);if(!m)return;openMail=m.id;m.read=true;A.save('mails',mails);A.view(A.nav('メール',`<button data-action="mailDelete" aria-label="削除">${icon('trash')}</button>`,'mailList','戻る')+`<div class="app-content"><h1 class="mail-detail-title">${esc(m.subject)}</h1><div class="mail-sender"><span class="avatar" style="background:linear-gradient(135deg,#c8b9a7,#a295ab)">${esc(m.initial||'私')}</span><div class="row-main"><strong>${esc(m.sender)}</strong><small>${esc(m.time)} · 宛先：${esc(m.to||'あなた')}</small></div></div><article class="mail-body">${esc(m.body)}</article><button class="secondary-button" data-action="mailReply" style="width:100%;margin:30px 0 10px">返信</button></div>`);};
function mailCompose(reply){const m=reply?mails.find(m=>m.id===openMail):null;A.view(A.nav('新規メール',`<button data-action="mailSave" style="font-size:12px">保存</button>`,'mailList','キャンセル')+`<div class="app-content"><p class="setting-description">デモ・外部送信なし</p><form id="mail-compose"><label class="form-label">宛先</label><input class="text-input" name="to" placeholder="name@example.com" value="${m?esc(m.sender):''}" required maxlength="150"><label class="form-label">件名</label><input class="text-input" name="subject" value="${m?'Re: '+esc(m.subject):''}" placeholder="件名" required maxlength="150"><label class="form-label">本文</label><textarea class="text-input" name="body" style="min-height:240px;line-height:1.9" placeholder="本文" required maxlength="10000"></textarea><button type="submit" class="primary-button" style="margin-top:20px">デモ送信</button></form></div>`);$('#mail-compose').onsubmit=e=>{e.preventDefault();storeMail('sent');};}
function storeMail(folder){const form=$('#mail-compose');if(!form)return;const v=Object.fromEntries(new FormData(form));mails.unshift({id:A.id(),sender:'あなた',initial:'私',...v,subject:v.subject||'件名なし',time:'今',read:true,folder});A.save('mails',mails);mailFolder=folder;mailApp();A.toast(folder==='sent'?'デモ保存済み・外部送信なし':'下書きに保存しました');}
A.actions.mailCompose=()=>mailCompose(false);A.actions.mailReply=()=>mailCompose(true);A.actions.mailSave=()=>storeMail('draft');A.actions.mailDelete=()=>A.confirm('メールを削除','このメールを削除しますか？',()=>{mails=mails.filter(m=>m.id!==openMail);A.save('mails',mails);mailApp();});
// Browser — polished local reading experience plus safe external navigation.
A.images={mountain:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85',forest:'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=900&q=85',coffee:'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=900&q=85',sea:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85',city:'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=900&q=85',flower:'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=900&q=85',desert:'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=900&q=85',lake:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=900&q=85',interior:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85'};
// Connected browsing is implemented in connected.js.
})();
