'use strict';
(() => {
const A=window.Aura,$=A.$,icon=A.icon;
let gamePage='library',gameCleanups=[];
const stopGame=()=>{gameCleanups.splice(0).forEach(fn=>fn());};
A.stopLegacyGames=stopGame;
const listenKey=fn=>{document.addEventListener('keydown',fn);gameCleanups.push(()=>document.removeEventListener('keydown',fn));};
function swipe(el,callback){let start=null;el.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY};el.setPointerCapture(e.pointerId);});el.addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.max(Math.abs(dx),Math.abs(dy))<17)return;callback(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');});el.addEventListener('pointercancel',()=>start=null);}
function library(){stopGame();gamePage='library';A.statusTheme(false);A.view(A.nav('ゲーム')+`<div class="app-content"><h1 class="app-title">ゲーム</h1><p class="app-subtitle"></p><div class="games-hero"><small>SMALL GAMES. BIG LITTLE JOYS.</small><h2>遊び心を、<br>ポケットに。</h2><p>シンプルだから、奥が深い。</p><span class="hero-block">2048</span></div><p class="section-label">YOUR LITTLE ARCADE</p><button class="game-card" data-action="gameOpen" data-game="2048"><span class="game-cover g2048">2048</span><div><strong>2048</strong><p>重ねて、つなげて、その先へ。</p><small>PUZZLE · BEST ${A.load('2048best',0).toLocaleString()}</small></div><span>›</span></button><button class="game-card" data-action="gameOpen" data-game="snake"><span class="game-cover gsnake">⌁</span><div><strong>Little Snake</strong><p>懐かしくて、新しい。</p><small>ARCADE · BEST ${A.load('snakeBest',0)}</small></div><span>›</span></button><button class="game-card" data-action="gameOpen" data-game="memory"><span class="game-cover gmemory">✿</span><div><strong>Memory Garden</strong><p>同じかたちを、見つけよう。</p><small>MEMORY · ${A.load('memoryBest',0)?'BEST '+A.load('memoryBest',0)+' MOVES':'TAKE YOUR TIME'}</small></div><span>›</span></button><p class="notes-footer">最高記録は端末内に保存</p></div>`);}
A.apps.games.render=arg=>{A.cleanups.push(stopGame);if(['2048','snake','memory'].includes(arg))openGame(arg);else library();};
A.actions.gamesLibrary=library;A.actions.gameOpen=el=>openGame(el.dataset.game);
function openGame(id){stopGame();gamePage=id;A.statusTheme(false);if(id==='2048')game2048();if(id==='snake')gameSnake();if(id==='memory')gameMemory();}
// 2048 — canonical single-merge-per-move rules, local progress, undo.
const saved2048=A.load('2048state',null);
let tiles=saved2048?.tiles?.length===16?saved2048.tiles:Array(16).fill(0),score=saved2048?.score||0,best=A.load('2048best',0),undo=null,won=false;
function spawn(){const empty=tiles.map((v,i)=>v===0?i:-1).filter(i=>i>=0);if(empty.length)tiles[empty[Math.floor(Math.random()*empty.length)]]=Math.random()<.9?2:4;}
if(!tiles.some(Boolean)){spawn();spawn();}
function save2048(){best=Math.max(best,score);A.save('2048best',best);A.save('2048state',{tiles,score});}
function mergeLine(line){const nonzero=line.filter(Boolean),out=[];let gain=0;for(let i=0;i<nonzero.length;i++){if(nonzero[i]===nonzero[i+1]){const value=nonzero[i]*2;out.push(value);gain+=value;i++;}else out.push(nonzero[i]);}while(out.length<4)out.push(0);return {line:out,gain};}
function movable(){if(tiles.includes(0))return true;for(let r=0;r<4;r++)for(let c=0;c<4;c++){const i=r*4+c;if(c<3&&tiles[i]===tiles[i+1])return true;if(r<3&&tiles[i]===tiles[i+4])return true;}return false;}
function move2048(direction){if(gamePage!=='2048'||!$('#overlay').hidden)return;const before=[...tiles],beforeScore=score;let gain=0;for(let row=0;row<4;row++){const indices=Array.from({length:4},(_,col)=>direction==='left'?row*4+col:direction==='right'?row*4+(3-col):direction==='up'?col*4+row:(3-col)*4+row);const result=mergeLine(indices.map(i=>tiles[i]));indices.forEach((i,k)=>tiles[i]=result.line[k]);gain+=result.gain;}if(before.every((v,i)=>v===tiles[i]))return;undo={tiles:before,score:beforeScore};score+=gain;spawn();save2048();render2048();A.haptic();if(!won&&tiles.includes(2048)){won=true;A.toast('2048達成');}}
function game2048(){A.view(A.nav('2048',`<button data-action="gameHelp" aria-label="遊び方">?</button>`,'gamesLibrary','ゲーム')+`<div class="app-content"><div class="game-heading"><h2>2048<span style="font-size:13px;margin-left:5px;letter-spacing:0">.</span></h2><div class="game-scores"><div class="score-badge"><small>SCORE</small><strong id="score-2048">${score}</strong></div><div class="score-badge" style="background:#b7a58e"><small>BEST</small><strong id="best-2048">${best}</strong></div></div></div><p class="game-instructions">スワイプ / 矢印キー</p><div class="board-2048" id="board-2048" aria-label="2048の盤面" tabindex="0"></div><div class="game-toolbar"><button data-action="undo2048">↶ 一手戻す</button><button data-action="restart2048">↻ もう一度</button></div><div class="game-status" id="status-2048" role="status"></div><div class="direction-pad" style="margin-top:10px">${[['up','↑'],['left','←'],['down','↓'],['right','→']].map(([d,s])=>`<button data-action="move2048" data-value="${d}" aria-label="${d}" style="color:#9c8b75;background:#e9e2d8;border-color:#ded4c6">${s}</button>`).join('')}</div><p class="notes-footer"></p></div>`);render2048();swipe($('#board-2048'),move2048);listenKey(e=>{const d={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key];if(d&&$('#overlay').hidden){e.preventDefault();move2048(d);}});}
function render2048(){if(!$('#board-2048'))return;$('#board-2048').innerHTML=tiles.map(v=>`<span class="tile-2048" data-value="${v}" data-large="${v>=128}">${v||''}</span>`).join('');$('#score-2048').textContent=score;$('#best-2048').textContent=best;$('#status-2048').textContent=!movable()?'終了・一手戻せます':tiles.some(v=>v>=2048)?'2048達成':'';}
A.actions.move2048=el=>move2048(el.dataset.value);A.actions.undo2048=()=>{if(!undo)return A.toast('戻せる手がありません');tiles=[...undo.tiles];score=undo.score;undo=null;save2048();render2048();};A.actions.restart2048=()=>A.confirm('新しい2048をはじめる','盤面をリセット。最高記録は保持',()=>{tiles=Array(16).fill(0);score=0;undo=null;won=false;spawn();spawn();save2048();render2048();});
// Snake — grid simulation, deterministic steering, pausing on app leave.
let snake=[],snakeDirection={x:1,y:0},snakeNext={x:1,y:0},snakeFood={x:12,y:8},snakeScore=0,snakeBest=A.load('snakeBest',0),snakeRunning=false,snakeOver=false,snakeInterval=null;
const snakeSize=18;
function resetSnake(){snake=[{x:7,y:9},{x:6,y:9},{x:5,y:9},{x:4,y:9}];snakeDirection={x:1,y:0};snakeNext={x:1,y:0};snakeScore=0;snakeRunning=false;snakeOver=false;spawnFood();}
function spawnFood(){const empty=[];for(let y=0;y<snakeSize;y++)for(let x=0;x<snakeSize;x++)if(!snake.some(s=>s.x===x&&s.y===y))empty.push({x,y});if(!empty.length){snakeRunning=false;snakeOver=true;clearInterval(snakeInterval);return;}snakeFood=empty[Math.floor(Math.random()*empty.length)];}
function stopSnake(){clearInterval(snakeInterval);snakeInterval=null;snakeRunning=false;}
function gameSnake(){if(!snake.length)resetSnake();gameCleanups.push(stopSnake);A.view(A.nav('Little Snake',`<button data-action="gameHelp" aria-label="遊び方">?</button>`,'gamesLibrary','ゲーム')+`<div class="app-content"><div class="game-heading"><h2 style="font-size:29px;color:#7f9675">Little Snake<span style="font-size:15px">.</span></h2><div class="score-badge" style="background:#9caa90"><small>BEST</small><strong id="snake-best">${snakeBest}</strong></div></div><p class="game-instructions" style="color:#8b9a83">実を集める・衝突に注意</p><div class="memory-meta" style="margin:17px 0 12px;color:#839578"><span>SCORE <strong id="snake-score">${snakeScore}</strong></span><span>18 × 18 GARDEN</span></div><canvas class="snake-board" id="snake-board" width="648" height="648" aria-label="スネークゲームの盤面"></canvas><div class="game-toolbar"><button data-action="snakeToggle" id="snake-toggle" style="background:#94a889;min-width:95px">${snakeOver?'もう一度':'▶ スタート'}</button><button data-action="snakeRestart" style="background:#dce3d7;color:#809373">↻ リセット</button></div><div class="game-status" id="snake-status" style="color:#829276">${snakeOver?'ゲームオーバー。もう一度、どうぞ。':'矢印キー・スワイプ・下のボタンで操作'}</div><div class="direction-pad">${[['up','↑'],['left','←'],['down','↓'],['right','→']].map(([d,s])=>`<button data-action="snakeDirection" data-value="${d}" aria-label="${d}">${s}</button>`).join('')}</div></div>`);drawSnake();swipe($('#snake-board'),steerSnake);listenKey(e=>{const d={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key];if(!$('#overlay').hidden)return;if(d){e.preventDefault();steerSnake(d);}if(e.code==='Space'){e.preventDefault();toggleSnake();}});}
function steerSnake(d){const direction={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}}[d];if(!direction)return;if(direction.x===-snakeDirection.x&&direction.y===-snakeDirection.y)return;snakeNext=direction;if(!snakeRunning&&!snakeOver)toggleSnake();}
function toggleSnake(){if(snakeOver){resetSnake();}if(snakeRunning)stopSnake();else{snakeRunning=true;clearInterval(snakeInterval);snakeInterval=setInterval(tickSnake,145);}updateSnakeUi();}
function updateSnakeUi(){if(!$('#snake-toggle'))return;$('#snake-toggle').textContent=snakeOver?'もう一度':snakeRunning?'Ⅱ 一時停止':'▶ スタート';$('#snake-score').textContent=snakeScore;$('#snake-best').textContent=snakeBest;$('#snake-status').textContent=snakeOver?'ゲームオーバー。もう一度、どうぞ。':snakeRunning?'':'矢印キー・スワイプ・下のボタンで操作';drawSnake();}
function tickSnake(){if(!snakeRunning)return;if(!$('#overlay').hidden||document.hidden)return;snakeDirection={...snakeNext};const head={x:snake[0].x+snakeDirection.x,y:snake[0].y+snakeDirection.y};const eating=head.x===snakeFood.x&&head.y===snakeFood.y;const body=eating?snake:snake.slice(0,-1);if(head.x<0||head.y<0||head.x>=snakeSize||head.y>=snakeSize||body.some(s=>s.x===head.x&&s.y===head.y)){snakeOver=true;stopSnake();updateSnakeUi();return;}snake.unshift(head);if(eating){snakeScore+=10;snakeBest=Math.max(snakeBest,snakeScore);A.save('snakeBest',snakeBest);spawnFood();A.haptic();}else snake.pop();updateSnakeUi();}
function drawSnake(){
 const c=$('#snake-board');if(!c)return;const ctx=c.getContext('2d'),size=c.width,cell=size/snakeSize;
 const ground=ctx.createLinearGradient(0,0,size,size);ground.addColorStop(0,'#ecf1e0');ground.addColorStop(1,'#bdcfb0');ctx.fillStyle=ground;ctx.fillRect(0,0,size,size);
 for(let y=0;y<snakeSize;y++)for(let x=0;x<snakeSize;x++){ctx.fillStyle=(x+y)%2?'#d5e3c52b':'#ffffff18';ctx.fillRect(x*cell,y*cell,cell,cell);if((x*7+y*3)%17===0){ctx.strokeStyle='#809d6922';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x*cell+12,y*cell+24);ctx.quadraticCurveTo(x*cell+10,y*cell+17,x*cell+8,y*cell+17);ctx.moveTo(x*cell+12,y*cell+24);ctx.quadraticCurveTo(x*cell+15,y*cell+16,x*cell+17,y*cell+19);ctx.stroke();}}
 const vignette=ctx.createRadialGradient(size/2,size/2,size*.15,size/2,size/2,size*.75);vignette.addColorStop(0,'#ffffff00');vignette.addColorStop(1,'#64865525');ctx.fillStyle=vignette;ctx.fillRect(0,0,size,size);
 const fx=(snakeFood.x+.5)*cell,fy=(snakeFood.y+.5)*cell;ctx.fillStyle='#d9b88a30';ctx.beginPath();ctx.arc(fx,fy,cell*.48,0,Math.PI*2);ctx.fill();ctx.shadowColor='#77634340';ctx.shadowBlur=5;ctx.shadowOffsetY=3;const fruit=ctx.createRadialGradient(fx-4,fy-5,2,fx,fy,cell*.31);fruit.addColorStop(0,'#e3b7a1');fruit.addColorStop(.45,'#cd917c');fruit.addColorStop(1,'#b47765');ctx.fillStyle=fruit;ctx.beginPath();ctx.arc(fx,fy,cell*.31,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.strokeStyle='#78875b';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(fx,fy-cell*.23);ctx.quadraticCurveTo(fx-2,fy-cell*.46,fx+4,fy-cell*.46);ctx.stroke();ctx.fillStyle='#859e69';ctx.beginPath();ctx.ellipse(fx+6,fy-cell*.3,cell*.15,cell*.07,-.4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff9';ctx.beginPath();ctx.ellipse(fx-4,fy-5,3,2,-.6,0,Math.PI*2);ctx.fill();
 ctx.shadowColor='#425f4240';ctx.shadowBlur=7;ctx.shadowOffsetY=4;ctx.strokeStyle='#769467';ctx.lineWidth=cell*.78;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();[...snake].reverse().forEach((p,i)=>i?ctx.lineTo((p.x+.5)*cell,(p.y+.5)*cell):ctx.moveTo((p.x+.5)*cell,(p.y+.5)*cell));ctx.stroke();ctx.shadowBlur=0;ctx.shadowOffsetY=0;
 [...snake].reverse().forEach((p,i)=>{const x=(p.x+.5)*cell,y=(p.y+.5)*cell,head=i===snake.length-1;const skin=ctx.createRadialGradient(x-cell*.13,y-cell*.18,1,x,y,cell*.45);skin.addColorStop(0,head?'#91b07a':'#abc193');skin.addColorStop(1,head?'#5d8052':'#769465');ctx.fillStyle=skin;ctx.beginPath();ctx.roundRect(p.x*cell+3,p.y*cell+3,cell-6,cell-6,head?13:10);ctx.fill();if(!head&&i%2===0){ctx.fillStyle='#dde9bf38';ctx.beginPath();ctx.arc(x-3,y-3,2.5,0,Math.PI*2);ctx.arc(x+3,y+3,2.5,0,Math.PI*2);ctx.fill();}});
 const h=snake[0],dx=snakeDirection.x,dy=snakeDirection.y;const eyes=dx?[{x:dx>0?.68:.32,y:.29},{x:dx>0?.68:.32,y:.71}]:[{x:.29,y:dy>0?.68:.32},{x:.71,y:dy>0?.68:.32}];for(const p of eyes){const x=(h.x+p.x)*cell,y=(h.y+p.y)*cell;ctx.fillStyle='#f9f7dd';ctx.beginPath();ctx.arc(x,y,cell*.13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#3b5440';ctx.beginPath();ctx.arc(x+dx*1.8,y+dy*1.8,cell*.065,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x+dx*1.8-1,y+dy*1.8-1,1,0,Math.PI*2);ctx.fill();}
 if(!snakeRunning){ctx.fillStyle='#e6eddb99';ctx.fillRect(0,0,size,size);ctx.fillStyle='#faf9e7d9';ctx.shadowColor='#516e3320';ctx.shadowBlur=25;ctx.beginPath();ctx.roundRect(size*.18,size*.39,size*.64,size*.22,25);ctx.fill();ctx.shadowBlur=0;ctx.textAlign='center';ctx.fillStyle='#5a7755';ctx.font='600 29px sans-serif';ctx.fillText(snakeOver?'GAME OVER':'LITTLE SNAKE',size/2,size*.49);ctx.font='17px sans-serif';ctx.fillStyle='#8d9d78';ctx.fillText(snakeOver?'SCORE '+snakeScore:'スタートでプレイ',size/2,size*.55);}
}
A.actions.snakeToggle=toggleSnake;A.actions.snakeDirection=el=>steerSnake(el.dataset.value);A.actions.snakeRestart=()=>{stopSnake();resetSnake();updateSnakeUi();};
// Memory Garden — shuffled pairs with a race-safe reveal timer.
const symbols=['✿','☀','☾','♧','♡','✦','☁','♫'];const colors=['#cd8d9a','#d2ae69','#a394c4','#91aa81','#d1a092','#a3b3c7','#8bb3c6','#b79ac1'];
let cards=[],flipped=[],matched=[],memoryMoves=0,memoryBusy=false,memoryTimeout=null,memoryBest=A.load('memoryBest',0),memoryStart=0,memorySeconds=0,memoryClock=null;
function shuffle(list){for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}return list;}
function resetMemory(){clearTimeout(memoryTimeout);cards=shuffle([...symbols,...symbols]);flipped=[];matched=[];memoryMoves=0;memoryBusy=false;memoryStart=0;memorySeconds=0;}
function gameMemory(){resetMemory();gameCleanups.push(()=>{clearTimeout(memoryTimeout);clearInterval(memoryClock);memoryBusy=false;});A.view(A.nav('Memory Garden',`<button data-action="gameHelp" aria-label="遊び方">?</button>`,'gamesLibrary','ゲーム')+`<div class="app-content"><div class="game-heading"><h2 style="font-size:28px;color:#9a88ac">Memory Garden<span style="font-size:15px">.</span></h2></div><p class="game-instructions" style="color:#a293ac">同じペア</p><div class="memory-meta" style="margin-top:25px"><span>MOVES <strong id="memory-moves">0</strong></span><span id="memory-time">00:00</span><span><strong id="memory-pairs">0</strong> / 8 PAIRS</span></div><div class="memory-board" id="memory-board"></div><div class="game-status" id="memory-status" style="color:#a08baa"></div><div class="game-toolbar"><button data-action="memoryRestart" style="background:#ad9abd">↻ 新しいお庭</button><span style="font-size:10px;color:#ad9abd;align-self:center" id="memory-best">BEST ${memoryBest?memoryBest+' MOVES':'—'}</span></div><p class="notes-footer"></p></div>`);renderMemory();memoryClock=setInterval(()=>{if(memoryStart&&matched.length<16){memorySeconds=Math.floor((Date.now()-memoryStart)/1000);if($('#memory-time'))$('#memory-time').textContent=`${String(Math.floor(memorySeconds/60)).padStart(2,'0')}:${String(memorySeconds%60).padStart(2,'0')}`;}},1000);}

function gardenArt(symbol){const content={
'✿':'<g fill="currentColor" opacity=".85"><ellipse cx="40" cy="25" rx="10" ry="16"/><ellipse cx="40" cy="55" rx="10" ry="16"/><ellipse cx="25" cy="40" rx="16" ry="10"/><ellipse cx="55" cy="40" rx="16" ry="10"/></g><circle cx="40" cy="40" r="8" fill="#e4c67e"/><circle cx="38" cy="37" r="2" fill="#fff5"/>',
'☀':'<g stroke="currentColor" stroke-width="3" stroke-linecap="round"><path d="M40 8v8m0 48v8M8 40h8m48 0h8M17 17l6 6m34 34 6 6M17 63l6-6m34-34 6-6"/></g><circle cx="40" cy="40" r="17" fill="currentColor"/><circle cx="35" cy="34" r="9" fill="#fff2"/>',
'☾':'<path d="M49 13a28 28 0 1 0 18 44A29 29 0 0 1 49 13Z" fill="currentColor"/><path d="m59 17 2 5 5 2-5 2-2 5-2-5-5-2 5-2Z" fill="#dfc48f"/>',
'♧':'<path d="M40 68V40" stroke="#83976a" stroke-width="3"/><path d="M40 48C12 50 10 20 18 15c23-1 26 17 22 33Z" fill="currentColor"/><path d="M40 44c-2-22 14-31 28-26 3 24-10 33-28 26Z" fill="currentColor" opacity=".7"/><path d="m20 24 20 25 20-23" stroke="#ffffff50" stroke-width="1.5" fill="none"/>',
'♡':'<path d="M40 66C29 57 12 44 12 30 12 12 34 12 40 27c6-15 28-15 28 3 0 14-17 27-28 36Z" fill="currentColor"/><path d="M22 32c-1-6 4-11 9-7" stroke="#fff6" stroke-width="3" fill="none" stroke-linecap="round"/>',
'✦':'<path d="m40 8 8 23 23 9-23 9-8 23-9-23-23-9 23-9Z" fill="currentColor"/><path d="m40 8 0 32 31 0-23-9Z" fill="#fff4"/><path d="m40 40 0 32-9-23-23-9Z" fill="#0000000e"/>',
'☁':'<path d="M20 59a14 14 0 1 1 1-28 20 20 0 0 1 39-2 15 15 0 0 1 1 30Z" fill="currentColor"/><path d="M20 34c3-5 7-6 11-5M33 26c7-9 17-5 19 0" stroke="#fff5" stroke-width="3" stroke-linecap="round" fill="none"/>',
'♫':'<path d="M29 55V25l28-7v31M29 34l28-7" stroke="currentColor" stroke-width="5" stroke-linejoin="round" fill="none"/><ellipse cx="20" cy="56" rx="12" ry="8" transform="rotate(-20 20 56)" fill="currentColor"/><ellipse cx="48" cy="50" rx="12" ry="8" transform="rotate(-20 48 50)" fill="currentColor"/>'
};return '<svg viewBox="0 0 80 80" aria-hidden="true">'+(content[symbol]||'<path d="m40 17 7 16 16 7-16 7-7 16-7-16-16-7 16-7Z" fill="none" stroke="#faf0ff99" stroke-width="1.5"/><circle cx="40" cy="40" r="4" fill="#f5e4ff66"/>')+'</svg>';}

function renderMemory(){if(!$('#memory-board'))return;$('#memory-board').innerHTML=cards.map((s,i)=>{const visible=flipped.includes(i)||matched.includes(i);return `<button class="memory-card ${visible?'flipped':''} ${matched.includes(i)?'matched':''}" data-action="memoryFlip" data-index="${i}" aria-label="${matched.includes(i)?'一致したカード':visible?s:'裏向きのカード '+(i+1)}" ${matched.includes(i)?'disabled':''}><span style="${visible?'color:'+colors[symbols.indexOf(s)]:''}">${gardenArt(visible?s:'back')}</span></button>`;}).join('');$('#memory-moves').textContent=memoryMoves;$('#memory-pairs').textContent=matched.length/2;}
function flipCard(index){if(memoryBusy||flipped.includes(index)||matched.includes(index))return;if(!memoryStart)memoryStart=Date.now();flipped.push(index);A.haptic();renderMemory();if(flipped.length===2){memoryMoves++;const [a,b]=flipped;if(cards[a]===cards[b]){matched.push(a,b);flipped=[];renderMemory();if(matched.length===16){const elapsed=Math.floor((Date.now()-memoryStart)/1000);memoryBest=memoryBest?Math.min(memoryBest,memoryMoves):memoryMoves;A.save('memoryBest',memoryBest);$('#memory-status').textContent=`お庭が完成！ ${memoryMoves}手・${elapsed}秒でクリア。`;$('#memory-best').textContent=`BEST ${memoryBest} MOVES`;A.toast('すべてのペアが見つかりました ✿');}else $('#memory-status').textContent='';}else{memoryBusy=true;renderMemory();$('#memory-status').textContent='';memoryTimeout=setTimeout(()=>{flipped=[];memoryBusy=false;if(gamePage==='memory')renderMemory();},800);}}}
A.actions.memoryFlip=el=>flipCard(+el.dataset.index);A.actions.memoryRestart=()=>{resetMemory();renderMemory();$('#memory-time').textContent='00:00';$('#memory-status').textContent='あせらず、ひとつずつ。';};
A.actions.gameHelp=()=>{const help=gamePage==='2048'?['2048 の遊び方','盤面を上下左右にスワイプすると、すべてのタイルが動きます。同じ数字がぶつかると合体し、数字が2倍になります。','合体した数字がスコアに加算されます。2048をつくった後も続けられます。動かせなくなったら終了です。','一手戻すは直前の1回だけ使用できます。進行状況とハイスコアは自動保存されます。']:gamePage==='snake'?['Little Snake の遊び方','スタートを押し、スワイプ・矢印キー・画面の方向ボタンでヘビを動かします。小さな実を食べると10点獲得します。','壁や自分の体にぶつかると終了です。来た方向へすぐに逆走することはできません。','アプリを離れると一時停止します。スペースキーでも一時停止できます。']:['Memory Garden の遊び方','カードを2枚めくり、同じ絵柄のペアを探しましょう。一致したカードは表向きのまま残ります。','8組のペアが揃えばクリア。2枚めくるたびに1手として数えます。少ない手数でのクリアに挑戦してください。','ハイスコアは最少手数です。アプリを開き直すと新しいお庭になります。'];A.overlay(`${A.overlayTitle(help[0])}<div class="about-copy">${help.slice(1).map(p=>`<p style="margin:22px 0">${p}</p>`).join('')}</div><button class="control-tile" data-action="closeOverlay" style="width:100%;margin-top:30px">遊んでみる</button>`);};
// Pure mechanics are exposed for regression tests; no production data hooks.
A.gameMath={mergeLine};
// Refresh badge counts now that every application has registered.
A.renderHome();
// Optional, documented deep links. All routes remain frontend-only.
const route=new URLSearchParams(location.hash.replace(/^#/,''));
if(route.get('app')&&A.apps[route.get('app')])A.open(route.get('app'),route.get('view')||undefined);
if(route.get('screen')==='lock')A.lock();
window.addEventListener('hashchange',()=>{const p=new URLSearchParams(location.hash.slice(1));if(p.get('app')&&A.apps[p.get('app')])A.open(p.get('app'),p.get('view')||undefined);else if(p.get('screen')==='lock')A.lock();else A.home();});
})();
