'use strict';
(() => {
const A=window.Aura,$=A.$,esc=A.escape,icon=A.icon;
// Photos and camera: samples are remote; imported/captured photos stay local.
const samplePhotos=[['lake','静かな湖'],['coffee','午後のコーヒー'],['mountain','山の稜線'],['flower','季節の花'],['sea','波の音'],['forest','木漏れ日'],['city','夜の街'],['desert','砂のかたち'],['interior','穏やかな部屋']].map(([key,title],i)=>({id:'sample-'+key,url:A.images[key],title,date:Date.now()-i*86400000,sample:true}));
let userPhotos=A.load('photos',[]),favorites=A.load('photoFavorites',[]),photoFilter='all',currentPhoto=null;
const allPhotos=()=>[...userPhotos,...samplePhotos];
const photoTabs=()=>A.tabs([{id:'all',icon:'photos',name:'ライブラリ',action:'photoFilter',value:'all'},{id:'favorites',icon:'heart',name:'お気に入り',action:'photoFilter',value:'favorites'},{id:'mine',icon:'camera',name:'自分の写真',action:'photoFilter',value:'mine'}],photoFilter);
function photos(){A.statusTheme(false);A.view(A.nav('写真',`<button data-action="photoImport" aria-label="写真を追加">${icon('plus')}</button>`)+`<div class="app-content"><h1 class="app-title">${photoFilter==='favorites'?'お気に入り':photoFilter==='mine'?'あなたの写真':'日々の、かけら。'}</h1><p class="app-subtitle">${photoFilter==='mine'?'カメラで撮影、または写真を追加できます。':'何気ない瞬間を、いつまでも。'}</p>${photoFilter==='all'?`<button class="photo-featured" data-action="photoOpen" data-id="sample-lake"><img src="${A.images.lake}" alt="山々に囲まれた湖"><span><small>A MOMENT TO REMEMBER</small>静けさを、集めて。</span></button><p class="section-label">すべての写真 · ${allPhotos().length}枚</p>`:''}<div class="photo-grid">${allPhotos().filter(p=>photoFilter==='favorites'?favorites.includes(p.id):photoFilter==='mine'?!p.sample:true).map(p=>`<button class="photo-tile" data-action="photoOpen" data-id="${p.id}" aria-label="${esc(p.title)}"><img src="${p.url}" alt="${esc(p.title)}" loading="lazy"></button>`).join('')}</div>${photoFilter==='mine'&&!userPhotos.length?A.empty('まだ写真がありません。<br>右上の＋から、思い出を追加しましょう。','camera'):photoFilter==='favorites'&&!favorites.length?A.empty('写真のハートを押すと、<br>ここに集まります。','heart'):''}<p class="notes-footer">${photoFilter==='mine'?'写真はこのブラウザに保存されます':'サンプル写真：Unsplash · 自分の写真も追加できます'}</p></div>`+photoTabs());}
A.apps.photos.render=photos;A.actions.photosHome=photos;A.actions.photoFilter=el=>{photoFilter=el.dataset.value;photos();};
function viewPhoto(id){const p=allPhotos().find(p=>p.id===id);if(!p)return;currentPhoto=id;A.statusTheme(true);A.view(A.nav(esc(p.title),'','photosHome','写真')+`<div class="photo-viewer"><img src="${p.url}" alt="${esc(p.title)}"></div><div class="photo-toolbar"><button data-action="photoPrevious" aria-label="前の写真">${icon('previous')}</button><button data-action="photoDownload" aria-label="写真をダウンロード">${icon('download')}</button><button class="${favorites.includes(id)?'liked':''}" data-action="photoFavorite" aria-label="お気に入り" aria-pressed="${favorites.includes(id)}">${icon('heart',favorites.includes(id)?'style="fill:currentColor"':'')}</button><button data-action="photoNext" aria-label="次の写真">${icon('next')}</button>${!p.sample?`<button data-action="photoDelete" aria-label="削除">${icon('trash')}</button>`:''}</div>`);}
A.actions.photoOpen=el=>viewPhoto(el.dataset.id);A.actions.photoFavorite=()=>{favorites=favorites.includes(currentPhoto)?favorites.filter(x=>x!==currentPhoto):[...favorites,currentPhoto];A.save('photoFavorites',favorites);viewPhoto(currentPhoto);};
const movePhoto=step=>{const list=allPhotos();viewPhoto(list[(list.findIndex(p=>p.id===currentPhoto)+step+list.length)%list.length].id);};A.actions.photoPrevious=()=>movePhoto(-1);A.actions.photoNext=()=>movePhoto(1);
A.actions.photoDelete=()=>A.confirm('写真を削除','このブラウザに保存された写真を削除します。',()=>{userPhotos=userPhotos.filter(p=>p.id!==currentPhoto);A.save('photos',userPhotos);photos();});
A.actions.photoDownload=async()=>{const p=allPhotos().find(p=>p.id===currentPhoto);try{const r=await fetch(p.url);if(!r.ok)throw Error();A.download(await r.blob(),`aura-${p.id}.jpg`);A.toast('写真のダウンロードを開始しました');}catch{A.toast('画像を取得できませんでした。通信を確認してください。');}};
A.storePhoto=(url,title)=>{const entry={id:A.id(),url,title,date:Date.now(),sample:false};const next=[entry,...userPhotos];if(A.save('photos',next)){userPhotos=next;return true;}return false;};
A.actions.photoImport=()=>{const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>{const file=input.files[0];if(!file)return;if(file.size>25*1024*1024)return A.toast('25MB以下の写真を選んでください');const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{const canvas=document.createElement('canvas'),scale=Math.min(1,1200/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const ok=A.storePhoto(canvas.toDataURL('image/jpeg',.82),file.name.replace(/\.[^.]+$/,''));URL.revokeObjectURL(url);if(ok){if(A.current==='photos')photos();A.toast('写真を追加しました');}};img.onerror=()=>{URL.revokeObjectURL(url);A.toast('この画像形式は読み込めませんでした');};img.src=url;};input.click();};
let cameraStream=null,cameraFacing='environment',cameraGrid=true,cameraSession=0;
function stopCamera(){cameraSession++;if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;}}
function camera(){A.statusTheme(true);A.view(A.nav('カメラ',`<button data-action="cameraGrid" aria-label="グリッド切り替え">${icon('grid')}</button>`)+`<div class="camera-preview" id="camera-preview"><video id="camera-video" playsinline autoplay muted></video><div class="camera-grid" id="camera-grid"></div><div class="camera-placeholder" id="camera-placeholder">${icon('camera')}<h3>今を、残そう。</h3><p>カメラへのアクセスを許可すると、<br>この画面で実際に撮影できます。</p><button class="primary-button" data-action="cameraStart">カメラを使う</button><button class="secondary-button" data-action="photoImport" style="background:#ffffff12;color:#c3c8d1;font-size:11px">端末の写真から追加</button><p style="font-size:9px;margin-top:24px">撮影した写真は、auraの「写真」に保存されます。<br>安全な接続（HTTPS）とカメラの許可が必要です。</p></div></div><div class="camera-bottom"><div class="camera-modes"><span>PHOTO STUDIO</span><span class="active">写真</span><span>1×</span></div><div class="camera-actions"><button class="camera-small" data-app="photos" aria-label="写真を開く">${icon('photos')}</button><button class="shutter" data-action="cameraCapture" aria-label="写真を撮影"></button><button class="camera-small" data-action="cameraFlip" aria-label="カメラ切り替え">${icon('refresh')}</button></div></div>`);$('#camera-grid').hidden=!cameraGrid;A.cleanups.push(stopCamera);}
A.apps.camera.render=camera;
A.actions.cameraStart=async()=>{if(!navigator.mediaDevices?.getUserMedia)return A.toast('この環境ではカメラを利用できません。写真を追加できます。');const token=++cameraSession;try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:cameraFacing,width:{ideal:1280},height:{ideal:1920}},audio:false});if(token!==cameraSession||A.current!=='camera'){stream.getTracks().forEach(t=>t.stop());return;}if(cameraStream)cameraStream.getTracks().forEach(t=>t.stop());cameraStream=stream;$('#camera-video').srcObject=stream;$('#camera-video').style.transform=cameraFacing==='user'?'scaleX(-1)':'';$('#camera-placeholder').hidden=true;await $('#camera-video').play();}catch(e){if(token===cameraSession)A.toast(e.name==='NotAllowedError'?'カメラの許可を確認してください':'カメラを起動できませんでした');}};
A.actions.cameraFlip=()=>{cameraFacing=cameraFacing==='user'?'environment':'user';if(cameraStream)stopCamera();A.actions.cameraStart();};A.actions.cameraGrid=()=>{cameraGrid=!cameraGrid;$('#camera-grid').hidden=!cameraGrid;};
A.actions.cameraCapture=()=>{const v=$('#camera-video');if(!cameraStream||!v?.videoWidth)return A.toast('先に「カメラを使う」をタップしてください');const c=document.createElement('canvas');const scale=Math.min(1,1200/Math.max(v.videoWidth,v.videoHeight));c.width=v.videoWidth*scale;c.height=v.videoHeight*scale;const ctx=c.getContext('2d');if(cameraFacing==='user'){ctx.translate(c.width,0);ctx.scale(-1,1);}ctx.drawImage(v,0,0,c.width,c.height);if(A.storePhoto(c.toDataURL('image/jpeg',.84),new Date().toLocaleDateString('ja-JP')+' の一枚')){A.haptic();A.toast('写真に保存しました');const preview=$('#camera-preview');preview.animate([{filter:'brightness(3)'},{filter:'brightness(1)'}],{duration:350});}};
// Music: original procedural ambient, synthesized entirely on-device.
const tracks=[{id:'dusk',title:'Golden Hour',artist:'aura sounds',album:'SLOW\nAFTERNOONS',art:'art-dusk',length:192,base:146.83,notes:[0,4,7,11,12,7,4,2],tempo:76},{id:'tide',title:'A Quiet Tide',artist:'aura sounds',album:'QUIET\nTIDES',art:'art-tide',length:214,base:130.81,notes:[0,3,7,10,14,10,7,3],tempo:64},{id:'orbit',title:'Somewhere, Softly',artist:'aura sounds',album:'SOFT\nORBIT',art:'art-orbit',length:186,base:164.81,notes:[0,5,7,12,16,12,7,5],tempo:82}];
const M=A.music={track:tracks[0],playing:false,position:0,startedAt:0,context:null,gain:null,scheduler:null,beat:0,liked:A.load('musicLikes',[])};
const fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
const art=(t,extra='')=>`<div class="album-art ${t.art} ${extra}"><small>AURA ORIGINALS / 0${tracks.indexOf(t)+1}</small><span>${t.album.replace('\n','<br>')}</span></div>`;
M.elapsed=()=>M.playing?Math.min(M.track.length,M.position+(Date.now()-M.startedAt)/1000):M.position;
M.setVolume=()=>{if(M.gain&&M.context)M.gain.gain.setTargetAtTime(A.settings.volume/100*.35,M.context.currentTime,.15);};
function audioInit(){if(!M.context){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('unsupported');M.context=new Audio();M.gain=M.context.createGain();M.gain.gain.value=A.settings.volume/100*.35;const compressor=M.context.createDynamicsCompressor();compressor.threshold.value=-16;compressor.ratio.value=4;M.gain.connect(compressor);compressor.connect(M.context.destination);}M.context.resume();}
function note(freq,time,duration,volume){const c=M.context,osc=c.createOscillator(),gain=c.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,time);gain.gain.exponentialRampToValueAtTime(volume,time+.08);gain.gain.exponentialRampToValueAtTime(.0001,time+duration);osc.connect(gain);gain.connect(M.gain);osc.start(time);osc.stop(time+duration+.05);osc.onended=()=>{osc.disconnect();gain.disconnect();};}
function synth(){if(!M.playing||!M.context)return;const t=M.context.currentTime,b=M.beat++,track=M.track;const semitone=track.notes[b%track.notes.length];note(track.base*Math.pow(2,semitone/12)*2,t,1.5,.14);if(b%4===0){[0,7,12].forEach((n,i)=>note(track.base*Math.pow(2,n/12),t+i*.025,3.2,.07));note(track.base/2,t,2,.12);}if(b%2===0)note(track.base*4,t+.23,.8,.035);}
M.start=()=>{try{audioInit();M.context.resume();M.startedAt=Date.now();M.playing=true;M.gain.gain.setTargetAtTime(A.settings.volume/100*.35,M.context.currentTime,.1);synth();clearInterval(M.scheduler);M.scheduler=setInterval(synth,60000/M.track.tempo/2);$('#phone-screen').classList.add('playing');refreshMusic();}catch{M.playing=false;A.toast('このブラウザでは音楽再生を利用できません');}};
M.pause=()=>{M.position=M.elapsed();M.playing=false;clearInterval(M.scheduler);if(M.gain)M.gain.gain.setTargetAtTime(0,M.context.currentTime,.1);$('#phone-screen').classList.remove('playing');refreshMusic();};
M.toggle=()=>M.playing?M.pause():M.start();
M.select=(id,play=true)=>{const next=tracks.find(t=>t.id===id);if(!next)return;if(M.playing)M.pause();M.track=next;M.position=0;M.beat=0;if(play)M.start();};
M.next=step=>{M.select(tracks[(tracks.indexOf(M.track)+step+tracks.length)%tracks.length].id,true);if(A.current==='music')music(musicPage);if(!$('#overlay').hidden&&$('#control-volume'))A.controls();};
M.tick=()=>{if(M.playing&&M.elapsed()>=M.track.length)M.next(1);const progress=$('#music-progress');if(progress&&document.activeElement!==progress)progress.value=M.elapsed();if($('#music-elapsed'))$('#music-elapsed').textContent=fmt(M.elapsed());if($('#music-remaining'))$('#music-remaining').textContent='−'+fmt(M.track.length-M.elapsed());};
let musicPage='home';
function music(arg){musicPage=arg==='player'?'player':'home';A.statusTheme(true);$('#app-screen').classList.add('music-app');if(musicPage==='player')return player();A.view(A.nav('ミュージック',`<button data-action="musicFavorites" aria-label="お気に入り">${icon('heart')}</button>`)+`<div class="app-content"><h1 class="app-title">聴く、くつろぐ。</h1><p class="app-subtitle">今日の気分に、小さなサウンドトラック。</p><div class="music-hero"><small>CURATED FOR YOUR SLOW MOMENTS</small><h3>A little less noise.<br>A little more you.</h3><p>静かな午後のための、音楽。</p><button data-action="musicPlayTrack" data-id="dusk" aria-label="Golden Hourを再生">${icon('play')}</button></div><p class="section-label" style="color:#a9a2ab;margin-bottom:13px">AURA ORIGINALS</p><div class="album-grid">${tracks.slice(0,2).map(t=>`<button class="album-card" data-action="musicPlayTrack" data-id="${t.id}">${art(t)}<h3>${t.title}</h3><p>AMBIENT · ${t.artist}</p></button>`).join('')}</div><p class="section-label">あなたのために</p>${tracks.map(t=>`<button class="track-row" data-action="musicPlayTrack" data-id="${t.id}">${art(t)}<div><strong>${t.title}</strong><small>${t.artist}</small></div><span>${fmt(t.length)}</span></button>`).join('')}<p class="setting-description" style="color:#777984;margin-top:20px">ブラウザが奏でるオリジナルのアンビエント。<br>音量を上げて、お楽しみください。</p></div>${miniPlayer()}`);}
function miniPlayer(){return `<div class="music-mini"><div class="mini-art ${M.track.art}"></div><button data-action="musicPlayer">${M.track.title}<small>${M.track.artist}</small></button><button data-action="musicToggle" aria-label="再生・一時停止" id="mini-play">${icon(M.playing?'pause':'play')}</button><button data-action="musicNext" aria-label="次の曲">${icon('next')}</button></div><div style="height:24px;background:#252329;flex-shrink:0"></div>`;}
function player(){const t=M.track;A.view(A.nav('再生中',`<button data-action="musicInfo" aria-label="音源について">···</button>`,'musicHome','閉じる')+`<div class="player-content">${art(t,'player-art')}<div class="player-info"><div><h2>${t.title}</h2><p>${t.artist}</p></div><button data-action="musicLike" id="music-like" aria-label="お気に入り" aria-pressed="${M.liked.includes(t.id)}">${M.liked.includes(t.id)?'♥':'♡'}</button></div><input class="music-progress" type="range" min="0" max="${t.length}" step="1" value="${M.elapsed()}" id="music-progress" aria-label="再生位置"><div class="progress-labels"><span id="music-elapsed">${fmt(M.elapsed())}</span><span id="music-remaining">−${fmt(t.length-M.elapsed())}</span></div><div class="player-controls"><button data-action="musicPrevious" aria-label="前の曲">${icon('previous')}</button><button class="main-play" data-action="musicToggle" id="player-play" aria-label="再生・一時停止">${icon(M.playing?'pause':'play')}</button><button data-action="musicNext" aria-label="次の曲">${icon('next')}</button></div><label class="player-volume">${icon('volume')}<input type="range" id="music-volume" min="0" max="100" value="${A.settings.volume}" aria-label="音量">${icon('volume')}</label><p style="text-align:center;font-size:8px;color:#968590;letter-spacing:2px;margin:20px 0 0">AURA ORIGINALS · PROCEDURAL AMBIENT</p></div>`);$('#music-progress').oninput=e=>{M.position=+e.target.value;M.startedAt=Date.now();M.tick();};$('#music-volume').oninput=e=>{A.settings.volume=+e.target.value;M.setVolume();A.save('settings',A.settings);};}
function refreshMusic(){if($('#mini-play'))$('#mini-play').innerHTML=icon(M.playing?'pause':'play');if($('#player-play'))$('#player-play').innerHTML=icon(M.playing?'pause':'play');}
A.apps.music.render=music;A.actions.musicHome=()=>music('home');A.actions.musicPlayer=()=>music('player');A.actions.musicToggle=M.toggle;A.actions.musicNext=()=>M.next(1);A.actions.musicPrevious=()=>M.next(-1);A.actions.musicPlayTrack=el=>{M.select(el.dataset.id,true);music('player');};A.actions.musicLike=()=>{M.liked=M.liked.includes(M.track.id)?M.liked.filter(x=>x!==M.track.id):[...M.liked,M.track.id];A.save('musicLikes',M.liked);$('#music-like').textContent=M.liked.includes(M.track.id)?'♥':'♡';$('#music-like').setAttribute('aria-pressed',M.liked.includes(M.track.id));};A.actions.musicInfo=()=>A.toast('aura originals — このブラウザで生成したオリジナル音源です');
A.actions.musicFavorites=()=>{A.view(A.nav('お気に入り','','musicHome','戻る')+`<div class="app-content"><h1 class="app-title">いつでも、そばに。</h1>${tracks.filter(t=>M.liked.includes(t.id)).map(t=>`<button class="track-row" data-action="musicPlayTrack" data-id="${t.id}">${art(t)}<div><strong>${t.title}</strong><small>${t.artist}</small></div>${icon('play','style="width:18px"')}</button>`).join('')||A.empty('好きな曲に、ハートを。','heart')}</div>${miniPlayer()}`);};
// Voice recorder: real microphone, explicit permission, temporary session blobs.
let recording=null,recorderStream=null,recordStart=0,recordInterval=null,recordItems=[],recorderGeneration=0;
function recorder(){A.statusTheme(false);A.view(A.nav('ボイスメモ')+`<div class="app-content" id="recorder-content"><h1 class="app-title">声も、思い出も。</h1><p class="app-subtitle">ふと思いついたことを、声で残そう。</p><div class="recorder-wave">${Array.from({length:65},(_,i)=>`<i style="height:${4+Math.abs(Math.sin(i*.71)*Math.cos(i*.19))*52}px;animation-delay:-${i*.08}s"></i>`).join('')}</div><div class="recorder-time" id="record-time">00:00</div><button class="record-button" id="record-button" data-action="recordToggle" aria-label="録音開始・停止"></button><p class="setting-description" id="record-hint" style="text-align:center">マイクの許可が必要です。<br>録音はアプリを閉じると削除されます。必要な音声は保存してください。</p><p class="section-label">このセッションの録音</p><div id="record-list"></div></div>`);renderRecordList();const token=++recorderGeneration;A.cleanups.push(()=>{if(recorderGeneration!==token)return;recorderGeneration++;if(recording?.state==='recording'){recording.onstop=null;recording.stop();}recorderStream?.getTracks().forEach(t=>t.stop());clearInterval(recordInterval);recording=null;recorderStream=null;recordItems.forEach(r=>URL.revokeObjectURL(r.url));recordItems=[];});}
function renderRecordList(){const el=$('#record-list');if(!el)return;el.innerHTML=recordItems.map(r=>`<article class="recording-row"><div style="flex:1;min-width:0"><strong style="font-size:11px;display:block;margin-bottom:10px">${esc(r.name)} · ${r.duration}</strong><audio controls playsinline src="${r.url}" aria-label="${esc(r.name)}"></audio></div><button data-action="recordDownload" data-id="${r.id}" aria-label="録音を保存" style="color:#7488a4">${icon('download','style="width:19px"')}</button></article>`).join('')||'<p class="empty-state" style="padding:10px">まだ録音がありません。</p>';}
A.apps.recorder.render=recorder;
A.actions.recordToggle=async()=>{if(recording?.state==='recording'){recording.stop();clearInterval(recordInterval);recorderStream?.getTracks().forEach(t=>t.stop());$('#recorder-content')?.classList.remove('recording');return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return A.toast('この環境では録音を利用できません');const token=recorderGeneration;$('#record-button').disabled=true;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(token!==recorderGeneration||A.current!=='recorder'){stream.getTracks().forEach(t=>t.stop());return;}recorderStream=stream;recording=new MediaRecorder(stream);const chunks=[];recording.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recording.onstop=()=>{if(token!==recorderGeneration)return;const type=recording.mimeType||'audio/webm';const blob=new Blob(chunks,{type});const duration=fmt((Date.now()-recordStart)/1000);recordItems.unshift({id:A.id(),name:'新規録音 '+(recordItems.length+1),blob,url:URL.createObjectURL(blob),duration,type});renderRecordList();A.toast('録音しました。保存ボタンで音声を持ち出せます。');};recording.start();recordStart=Date.now();$('#recorder-content').classList.add('recording');$('#record-time').textContent='00:00';recordInterval=setInterval(()=>{const el=$('#record-time');if(el)el.textContent=fmt((Date.now()-recordStart)/1000).padStart(5,'0');},300);}catch(e){A.toast(e.name==='NotAllowedError'?'マイクの許可を確認してください':'録音を開始できませんでした');}finally{if($('#record-button'))$('#record-button').disabled=false;}};
A.actions.recordDownload=el=>{const r=recordItems.find(r=>r.id===el.dataset.id);if(r)A.download(r.blob,`aura-recording-${r.id}.${r.type.includes('mp4')?'m4a':r.type.includes('ogg')?'ogg':'webm'}`);};
// Weather: openly labelled illustrative forecast, not live weather.
const cities=[{name:'東京',temp:26,low:21,high:28,desc:'晴れ',condition:'☀',humidity:62,wind:3.2},{name:'京都',temp:28,low:22,high:30,desc:'晴れ時々くもり',condition:'☀',humidity:66,wind:2.1},{name:'札幌',temp:22,low:16,high:24,desc:'くもり',condition:'☁',humidity:71,wind:4.3},{name:'那覇',temp:31,low:27,high:32,desc:'晴れ',condition:'☀',humidity:78,wind:5.6}];let cityIndex=A.load('weatherCity',0);
A.weatherSnapshot=()=>cities[cityIndex]||cities[0];
function weather(){const c=cities[cityIndex]||cities[0];A.statusTheme(true);$('#app-screen').classList.add('weather-app');A.view(A.nav('天気',`<button data-action="weatherCities" aria-label="都市を選ぶ">${icon('plus')}</button>`)+`<div class="app-content"><section class="weather-summary"><h2>${c.name}</h2><div class="big-temperature">${c.temp}°</div><p>${c.desc}</p><small>最高 ${c.high}°　最低 ${c.low}°</small><span style="display:block;margin-top:12px;font-size:8px;opacity:.6;letter-spacing:1.2px">SAMPLE WEATHER / NOT LIVE</span></section><div class="weather-card"><p style="font-size:10px;line-height:1.8;margin:0 0 13px">${c.condition}　午後も、心地よい天気が続きます。</p><div class="hourly-forecast">${[0,1,2,3,4,5].map((_,i)=>`<div><span>${i===0?'現在':((new Date().getHours()+i)%24)+'時'}</span><span class="condition">${i===4?'☁':c.condition}</span><span>${c.temp+[0,1,2,1,0,-1][i]}°</span></div>`).join('')}</div></div><div class="weather-card"><h3>▦　7日間の天気予報</h3>${['今日','月','火','水','木','金','土'].map((d,i)=>`<div class="forecast-row"><span>${i===0?'今日':['日','月','火','水','木','金','土'][(new Date().getDay()+i)%7]}</span><span class="condition">${['☀','☀','☁','☀','☂','☁','☀'][i]}</span><span style="opacity:.65">${c.low+[0,1,0,-1,-2,-1,1][i]}°</span><div class="temp-range" style="opacity:${i===4?.65:1}"></div><span>${c.high+[0,1,-1,0,-3,-1,1][i]}°</span></div>`).join('')}</div><div class="weather-stats"><div class="weather-card weather-stat"><h3>☀　UV指数</h3><strong>5</strong><p>中程度</p><div class="temp-range" style="margin:12px 0 0"></div></div><div class="weather-card weather-stat"><h3>≋　風</h3><strong>${c.wind} <span style="font-size:13px">m/s</span></strong><p>南東から、穏やかな風。</p></div><div class="weather-card weather-stat"><h3>♧　湿度</h3><strong>${c.humidity}%</strong><p>心地よく過ごせる湿度。</p></div><div class="weather-card weather-stat"><h3>◒　日の入り</h3><strong>18:04</strong><p>日の出：5:18</p></div></div><p class="control-footer" style="margin-top:4px">天気は体験用のサンプルデータです。<br>実際の予報・防災情報には使用しないでください。</p></div>`);}
A.apps.weather.render=weather;A.actions.weatherCities=()=>A.overlay(`${A.overlayTitle('お気に入りの場所')}<div class="group-card" style="background:#ffffff20">${cities.map((c,i)=>`<button class="list-row" data-action="weatherSelect" data-value="${i}" style="color:white"><span class="row-main"><strong>${c.name}</strong><small style="color:#fffb">${c.desc} · サンプル</small></span><span style="font-size:31px">${c.temp}°</span></button>`).join('')}</div>`);A.actions.weatherSelect=el=>{cityIndex=+el.dataset.value;A.save('weatherCity',cityIndex);A.closeOverlay();weather();};
// Maps: hand-drawn vector streets with panning, zoom, local search, demo routes.
const places=[{id:'cafe',name:'喫茶 余白',type:'カフェ',distance:'徒歩 4分',desc:'大きな窓と、ゆっくり流れる時間。',emoji:'☕',x:360,y:620},{id:'park',name:'こもれび公園',type:'公園',distance:'徒歩 8分',desc:'木々に囲まれた、小さな都会のオアシス。',emoji:'♧',x:545,y:445},{id:'book',name:'栞の書店',type:'書店',distance:'徒歩 6分',desc:'次の一冊と出会う、静かな本屋。',emoji:'▤',x:305,y:445},{id:'cafe2',name:'ベーカリー 小麦日和',type:'カフェ',distance:'徒歩 5分',desc:'朝焼きのパンと、季節のスープ。',emoji:'♨',x:465,y:680}];
let mapX=0,mapY=0,mapZoom=1,mapCategory='',mapQuery='',selectedPlace=null,mapRoute=false;
function mapSvg(){let blocks='';for(let y=100;y<1050;y+=95)for(let x=20;x<850;x+=95){const n=(x+y)%7;blocks+=`<rect x="${x}" y="${y}" width="77" height="77" rx="5" fill="${['#e2e0d9','#dedfd6','#e8e6dc'][Math.floor((x+y)/5)%3]}"/><rect x="${x+8}" y="${y+9}" width="26" height="${30+n*3}" rx="2" fill="#d5d5cd"/><rect x="${x+44}" y="${y+12}" width="23" height="45" rx="2" fill="#d3d5cf"/>`;}
return `<svg class="map-drawing" id="map-drawing" viewBox="0 0 900 1150" xmlns="http://www.w3.org/2000/svg"><rect width="900" height="1150" fill="#f0eee4"/>${blocks}<path d="M-30 40C250 330 110 570 340 850S700 1090 960 1180" stroke="#a9cfd7" stroke-width="100" fill="none"/><path d="M-30 40C250 330 110 570 340 850S700 1090 960 1180" stroke="#c2dfe3" stroke-width="74" fill="none"/><path d="M0 485 920 210M0 775 900 665M425-30 455 1200" stroke="#d8cdb9" stroke-width="28" fill="none"/><path d="M0 485 920 210M0 775 900 665M425-30 455 1200" stroke="#fff8e6" stroke-width="22" fill="none"/><path d="M0 1010 900 845" stroke="#c4bfc0" stroke-width="8"/><path d="M0 1010 900 845" stroke="#f4f1ed" stroke-width="3" stroke-dasharray="6 4"/><path d="M510 350h110q20 0 20 20v160h-120q-20 0-20-20V370Z" fill="#c8dab9"/><path d="m523 375 92 119m-92 0 92-119" stroke="#e5ebd9" stroke-width="8"/>${Array.from({length:13},(_,i)=>`<circle cx="${511+(i*23)%113}" cy="${358+(i*37)%165}" r="${7+i%4}" fill="#b5cda5"/>`).join('')}<g font-family="sans-serif" font-size="12" fill="#919993" text-anchor="middle"><text x="320" y="270">青葉二丁目</text><text x="650" y="620">緑町</text><text x="300" y="820">川辺通り</text><text x="735" y="870">南青葉</text><text x="420" y="500" transform="rotate(88 420 500)" font-size="10">けやき通り</text><text x="545" y="555" fill="#8ba180" font-size="11">こもれび公園</text><text x="493" y="935" fill="#959092">青葉駅</text></g><rect x="444" y="926" width="17" height="17" rx="4" fill="#9ba1a6"/><text x="452" y="939" fill="white" font-size="13" text-anchor="middle">▥</text>${places.map(p=>`<g data-action="mapPlace" data-id="${p.id}" style="cursor:pointer"><circle cx="${p.x}" cy="${p.y}" r="13" fill="${p.type==='公園'?'#83a575':p.type==='書店'?'#9187aa':'#d0a472'}" stroke="white" stroke-width="3"/><text x="${p.x}" y="${p.y+4}" text-anchor="middle" font-size="12" fill="white">${p.emoji}</text><text x="${p.x+20}" y="${p.y+4}" font-family="sans-serif" font-size="11" fill="#7c847d">${p.name}</text></g>`).join('')}<path id="map-route" d="M450 545v77h-90" stroke="#5d8ee8" stroke-width="7" stroke-linecap="round" stroke-linejoin="round" fill="none" style="display:none"/><circle cx="450" cy="545" r="18" fill="#5988e820"/><circle cx="450" cy="545" r="8" fill="#508be4" stroke="white" stroke-width="3"/></svg>`;}
function maps(){A.statusTheme(false);$('#app-screen').classList.add('maps-app');A.view(`<div class="map-canvas" id="map-canvas">${mapSvg()}</div><div class="map-top"><button data-action="home" aria-label="ホーム">‹</button>${A.search('map-search','場所を検索')}</div><div class="map-zoom"><button data-action="mapZoom" data-value=".2" aria-label="拡大">+</button><button data-action="mapZoom" data-value="-.2" aria-label="縮小">−</button><button data-action="mapLocate" aria-label="表示をリセット" style="font-size:18px">⌖</button></div><div class="map-sheet" id="map-sheet"></div>`);selectedPlace=null;mapRoute=false;renderMapSheet();applyMap();$('#map-search').oninput=e=>{mapQuery=e.target.value;selectedPlace=null;renderMapSheet();};const c=$('#map-canvas');let down=null;c.onpointerdown=e=>{if(e.target.closest('[data-action]'))return;down={x:e.clientX,y:e.clientY,ox:mapX,oy:mapY};c.setPointerCapture(e.pointerId);};c.onpointermove=e=>{if(!down)return;mapX=Math.max(-250,Math.min(250,down.ox+e.clientX-down.x));mapY=Math.max(-300,Math.min(300,down.oy+e.clientY-down.y));applyMap();};c.onpointerup=c.onpointercancel=()=>down=null;c.onwheel=e=>{e.preventDefault();mapZoom=Math.max(.7,Math.min(2.2,mapZoom-e.deltaY*.001));applyMap();};c.addEventListener('wheel',c.onwheel,{passive:false});}
function applyMap(){const d=$('#map-drawing');if(d)d.style.transform=`translate(${mapX}px,${mapY}px) scale(${mapZoom})`;}
function renderMapSheet(){const el=$('#map-sheet');if(!el)return;if(selectedPlace){const p=places.find(p=>p.id===selectedPlace);el.innerHTML=`<div class="sheet-handle"></div><button data-action="mapBack" style="float:right;color:#969ba1;font-size:23px">×</button><h2>${p.emoji} ${p.name}</h2><p>${p.type} · ${p.distance}<br>${p.desc}</p><div style="font-size:11px;color:#baa16e;margin:15px 0">★★★★★ <span style="color:#979b9f">4.8 · サンプルスポット</span></div><button class="primary-button" data-action="mapRoute">${icon('arrow')}${mapRoute?'ルート表示を終了':'デモルートを表示'}</button><p style="margin-bottom:0;font-size:9px">架空の地図です。実際の移動には使用できません。</p>`;return;}const filtered=places.filter(p=>(!mapCategory||p.type===mapCategory)&&(p.name+p.type).includes(mapQuery));el.innerHTML=`<div class="sheet-handle"></div><h2>いつもと違う、帰り道。</h2><p>青葉エリアを探索 <span class="demo-label">架空の地図</span></p><div class="map-categories">${[['カフェ','☕'],['公園','♧'],['書店','▤']].map(([c,e])=>`<button class="${mapCategory===c?'active':''}" data-action="mapCategory" data-value="${c}">${e} ${c}</button>`).join('')}</div>${filtered.map(p=>`<button class="place-row" data-action="mapPlace" data-id="${p.id}"><span>${p.emoji}</span><div><strong>${p.name}</strong><small>${p.type} · おすすめの場所</small></div><small>${p.distance}</small></button>`).join('')||'<p style="font-size:11px;color:#999">該当する場所はありません。</p>'}`;}
A.apps.maps.render=maps;A.actions.mapZoom=el=>{mapZoom=Math.max(.7,Math.min(2.2,mapZoom+ +el.dataset.value));applyMap();};A.actions.mapLocate=()=>{mapX=0;mapY=0;mapZoom=1;applyMap();};A.actions.mapCategory=el=>{mapCategory=mapCategory===el.dataset.value?'':el.dataset.value;renderMapSheet();};A.actions.mapPlace=el=>{selectedPlace=el.dataset.id;mapRoute=false;if($('#map-route'))$('#map-route').style.display='none';renderMapSheet();};A.actions.mapBack=()=>{selectedPlace=null;mapRoute=false;$('#map-route').style.display='none';renderMapSheet();};A.actions.mapRoute=()=>{mapRoute=!mapRoute;const p=places.find(p=>p.id===selectedPlace);$('#map-route').setAttribute('d',`M450 545V${p.y}H${p.x}`);$('#map-route').style.display=mapRoute?'':'none';renderMapSheet();};
})();
