'use strict';
(() => {
const A=window.Aura,$=A.$,esc=A.escape,icon=A.icon;
// Photos and camera: samples are remote; imported/captured photos stay local.
const samplePhotos=[['lake','静かな湖'],['coffee','午後のコーヒー'],['mountain','山の稜線'],['flower','季節の花'],['sea','波の音'],['forest','木漏れ日'],['city','夜の街'],['desert','砂のかたち'],['interior','穏やかな部屋']].map(([key,title],i)=>({id:'sample-'+key,url:A.images[key],title,date:Date.now()-i*86400000,sample:true}));
let userPhotos=A.load('photos',[]),favorites=A.load('photoFavorites',[]),photoFilter='all',currentPhoto=null;
const allPhotos=()=>[...userPhotos,...samplePhotos];
const albumPhotos=()=>allPhotos().filter(p=>photoFilter==='favorites'?favorites.includes(p.id):photoFilter==='mine'?!p.sample:true);
const photoTabs=()=>A.tabs([{id:'all',icon:'photos',name:'ライブラリ',action:'photoFilter',value:'all'},{id:'favorites',icon:'heart',name:'お気に入り',action:'photoFilter',value:'favorites'},{id:'mine',icon:'camera',name:'自分の写真',action:'photoFilter',value:'mine'}],photoFilter);
function photos(){A.statusTheme(false);A.view(A.nav('写真',`<button data-action="photoImport" aria-label="写真を追加">${icon('plus')}</button>`)+`<div class="app-content"><h1 class="app-title">${photoFilter==='favorites'?'お気に入り':photoFilter==='mine'?'自分の写真':'写真'}</h1>${photoFilter==='all'?`<button class="photo-featured" data-action="photoOpen" data-id="sample-lake"><img src="${A.images.lake}" alt="山々に囲まれた湖"></button><p class="section-label">すべての写真 · ${allPhotos().length}枚</p>`:''}<div class="photo-grid">${albumPhotos().map(p=>`<button class="photo-tile" data-action="photoOpen" data-id="${p.id}" aria-label="${esc(p.title)}"><img src="${p.url}" alt="${esc(p.title)}" loading="lazy"></button>`).join('')}</div>${photoFilter==='mine'&&!userPhotos.length?A.empty('＋で写真を追加','camera'):photoFilter==='favorites'&&!favorites.length?A.empty('お気に入りなし','heart'):''}<p class="notes-footer">${photoFilter==='mine'?'写真は端末内に保存':'サンプル：Unsplash'}</p></div>`+photoTabs());}
A.apps.photos.render=photos;A.actions.photosHome=photos;A.actions.photoFilter=el=>{photoFilter=el.dataset.value;photos();};
function viewPhoto(id){const p=allPhotos().find(p=>p.id===id);if(!p)return;currentPhoto=id;A.statusTheme(true);A.view(A.nav(esc(p.title),'','photosHome','写真')+`<div class="photo-viewer"><img src="${p.url}" alt="${esc(p.title)}"></div><div class="photo-toolbar"><button data-action="photoPrevious" aria-label="前の写真">${icon('previous')}</button><button data-action="photoShare" aria-label="写真を共有">${icon('share')}</button><button data-action="photoDownload" aria-label="写真をダウンロード">${icon('download')}</button><button class="${favorites.includes(id)?'liked':''}" data-action="photoFavorite" aria-label="お気に入り" aria-pressed="${favorites.includes(id)}">${icon('heart',favorites.includes(id)?'style="fill:currentColor"':'')}</button><button data-action="photoNext" aria-label="次の写真">${icon('next')}</button>${!p.sample?`<button data-action="photoDelete" aria-label="削除">${icon('trash')}</button>`:''}</div>`);}
A.actions.photoOpen=el=>viewPhoto(el.dataset.id);A.actions.photoFavorite=()=>{const next=favorites.includes(currentPhoto)?favorites.filter(x=>x!==currentPhoto):[...favorites,currentPhoto];if(!A.save('photoFavorites',next))return;favorites=next;viewPhoto(currentPhoto);};
const movePhoto=step=>{const list=albumPhotos();if(!list.length)return photos();const index=list.findIndex(p=>p.id===currentPhoto),next=index<0?(step>0?0:list.length-1):(index+step+list.length)%list.length;viewPhoto(list[next].id);};A.actions.photoPrevious=()=>movePhoto(-1);A.actions.photoNext=()=>movePhoto(1);
A.actions.photoDelete=()=>A.confirm('写真を削除','このブラウザに保存された写真を削除します。',()=>{const next=userPhotos.filter(p=>p.id!==currentPhoto),nextFavorites=favorites.filter(id=>id!==currentPhoto);if(!A.save('photoFavorites',nextFavorites))return;if(!A.save('photos',next)){A.save('photoFavorites',favorites);return;}userPhotos=next;favorites=nextFavorites;photos();});
A.actions.photoShare=async()=>{const root=$('.photo-viewer'),p=allPhotos().find(p=>p.id===currentPhoto);if(!root||!p)return A.toast('先に共有する写真を開いてください');A.toast('共有する写真を準備中…');try{const response=await fetch(p.url,{signal:AbortSignal.timeout(15000),credentials:'omit'});if(!response.ok)throw Error();const blob=await response.blob();if(A.current==='photos'&&root.isConnected)A.network.offerFile(blob,`aura-${p.id}.jpg`);}catch{A.toast('写真を取得できません。通信を確認。');}};
A.actions.photoDownload=async()=>{const p=allPhotos().find(p=>p.id===currentPhoto);try{const r=await fetch(p.url);if(!r.ok)throw Error();A.download(await r.blob(),`aura-${p.id}.jpg`);A.toast('写真のダウンロードを開始済み');}catch{A.toast('画像を取得できません。通信を確認。');}};
A.storePhoto=(url,title)=>{const entry={id:A.id(),url,title,date:Date.now(),sample:false};const next=[entry,...userPhotos];if(A.save('photos',next)){userPhotos=next;return true;}return false;};
A.actions.photoImport=()=>{const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>{const file=input.files[0];if(!file)return;if(file.size>25*1024*1024)return A.toast('25MB以下の写真を選択');const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{const canvas=document.createElement('canvas'),scale=Math.min(1,1200/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const ok=A.storePhoto(canvas.toDataURL('image/jpeg',.82),file.name.replace(/\.[^.]+$/,''));URL.revokeObjectURL(url);if(ok){if(A.current==='photos')photos();A.toast('写真を追加済み');}};img.onerror=()=>{URL.revokeObjectURL(url);A.toast('この画像形式は読み込めませんでした');};img.src=url;};input.click();};
let cameraStream=null,cameraFacing='environment',cameraGrid=true,cameraSession=0;
function stopCamera(){cameraSession++;if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;}}
function camera(){A.statusTheme(true);A.view(A.nav('カメラ',`<button data-action="cameraGrid" aria-label="グリッド切り替え">${icon('grid')}</button>`)+`<div class="camera-preview" id="camera-preview"><video id="camera-video" playsinline autoplay muted></video><div class="camera-grid" id="camera-grid"></div><div class="camera-placeholder" id="camera-placeholder">${icon('camera')}<button class="primary-button" data-action="cameraStart">カメラを使う</button><button class="secondary-button" data-action="photoImport" style="background:#ffffff12;color:#c3c8d1;font-size:11px">端末の写真から追加</button><p style="font-size:9px;margin-top:24px">auraの写真に保存。HTTPS・カメラ許可が必要</p></div></div><div class="camera-bottom"><div class="camera-modes"><span class="active">写真</span><span>1×</span></div><div class="camera-actions"><button class="camera-small" data-app="photos" aria-label="写真を開く">${icon('photos')}</button><button class="shutter" data-action="cameraCapture" aria-label="写真を撮影"></button><button class="camera-small" data-action="cameraFlip" aria-label="カメラ切り替え">${icon('refresh')}</button></div></div>`);$('#camera-grid').hidden=!cameraGrid;A.cleanups.push(stopCamera);}
A.apps.camera.render=camera;
A.actions.cameraStart=async()=>{if(!navigator.mediaDevices?.getUserMedia)return A.toast('この環境ではカメラを利用できません。写真を追加できます。');const token=++cameraSession;try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:cameraFacing,width:{ideal:1280},height:{ideal:1920}},audio:false});if(token!==cameraSession||A.current!=='camera'){stream.getTracks().forEach(t=>t.stop());return;}if(cameraStream)cameraStream.getTracks().forEach(t=>t.stop());cameraStream=stream;$('#camera-video').srcObject=stream;$('#camera-video').style.transform=cameraFacing==='user'?'scaleX(-1)':'';$('#camera-placeholder').hidden=true;await $('#camera-video').play();}catch(e){if(token===cameraSession)A.toast(e.name==='NotAllowedError'?'カメラの許可を確認してください':'カメラを起動できませんでした');}};
A.actions.cameraFlip=()=>{cameraFacing=cameraFacing==='user'?'environment':'user';if(cameraStream)stopCamera();A.actions.cameraStart();};A.actions.cameraGrid=()=>{cameraGrid=!cameraGrid;$('#camera-grid').hidden=!cameraGrid;};
A.actions.cameraCapture=()=>{const v=$('#camera-video');if(!cameraStream||!v?.videoWidth)return A.toast('先にカメラを起動');const c=document.createElement('canvas');const scale=Math.min(1,1200/Math.max(v.videoWidth,v.videoHeight));c.width=v.videoWidth*scale;c.height=v.videoHeight*scale;const ctx=c.getContext('2d');if(cameraFacing==='user'){ctx.translate(c.width,0);ctx.scale(-1,1);}ctx.drawImage(v,0,0,c.width,c.height);if(A.storePhoto(c.toDataURL('image/jpeg',.84),new Date().toLocaleDateString('ja-JP')+' の一枚')){A.haptic();A.toast('写真に保存済み');const preview=$('#camera-preview');preview.animate([{filter:'brightness(3)'},{filter:'brightness(1)'}],{duration:350});}};
// Music: original procedural ambient, synthesized entirely on-device.
const tracks=[{id:'dusk',title:'Golden Hour',artist:'aura sounds',album:'SLOW\nAFTERNOONS',art:'art-dusk',length:192,base:146.83,notes:[0,4,7,11,12,7,4,2],tempo:76},{id:'tide',title:'A Quiet Tide',artist:'aura sounds',album:'QUIET\nTIDES',art:'art-tide',length:214,base:130.81,notes:[0,3,7,10,14,10,7,3],tempo:64},{id:'orbit',title:'Somewhere, Softly',artist:'aura sounds',album:'SOFT\nORBIT',art:'art-orbit',length:186,base:164.81,notes:[0,5,7,12,16,12,7,5],tempo:82}];
const M=A.music={track:tracks[0],playing:false,position:0,startedAt:0,context:null,gain:null,scheduler:null,beat:0,liked:A.load('musicLikes',[])};
const fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
// Original local SVG covers: unique paint IDs, no downloads or generated-image dependencies.
let musicArtSerial=0;
A.musicArtwork=(track='dusk',record=false)=>{
  const id=`music-cover-${++musicArtSerial}`,t=tracks.find(t=>t.id===track)||tracks[0],tide=t.id==='tide',orbit=t.id==='orbit';
  const colors=tide?['#d8e5df','#7fa8b1','#244b67']:orbit?['#e0cbe6','#867fac','#353652']:['#f8d7a6','#d2957f','#555f67'];
  return `<svg class="music-cover-art ${record?'music-record-art':''}" viewBox="0 0 320 240" aria-hidden="true" focusable="false"><defs><linearGradient id="${id}-sky" x2=".6" y2="1"><stop stop-color="${colors[0]}"/><stop offset=".6" stop-color="${colors[1]}"/><stop offset="1" stop-color="${colors[2]}"/></linearGradient><radialGradient id="${id}-sun"><stop stop-color="#fff9df"/><stop offset="1" stop-color="${colors[0]}"/></radialGradient><linearGradient id="${id}-vinyl" x2="1" y2="1"><stop stop-color="#444951"/><stop offset=".3" stop-color="#191d23"/><stop offset=".55" stop-color="#454952"/><stop offset=".7" stop-color="#111821"/><stop offset="1" stop-color="#333b45"/></linearGradient><clipPath id="${id}-clip"><rect x="10" y="10" width="300" height="220" rx="14"/></clipPath></defs>
  <g clip-path="url(#${id}-clip)"><rect x="10" y="10" width="300" height="220" fill="url(#${id}-sky)"/><circle cx="${orbit?162:224}" cy="${orbit?100:81}" r="${orbit?56:36}" fill="url(#${id}-sun)"/>
  ${orbit?'<ellipse cx="162" cy="100" rx="115" ry="24" transform="rotate(-24 162 100)" fill="none" stroke="#eee3f0" stroke-opacity=".55" stroke-width="2"/><circle cx="77" cy="65" r="2" fill="#fff5ec"/><circle cx="257" cy="46" r="1.5" fill="#fff5ec"/>':`<path d="M0 154Q70 ${tide?109:57} 142 142T326 98v160H0Z" fill="${colors[2]}" opacity=".5"/><path d="M0 198Q79 140 170 168T325 139v120H0Z" fill="${colors[2]}" opacity=".8"/><path d="M-5 208q90-39 170-9t164-8" fill="none" stroke="${colors[0]}" stroke-opacity=".5" stroke-width="1.5"/>`}
  <g stroke="#fff" stroke-opacity=".08">${Array.from({length:18},(_,i)=>`<path d="M10 ${18+i*12}h300"/>`).join('')}</g></g><rect x="10.5" y="10.5" width="299" height="219" rx="14" fill="none" stroke="#fff" stroke-opacity=".4"/>
  ${record?`<g class="vinyl-disc"><circle cx="213" cy="135" r="91" fill="url(#${id}-vinyl)" stroke="#798087" stroke-width="1.5"/><g fill="none" stroke="#b7bec6" stroke-opacity=".17">${Array.from({length:12},(_,i)=>`<circle cx="213" cy="135" r="${39+i*4}"/>`).join('')}</g><path d="M154 80a80 80 0 0 1 113-5M159 194a80 80 0 0 0 111-4" fill="none" stroke="#d8e0e8" stroke-opacity=".2" stroke-width="7"/><circle cx="213" cy="135" r="32" fill="url(#${id}-sky)"/><circle cx="213" cy="135" r="26" fill="none" stroke="#ffffff55"/><path d="M200 123h26m-26 5h26m-21 21h16" stroke="#fff" stroke-opacity=".5"/><circle cx="213" cy="135" r="6" fill="#252b33" stroke="#a0a5a8"/><circle cx="212" cy="134" r="2" fill="#ecf0eb"/></g>`:''}</svg>`;
};
A.musicLibraryPreview=()=>`<button class="music-originals-entry" data-action="musicOriginals"><span class="music-originals-heading"><strong>オリジナル音源</strong><small>3曲 · ブラウザ生成</small>${icon('chevronRight')}</span><span class="music-originals-covers">${tracks.map(t=>`<span>${A.musicArtwork(t.id)}<strong>${t.title}</strong><small>${fmt(t.length)}</small></span>`).join('')}</span></button>`;
const art=(t,extra='')=>`<div class="album-art ${t.art} ${extra}">${A.musicArtwork(t.id,extra==='player-art')}<span>${t.album.replace('\n','<br>')}</span></div>`;
M.elapsed=()=>M.playing?Math.min(M.track.length,M.position+(Date.now()-M.startedAt)/1000):M.position;
M.setVolume=()=>{if(M.gain&&M.context)M.gain.gain.setTargetAtTime(A.settings.volume/100*.35,M.context.currentTime,.15);};
function audioInit(){if(!M.context){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('unsupported');M.context=new Audio();M.gain=M.context.createGain();M.gain.gain.value=A.settings.volume/100*.35;const compressor=M.context.createDynamicsCompressor();compressor.threshold.value=-16;compressor.ratio.value=4;M.gain.connect(compressor);compressor.connect(M.context.destination);}M.context.resume();}
function note(freq,time,duration,volume){const c=M.context,osc=c.createOscillator(),gain=c.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,time);gain.gain.exponentialRampToValueAtTime(volume,time+.08);gain.gain.exponentialRampToValueAtTime(.0001,time+duration);osc.connect(gain);gain.connect(M.gain);osc.start(time);osc.stop(time+duration+.05);osc.onended=()=>{osc.disconnect();gain.disconnect();};}
function synth(){if(!M.playing||!M.context)return;const t=M.context.currentTime,b=M.beat++,track=M.track;const semitone=track.notes[b%track.notes.length];note(track.base*Math.pow(2,semitone/12)*2,t,1.5,.14);if(b%4===0){[0,7,12].forEach((n,i)=>note(track.base*Math.pow(2,n/12),t+i*.025,3.2,.07));note(track.base/2,t,2,.12);}if(b%2===0)note(track.base*4,t+.23,.8,.035);}
M.start=()=>{try{audioInit();M.context.resume();M.startedAt=Date.now();M.playing=true;M.gain.gain.setTargetAtTime(A.settings.volume/100*.35,M.context.currentTime,.1);synth();clearInterval(M.scheduler);M.scheduler=setInterval(synth,60000/M.track.tempo/2);$('#phone-screen').classList.add('playing');refreshMusic();}catch{M.playing=false;A.toast('このブラウザでは音楽再生を利用できません');}};
M.pause=()=>{M.position=M.elapsed();M.playing=false;clearInterval(M.scheduler);if(M.gain)M.gain.gain.setTargetAtTime(0,M.context.currentTime,.1);$('#phone-screen').classList.remove('playing');refreshMusic();};
M.toggle=()=>M.playing?M.pause():M.start();
M.select=(id,play=true)=>{const next=tracks.find(t=>t.id===id);if(!next)return;if(M.playing)M.pause();M.track=next;M.position=0;M.beat=0;if(play)M.start();};
M.next=step=>{M.select(tracks[(tracks.indexOf(M.track)+step+tracks.length)%tracks.length].id,true);if(A.current==='music')music(musicPage);if(!$('#overlay').hidden&&$('#control-volume'))A.controls();};
M.tick=()=>{if(M.playing&&M.elapsed()>=M.track.length)M.next(1);const progress=$('#music-progress');if(progress&&document.activeElement!==progress)progress.value=M.elapsed();if($('#music-elapsed'))$('#music-elapsed').textContent=fmt(M.elapsed());if($('#music-remaining'))$('#music-remaining').textContent='−'+fmt(M.track.length-M.elapsed());};
let musicPage='home';
function music(arg){musicPage=arg==='player'?'player':'home';A.statusTheme(true);$('#app-screen').classList.add('music-app');if(musicPage==='player')return player();A.view(A.nav('ミュージック',`<button data-action="musicCatalogue">検索</button><button data-action="musicFavorites" aria-label="お気に入り">${icon('heart')}</button>`)+`<div class="app-content"><h1 class="app-title">音源</h1><div class="music-hero">${A.musicArtwork('dusk',true)}<div class="music-feature-title"><strong>Golden Hour</strong><span>aura sounds</span></div><button data-action="musicPlayTrack" data-id="dusk" aria-label="Golden Hourを再生">${icon('play')}</button></div><div class="album-grid">${tracks.slice(0,2).map(t=>`<button class="album-card" data-action="musicPlayTrack" data-id="${t.id}">${art(t)}<h3>${t.title}</h3><p>${t.artist}</p></button>`).join('')}</div>${tracks.map(t=>`<button class="track-row" data-action="musicPlayTrack" data-id="${t.id}">${art(t)}<div><strong>${t.title}</strong><small>${t.artist}</small></div><span>${fmt(t.length)}</span></button>`).join('')}<p class="setting-description" style="color:#777984;margin-top:20px">ブラウザ生成の環境音楽</p></div>${miniPlayer()}`);}
function miniPlayer(){return `<div class="music-mini"><div class="mini-art ${M.track.art}"></div><button data-action="musicPlayer">${M.track.title}<small>${M.track.artist}</small></button><button data-action="musicToggle" aria-label="再生・一時停止" id="mini-play">${icon(M.playing?'pause':'play')}</button><button data-action="musicNext" aria-label="次の曲">${icon('next')}</button></div><div style="height:24px;background:#252329;flex-shrink:0"></div>`;}
function player(){const t=M.track;A.view(A.nav('再生中',`<button data-action="musicInfo" aria-label="音源について">···</button>`,'musicHome','閉じる')+`<div class="player-content">${art(t,'player-art')}<div class="player-info"><div><h2>${t.title}</h2><p>${t.artist}</p></div><button data-action="musicLike" id="music-like" aria-label="お気に入り" aria-pressed="${M.liked.includes(t.id)}">${M.liked.includes(t.id)?'♥':'♡'}</button></div><input class="music-progress" type="range" min="0" max="${t.length}" step="1" value="${M.elapsed()}" id="music-progress" aria-label="再生位置"><div class="progress-labels"><span id="music-elapsed">${fmt(M.elapsed())}</span><span id="music-remaining">−${fmt(t.length-M.elapsed())}</span></div><div class="player-controls"><button data-action="musicPrevious" aria-label="前の曲">${icon('previous')}</button><button class="main-play" data-action="musicToggle" id="player-play" aria-label="再生・一時停止">${icon(M.playing?'pause':'play')}</button><button data-action="musicNext" aria-label="次の曲">${icon('next')}</button></div><label class="player-volume">${icon('volume')}<input type="range" id="music-volume" min="0" max="100" value="${A.settings.volume}" aria-label="音量">${icon('volume')}</label></div>`);$('#music-progress').oninput=e=>{M.position=+e.target.value;M.startedAt=Date.now();M.tick();};$('#music-volume').oninput=e=>{A.settings.volume=+e.target.value;M.setVolume();A.save('settings',A.settings);};}
function refreshMusic(){if($('#mini-play'))$('#mini-play').innerHTML=icon(M.playing?'pause':'play');if($('#player-play'))$('#player-play').innerHTML=icon(M.playing?'pause':'play');}
A.apps.music.render=music;A.actions.musicHome=()=>music('home');A.actions.musicPlayer=()=>music('player');A.actions.musicToggle=M.toggle;A.actions.musicNext=()=>M.next(1);A.actions.musicPrevious=()=>M.next(-1);A.actions.musicPlayTrack=el=>{M.select(el.dataset.id,true);music('player');};A.actions.musicLike=()=>{M.liked=M.liked.includes(M.track.id)?M.liked.filter(x=>x!==M.track.id):[...M.liked,M.track.id];A.save('musicLikes',M.liked);$('#music-like').textContent=M.liked.includes(M.track.id)?'♥':'♡';$('#music-like').setAttribute('aria-pressed',M.liked.includes(M.track.id));};A.actions.musicInfo=()=>A.toast('aura originals — このブラウザで生成したオリジナル音源です');
A.actions.musicFavorites=()=>{A.view(A.nav('お気に入り','','musicHome','戻る')+`<div class="app-content">${tracks.filter(t=>M.liked.includes(t.id)).map(t=>`<button class="track-row" data-action="musicPlayTrack" data-id="${t.id}">${art(t)}<div><strong>${t.title}</strong><small>${t.artist}</small></div>${icon('play','style="width:18px"')}</button>`).join('')||A.empty('お気に入りなし','heart')}</div>${miniPlayer()}`);};
// Voice recorder: real microphone, explicit permission, temporary session blobs.
let recording=null,recorderStream=null,recordStart=0,recordInterval=null,recordItems=[],recorderGeneration=0;
function recorder(){A.statusTheme(false);A.view(A.nav('ボイスメモ')+`<div class="app-content" id="recorder-content"><div class="recorder-wave">${Array.from({length:65},(_,i)=>`<i style="height:${4+Math.abs(Math.sin(i*.71)*Math.cos(i*.19))*52}px;animation-delay:-${i*.08}s"></i>`).join('')}</div><div class="recorder-time" id="record-time">00:00</div><button class="record-button" id="record-button" data-action="recordToggle" aria-label="録音開始・停止"></button><p class="setting-description" id="record-hint" style="text-align:center">マイク許可が必要。終了で録音削除・先に保存</p><div id="record-list"></div></div>`);renderRecordList();const token=++recorderGeneration;A.cleanups.push(()=>{if(recorderGeneration!==token)return;recorderGeneration++;if(recording?.state==='recording'){recording.onstop=null;recording.stop();}recorderStream?.getTracks().forEach(t=>t.stop());clearInterval(recordInterval);recording=null;recorderStream=null;recordItems.forEach(r=>URL.revokeObjectURL(r.url));recordItems=[];});}
function renderRecordList(){const el=$('#record-list');if(!el)return;el.innerHTML=recordItems.map(r=>`<article class="recording-row"><div style="flex:1;min-width:0"><strong style="font-size:11px;display:block;margin-bottom:10px">${esc(r.name)} · ${r.duration}</strong><audio controls playsinline src="${r.url}" aria-label="${esc(r.name)}"></audio></div><button data-action="recordShare" data-id="${r.id}" aria-label="録音を共有">${icon('share','style="width:19px"')}</button><button data-action="recordDownload" data-id="${r.id}" aria-label="録音を保存" style="color:#7488a4">${icon('download','style="width:19px"')}</button></article>`).join('')||'<p class="empty-state" style="padding:10px">録音なし</p>';}
A.apps.recorder.render=recorder;
A.actions.recordToggle=async()=>{if(recording?.state==='recording'){recording.stop();clearInterval(recordInterval);recorderStream?.getTracks().forEach(t=>t.stop());$('#recorder-content')?.classList.remove('recording');return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return A.toast('この環境では録音を利用できません');const token=recorderGeneration;let acquiredStream=null;$('#record-button').disabled=true;try{const stream=acquiredStream=await navigator.mediaDevices.getUserMedia({audio:true});if(token!==recorderGeneration||A.current!=='recorder'){stream.getTracks().forEach(t=>t.stop());return;}recorderStream=stream;recording=new MediaRecorder(stream);const chunks=[];recording.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recording.onstop=()=>{if(token!==recorderGeneration)return;const type=recording.mimeType||'audio/webm';const blob=new Blob(chunks,{type});const duration=fmt((Date.now()-recordStart)/1000);recordItems.unshift({id:A.id(),name:'新規録音 '+(recordItems.length+1),blob,url:URL.createObjectURL(blob),duration,type});renderRecordList();A.toast('録音済み。終了前に保存を。');};recording.start();recordStart=Date.now();$('#recorder-content').classList.add('recording');$('#record-time').textContent='00:00';recordInterval=setInterval(()=>{const el=$('#record-time');if(el)el.textContent=fmt((Date.now()-recordStart)/1000).padStart(5,'0');},300);}catch(e){acquiredStream?.getTracks().forEach(t=>t.stop());if(token===recorderGeneration){if(recording){recording.onstop=null;if(recording.state==='recording')recording.stop();}recording=null;recorderStream=null;clearInterval(recordInterval);$('#recorder-content')?.classList.remove('recording');A.toast(e.name==='NotAllowedError'?'マイクの許可を確認してください':'録音を開始できませんでした');}}finally{if(token===recorderGeneration&&$('#record-button'))$('#record-button').disabled=false;}};
A.actions.recordShare=el=>{const r=recordItems.find(r=>r.id===el.dataset.id);if(r)A.network.offerFile(r.blob,`aura-recording-${r.id}.${r.type.includes('mp4')?'m4a':r.type.includes('ogg')?'ogg':'webm'}`);};
A.actions.recordDownload=el=>{const r=recordItems.find(r=>r.id===el.dataset.id);if(r)A.download(r.blob,`aura-recording-${r.id}.${r.type.includes('mp4')?'m4a':r.type.includes('ogg')?'ogg':'webm'}`);};
// Live weather and maps are implemented in connected.js.
})();
