'use strict';
(() => {
 const A=window.Aura,$=A.$,esc=A.escape;
 const day=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 const list=key=>{const v=A.load(key,[]);return Array.isArray(v)?v:[];};
 const button=(action,label,icon,id='')=>`<button class="pd-icon" data-action="${action}" data-id="${esc(id)}" aria-label="${esc(label)}" title="${esc(label)}">${A.icon(icon)}</button>`;
 const field=(label,name,value='',type='text',attrs='')=>`<label class="form-label" for="pd-${name}">${label}</label><input class="text-input" id="pd-${name}" name="${name}" value="${esc(value)}" type="${type}" ${attrs}>`;
 const select=(label,name,options,value)=>`<label class="form-label" for="pd-${name}">${label}</label><select class="text-input" name="${name}" id="pd-${name}">${options.map(([id,text])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(text)}</option>`).join('')}</select>`;
 const tabs=(options,value,action)=>`<div class="pd-tabs">${options.map(([id,label])=>`<button data-action="${action}" data-id="${id}" class="${id===value?'selected':''}" aria-pressed="${id===value}">${label}</button>`).join('')}</div>`;
 const empty=text=>`<div class="pd-empty">${text}</div>`;
 const download=(filename,text,type='text/plain')=>A.download(new Blob([text],{type:type+';charset=utf-8'}),filename);
 const page=(title,content,right='',back='home')=>A.view(A.nav(title,right,back,back==='home'?'':'戻る')+`<div class="app-content productivity">${content}</div>`);

 // Notes: folders, templates, checklists, previews and recoverable deletion.
 let noteFolder='all',noteQuery='',noteCurrent=null,notePreview=false;
 const folderNames=()=>[...new Set([...list('noteFolders'),...A.noteModel.get().map(n=>n.folder).filter(Boolean)])];
 function notes(){noteCurrent=null;const counts=A.noteModel.get();page('メモ',`<div class="pd-folder-bar"><select id="pd-note-folder" aria-label="メモのフォルダ"><option value="all">すべて ${counts.length}</option><option value="pinned" ${noteFolder==='pinned'?'selected':''}>ピン留め</option><option value="" ${noteFolder===''?'selected':''}>未分類</option>${folderNames().map(name=>`<option value="${esc(name)}" ${name===noteFolder?'selected':''}>${esc(name)}</option>`).join('')}</select>${button('pdNoteFolders','フォルダを管理','files')}${button('pdNoteTrash','ごみ箱','trash')}</div>${A.search('notes-search','メモ・タグを検索')}<div class="notes-toolbar"><span id="notes-count" role="status"></span><select id="notes-sort" aria-label="メモの並べ替え"><option value="updated">更新順</option><option value="title">タイトル順</option></select></div><div class="notes-grid" id="notes-grid"></div>`,button('pdNoteTemplates','テンプレート','layers')+button('noteNew','新規メモ','edit'));$('#notes-sort').value=A.load('noteSort','updated');$('#notes-search').value=noteQuery;renderNotes();$('#notes-search').oninput=e=>{noteQuery=e.target.value;renderNotes();};$('#notes-sort').onchange=e=>{A.save('noteSort',e.target.value);renderNotes();};$('#pd-note-folder').onchange=e=>{noteFolder=e.target.value;renderNotes();};}
 function renderNotes(){const query=noteQuery.trim().toLowerCase(),sort=A.load('noteSort','updated'),rows=A.noteModel.get().filter(n=>(noteFolder==='all'||noteFolder==='pinned'&&n.pinned||noteFolder===(n.folder||''))&&(n.title+' '+n.body+' '+(n.tags||'')).toLowerCase().includes(query)).sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned)||(sort==='title'?a.title.localeCompare(b.title,'ja'):b.updated-a.updated));$('#notes-count').textContent=rows.length+'件';$('#notes-grid').innerHTML=rows.map(n=>{const checks=n.body.split('\n').filter(x=>/^\s*[☐☑]/.test(x)),done=checks.filter(x=>/^\s*☑/.test(x)).length;return `<button class="note-card ${n.pinned?'is-pinned':''}" data-action="noteOpen" data-id="${esc(n.id)}">${n.pinned?`<span class="note-pin-label">${A.icon('pin')}ピン留め</span>`:''}<h3>${esc(n.title||'新しいメモ')}</h3><p>${esc(n.body)}</p><small>${new Date(n.updated).toLocaleDateString('ja-JP',{month:'short',day:'numeric'})}${checks.length?' · '+done+'/'+checks.length:''}${n.folder?' · '+esc(n.folder):''}</small>${n.tags?`<div class="pd-tags">${esc(n.tags)}</div>`:''}</button>`;}).join('')||empty('メモはありません');}
 function noteEditor(id){const n=A.noteModel.get().find(x=>x.id===id);if(!n)return;noteCurrent=id;page('メモ',`<div class="pd-editor-top"><span id="note-save-status" role="status">保存済み</span><span id="note-length">${Array.from(n.body).length}字</span></div><div class="note-editor-tools"><button class="note-pin-button" data-action="notePin" aria-pressed="${!!n.pinned}">${A.icon('pin')}<span>${n.pinned?'ピン留め済み':'ピン留め'}</span></button><button class="pd-text-button" data-action="pdNoteOrganize">${esc(n.folder||'未分類')} ›</button></div><input class="note-title-input" id="note-title" aria-label="メモのタイトル" placeholder="タイトル" maxlength="120" value="${esc(n.title)}"><div class="pd-format-bar"><button data-action="pdNoteInsert" data-id="☐ " aria-label="チェック項目">☐</button><button data-action="pdNoteInsert" data-id="• " aria-label="箇条書き">•</button><button data-action="pdNoteInsert" data-id="# " aria-label="見出し">H</button><button data-action="pdNoteInsert" data-id="date" aria-label="日付を挿入">${A.icon('calendar')}</button><button data-action="pdNotePreview" class="${notePreview?'selected':''}">${notePreview?'編集':'表示'}</button></div><textarea class="note-body-input pd-note-body" id="note-body" aria-label="メモ本文" maxlength="50000" placeholder="書き始める" ${notePreview?'hidden':''}>${esc(n.body)}</textarea><div id="pd-note-preview" class="pd-markdown" ${notePreview?'':'hidden'}></div>`,button('pdNoteMenu','メモの操作','layers'),'noteList');const save=()=>{const next={...n,title:$('#note-title').value,body:$('#note-body').value,updated:Date.now()},ok=A.noteModel.replace(A.noteModel.get().map(x=>x.id===id?next:x));if(ok)Object.assign(n,next);$('#note-save-status').textContent=ok?'保存済み':'保存できません';$('#note-length').textContent=Array.from(next.body).length+'字';};$('#note-title').oninput=save;$('#note-body').oninput=save;if(notePreview)renderNotePreview(n);}
 function renderNotePreview(n){$('#pd-note-preview').innerHTML=n.body.split('\n').map((line,i)=>/^\s*[☐☑]/.test(line)?`<button class="pd-checkline ${/^\s*☑/.test(line)?'done':''}" data-action="pdNoteCheck" data-id="${i}" aria-pressed="${/^\s*☑/.test(line)}"><span>${/^\s*☑/.test(line)?'✓':''}</span>${esc(line.replace(/^\s*[☐☑]\s*/,''))}</button>`:/^#{1,3}\s/.test(line)?`<h3>${esc(line.replace(/^#{1,3}\s/,''))}</h3>`:/^[-•]\s/.test(line)?`<div class="pd-bullet">${esc(line.replace(/^[-•]\s/,''))}</div>`:`<p>${esc(line)||'<br>'}</p>`).join('');}
 function newNote(template={title:'',body:''}){const n={id:A.id(),...template,folder:['all','pinned'].includes(noteFolder)?'':noteFolder,updated:Date.now(),pinned:false,tags:''};if(!A.noteModel.replace([n,...A.noteModel.get()]))return;A.closeOverlay();notePreview=false;noteEditor(n.id);$('#note-title').focus();}
 A.apps.notes.render=notes;A.actions.noteList=notes;A.actions.noteOpen=el=>{notePreview=false;noteEditor(el.dataset.id);};A.actions.noteNew=()=>newNote();
 A.actions.notePin=()=>{const n=A.noteModel.get().find(x=>x.id===noteCurrent);if(n&&A.noteModel.replace(A.noteModel.get().map(x=>x.id===n.id?{...x,pinned:!x.pinned}:x)))noteEditor(n.id);};
 A.actions.pdNoteInsert=el=>{if(notePreview){notePreview=false;noteEditor(noteCurrent);}const input=$('#note-body'),text=el.dataset.id==='date'?day():el.dataset.id;input.setRangeText((input.selectionStart&&input.value[input.selectionStart-1]!=='\n'?'\n':'')+text,input.selectionStart,input.selectionEnd,'end');input.dispatchEvent(new Event('input'));input.focus();};
 A.actions.pdNotePreview=()=>{notePreview=!notePreview;noteEditor(noteCurrent);};
 A.actions.pdNoteCheck=el=>{const n=A.noteModel.get().find(x=>x.id===noteCurrent);if(!n)return;const lines=n.body.split('\n'),i=Number(el.dataset.id);lines[i]=lines[i].replace(/[☐☑]/,c=>c==='☐'?'☑':'☐');if(A.noteModel.replace(A.noteModel.get().map(x=>x.id===n.id?{...x,body:lines.join('\n'),updated:Date.now()}:x)))noteEditor(n.id);};
 A.actions.pdNoteOrganize=()=>{const n=A.noteModel.get().find(x=>x.id===noteCurrent);if(!n)return;A.form('整理',select('フォルダ','folder',[['','未分類'],...folderNames().map(x=>[x,x])],n.folder||'')+field('タグ','tags',n.tags||'','text','maxlength="120"'),v=>{if(!A.noteModel.replace(A.noteModel.get().map(x=>x.id===n.id?{...x,...v,updated:Date.now()}:x)))return false;noteEditor(n.id);});};
 A.actions.pdNoteFolders=()=>A.overlay(`${A.overlayTitle('フォルダ')}<div class="pd-menu">${folderNames().map(name=>`<div class="pd-folder-row"><span>${esc(name)}</span>${button('pdNoteFolderDelete','フォルダを削除','trash',name)}</div>`).join('')}<button data-action="pdNoteFolderNew">＋ フォルダを作成</button></div>`);
 A.actions.pdNoteFolderNew=()=>A.form('フォルダを作成',field('名前','name','','text','required maxlength="40"'),v=>{const name=v.name.trim();if(!name||['all','pinned'].includes(name)){A.toast('別の名前を入力してください');return false;}if(!A.save('noteFolders',[...new Set([...folderNames(),name])]))return false;noteFolder=name;notes();});
 A.actions.pdNoteFolderDelete=el=>A.confirm('フォルダを削除？','メモは未分類に移動します。',()=>{const name=el.dataset.id;if(!A.noteModel.replace(A.noteModel.get().map(n=>n.folder===name?{...n,folder:''}:n)))return;A.save('noteFolders',folderNames().filter(x=>x!==name));noteFolder='all';notes();});
 const templates={checklist:{title:'チェックリスト',body:'☐ \n☐ \n☐ '},meeting:{title:'打ち合わせ',body:'# '+day()+'\n\n# 議題\n• \n\n# 決まったこと\n• \n\n# 次のアクション\n☐ '},trip:{title:'旅の計画',body:'# 行き先\n\n# 予定\n\n# 持ちもの\n☐ \n☐ '},idea:{title:'アイデア',body:'# やりたいこと\n\n# きっかけ\n\n# 次の一歩\n☐ '}};
 A.actions.pdNoteTemplates=()=>A.overlay(`${A.overlayTitle('テンプレート')}<div class="pd-template-grid">${Object.entries(templates).map(([id,t])=>`<button data-action="pdNoteTemplate" data-id="${id}">${A.icon(id==='checklist'?'check':id==='trip'?'maps':id==='meeting'?'calendar':'notes')}<strong>${t.title}</strong></button>`).join('')}</div>`);A.actions.pdNoteTemplate=el=>newNote(templates[el.dataset.id]);
 A.actions.pdNoteMenu=()=>A.overlay(`${A.overlayTitle('メモ')}<div class="pd-menu"><button data-action="pdNoteOrganize">${A.icon('files')}フォルダ・タグ</button><button data-action="pdNoteDuplicate">${A.icon('layers')}複製</button><button data-action="pdNoteExport">${A.icon('download')}テキストを保存</button><button data-action="noteDelete" class="pd-danger">${A.icon('trash')}ごみ箱へ</button></div>`);
 A.actions.pdNoteDuplicate=()=>{const n=A.noteModel.get().find(x=>x.id===noteCurrent);if(!n)return;const copy={...n,id:A.id(),title:(n.title+' コピー').slice(0,120),updated:Date.now()};if(A.noteModel.replace([copy,...A.noteModel.get()])){A.closeOverlay();noteEditor(copy.id);}};
 A.actions.pdNoteExport=()=>{const n=A.noteModel.get().find(x=>x.id===noteCurrent);if(n)download((n.title||'メモ').replace(/[\\/:*?"<>|]/g,'_')+'.txt',n.title+'\n\n'+n.body);};
 A.actions.noteDelete=()=>{const n=A.noteModel.get().find(x=>x.id===noteCurrent);if(!n)return;const trash=list('noteTrash');if(!A.save('noteTrash',[{...n,deletedAt:Date.now()},...trash.filter(x=>x.id!==n.id)]))return;if(!A.noteModel.replace(A.noteModel.get().filter(x=>x.id!==n.id))){A.save('noteTrash',trash);return;}A.closeOverlay();notes();A.toast('ごみ箱に移動しました');};
 A.actions.pdNoteTrash=()=>page('ごみ箱',`${list('noteTrash').map(n=>`<div class="pd-trash-row"><div><strong>${esc(n.title||'メモ')}</strong><small>${new Date(n.deletedAt).toLocaleDateString('ja-JP')}</small></div>${button('pdNoteRestore','復元','refresh',n.id)}${button('pdNotePurge','完全に削除','trash',n.id)}</div>`).join('')||empty('ごみ箱は空です')}`,'','noteList');
 A.actions.pdNoteRestore=el=>{const n=list('noteTrash').find(x=>x.id===el.dataset.id);if(!n)return;const {deletedAt,...rest}=n;if(!A.noteModel.get().some(x=>x.id===n.id)&&!A.noteModel.replace([{...rest,updated:Date.now()},...A.noteModel.get()]))return;if(A.save('noteTrash',list('noteTrash').filter(x=>x.id!==n.id)))A.actions.pdNoteTrash();};
 A.actions.pdNotePurge=el=>A.confirm('完全に削除？','この操作は元に戻せません。',()=>{if(A.save('noteTrash',list('noteTrash').filter(x=>x.id!==el.dataset.id)))A.actions.pdNoteTrash();});

 // Calendar: month/week/agenda views, colors, durations and bounded recurrence.
 const eventColors={rose:'#c98895',sage:'#80a18a',blue:'#83a5c4',gold:'#c6a36c',violet:'#a591bb'};
 let calendarView=A.load('calendarView','month'),calendarDay=day(),calendarMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),eventQuery='';
 const sortedEvents=()=>[...A.eventModel.get()].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
 function agendaRows(rows){return rows.map(e=>`<button class="pd-agenda-row" data-action="calendarEdit" data-id="${esc(e.id)}" style="--event-color:${eventColors[e.color]||eventColors.rose}"><time>${esc(e.time)}${e.endTime?`<small>${esc(e.endTime)}</small>`:''}</time><span><strong>${esc(e.title)}</strong><small>${esc(e.place||'')}${e.series?' · ↻':''}</small></span><i>›</i></button>`).join('')||empty('予定はありません');}
 function calendar(){const y=calendarMonth.getFullYear(),m=calendarMonth.getMonth(),events=A.eventModel.get();let content='';if(calendarView==='month'){const first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate();content=`<div class="month-grid pd-month-grid">${['日','月','火','水','木','金','土'].map(x=>`<span class="weekday">${x}</span>`).join('')}${'<span></span>'.repeat(first)}${Array.from({length:count},(_,i)=>{const date=day(new Date(y,m,i+1)),items=events.filter(e=>e.date===date);return `<button class="month-day ${date===day()?'today':''} ${date===calendarDay?'selected':''}" data-action="calendarSelect" data-date="${date}"><strong>${i+1}</strong><span class="pd-event-dots">${items.slice(0,3).map(e=>`<i style="background:${eventColors[e.color]||eventColors.rose}"></i>`).join('')}</span></button>`;}).join('')}</div><header class="pd-section"><h3>${new Date(calendarDay+'T12:00:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'short'})}</h3></header><div class="pd-agenda calendar-agenda">${agendaRows(sortedEvents().filter(e=>e.date===calendarDay))}</div>`;}else if(calendarView==='week'){const start=new Date(calendarDay+'T12:00:00');start.setDate(start.getDate()-start.getDay());content=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const key=day(d);return `<section class="pd-week-day ${key===day()?'today':''}"><header><strong>${d.getDate()}</strong><small>${d.toLocaleDateString('ja-JP',{weekday:'short'})}</small><button data-action="pdCalendarDayAdd" data-id="${key}" aria-label="${key}に追加">+</button></header><div class="pd-agenda">${agendaRows(sortedEvents().filter(e=>e.date===key))}</div></section>`;}).join('');}else{content=`${A.search('pd-event-search','予定・場所を検索')}<div id="pd-event-results"></div>`;}
 page('カレンダー',`${tabs([['month','月'],['week','週'],['agenda','予定']],calendarView,'pdCalendarView')}<div class="calendar-month-head"><h3>${y}年 ${m+1}月</h3><div><button data-action="calendarMove" data-value="-1" aria-label="前へ">‹</button><button data-action="calendarToday" class="pd-calendar-today">今日</button><button data-action="calendarMove" data-value="1" aria-label="次へ">›</button></div></div>${content}`,button('calendarAdd','予定を追加','plus'));if(calendarView==='agenda'){const render=()=>{const rows=sortedEvents().filter(e=>(e.title+' '+e.place+' '+e.date).toLowerCase().includes(eventQuery.toLowerCase())&&(eventQuery||e.date>=calendarDay));let previous='';$('#pd-event-results').innerHTML=rows.map(e=>{const heading=e.date!==previous?`<header class="pd-section"><h3>${esc(e.date)}</h3></header>`:'';previous=e.date;return heading+agendaRows([e]);}).join('')||empty('予定はありません');};$('#pd-event-search').value=eventQuery;$('#pd-event-search').oninput=e=>{eventQuery=e.target.value;render();};render();}}
 A.apps.calendar.render=calendar;A.actions.pdCalendarView=el=>{calendarView=el.dataset.id;A.save('calendarView',calendarView);calendar();};
 A.actions.calendarToday=()=>{calendarDay=day();calendarMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1);calendar();};
 A.actions.calendarMove=el=>{if(calendarView==='week'){const d=new Date(calendarDay+'T12:00:00');d.setDate(d.getDate()+Number(el.dataset.value)*7);calendarDay=day(d);calendarMonth=new Date(d.getFullYear(),d.getMonth(),1);}else{calendarMonth.setMonth(calendarMonth.getMonth()+Number(el.dataset.value));calendarDay=day(calendarMonth);}calendar();};
 A.actions.calendarSelect=el=>{calendarDay=el.dataset.date;calendarMonth=new Date(calendarDay+'T12:00:00');calendarMonth.setDate(1);calendar();};A.actions.pdCalendarDayAdd=el=>{calendarDay=el.dataset.id;eventEditor();};
 function eventEditor(event){const defaultEnd=event?.endTime||'';A.form(event?'予定を編集':'予定を追加',field('タイトル','title',event?.title||'','text','required maxlength="80"')+field('日付','date',event?.date||calendarDay,'date','required')+`<div class="pd-form-two">${field('開始','time',event?.time||'15:00','time','required')}${field('終了','endTime',defaultEnd,'time')}</div>`+field('場所','place',event?.place||'','text','maxlength="120"')+select('色','color',[['rose','ローズ'],['sage','セージ'],['blue','ブルー'],['gold','ゴールド'],['violet','ラベンダー']],event?.color||'rose')+(event?'':select('繰り返し','repeat',[['none','なし'],['daily','毎日'],['weekly','毎週'],['monthly','毎月']],'none')+field('作成する回数','count',4,'number','required min="1" max="52" step="1"'))+(event?`<div class="pd-form-actions"><button type="button" data-action="pdCalendarDuplicate" data-id="${event.id}">複製</button><button type="button" class="pd-danger" data-action="calendarDelete" data-id="${event.id}">削除</button>${event.series?`<button type="button" class="pd-danger" data-action="pdCalendarDeleteSeries" data-id="${event.series}">繰り返しを削除</button>`:''}</div>`:''),v=>{if(!v.title.trim())return false;const base={...event,id:event?.id||A.id(),title:v.title.trim(),date:v.date,time:v.time,endTime:v.endTime,place:v.place,color:v.color};let rows=A.eventModel.get();if(event)rows=rows.map(e=>e.id===event.id?base:e);else{const count=v.repeat==='none'?1:Math.max(1,Math.min(52,Number(v.count))),series=count>1?A.id():null,start=new Date(v.date+'T12:00:00'),added=[];for(let i=0;i<count;i++){const d=new Date(start);if(v.repeat==='monthly'){d.setDate(1);d.setMonth(start.getMonth()+i);d.setDate(Math.min(start.getDate(),new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));}else d.setDate(start.getDate()+i*(v.repeat==='weekly'?7:1));added.push({...base,id:i?A.id():base.id,date:day(d),series});}rows=[...rows,...added];}if(!A.eventModel.replace(rows))return false;calendarDay=v.date;calendarMonth=new Date(v.date+'T12:00:00');calendarMonth.setDate(1);calendar();});}
 A.actions.calendarAdd=()=>eventEditor();A.actions.calendarEdit=el=>{const e=A.eventModel.get().find(x=>x.id===el.dataset.id);if(e)eventEditor(e);};A.actions.calendarDelete=el=>A.confirm('予定を削除？','この予定だけを削除します。',()=>{if(A.eventModel.replace(A.eventModel.get().filter(e=>e.id!==el.dataset.id)))calendar();});A.actions.pdCalendarDeleteSeries=el=>A.confirm('繰り返しを削除？','同じ繰り返しの予定をまとめて削除します。',()=>{if(A.eventModel.replace(A.eventModel.get().filter(e=>e.series!==el.dataset.id)))calendar();});A.actions.pdCalendarDuplicate=el=>{const e=A.eventModel.get().find(x=>x.id===el.dataset.id);if(!e)return;A.closeOverlay();calendarDay=e.date;eventEditor();const f=$('#modal-form');for(const key of ['title','date','time','endTime','place','color'])f.elements[key].value=e[key]||'';};

 // Files: local folders, safe previews, version history and bulk text import.
 let fileCurrent=null,fileFolder='all',fileQuery='',fileKind='all',fileSort='date';
 const fileFolders=()=>[...new Set([...list('fileFolders'),...A.fileModel.get().map(x=>x.folder).filter(Boolean)])];
 function files(){page('ファイル',`<div class="pd-folder-bar"><select id="pd-file-folder" aria-label="フォルダ"><option value="all">すべてのファイル</option><option value="" ${fileFolder===''?'selected':''}>未分類</option>${fileFolders().map(x=>`<option value="${esc(x)}" ${fileFolder===x?'selected':''}>${esc(x)}</option>`).join('')}</select>${button('pdFileFolders','フォルダを管理','files')}</div>${A.search('file-search','名前・内容を検索')}${tabs([['all','すべて'],['txt','TXT'],['md','MD'],['json','JSON'],['csv','CSV']],fileKind,'pdFileKind')}<div class="pd-file-toolbar"><span>${A.fileModel.get().length}件 · ${(new Blob([JSON.stringify(A.fileModel.get())]).size/1024).toFixed(1)}KB</span><select id="pd-file-sort" aria-label="並べ替え"><option value="date">更新順</option><option value="name">名前順</option><option value="size">サイズ順</option></select></div><div class="files-grid" id="files-grid"></div><button class="secondary-button pd-wide" data-action="fileImport">テキストを読み込む</button><p class="pd-caption">TXT・MD・JSON・CSV · 1件100KBまで</p>`,button('fileNew','ファイルを作成','plus'));const render=()=>{$('#files-grid').innerHTML=A.fileModel.get().filter(x=>(fileFolder==='all'||(x.folder||'')===fileFolder)&&(fileKind==='all'||x.name.toLowerCase().endsWith('.'+fileKind))&&(x.name+' '+x.content).toLowerCase().includes(fileQuery.toLowerCase())).sort((a,b)=>fileSort==='name'?a.name.localeCompare(b.name,'ja'):fileSort==='size'?new Blob([b.content]).size-new Blob([a.content]).size:b.date-a.date).map(f=>`<button class="file-tile pd-file-tile" data-action="fileOpen" data-id="${esc(f.id)}"><span class="pd-file-extension">${esc(f.name.split('.').at(-1).slice(0,5).toUpperCase())}</span>${A.icon('document')}<h3>${esc(f.name)}</h3><small>${(new Blob([f.content]).size/1024).toFixed(1)}KB${f.folder?' · '+esc(f.folder):''}</small></button>`).join('')||empty('ファイルはありません');};render();$('#file-search').value=fileQuery;$('#file-search').oninput=e=>{fileQuery=e.target.value;render();};$('#pd-file-folder').onchange=e=>{fileFolder=e.target.value;render();};$('#pd-file-sort').value=fileSort;$('#pd-file-sort').onchange=e=>{fileSort=e.target.value;render();};}
 function openFile(id){const f=A.fileModel.get().find(x=>x.id===id);if(!f)return;fileCurrent=id;page('ファイル',`<div class="pd-file-heading"><span>${esc(f.name.split('.').at(-1).toUpperCase())}</span><h1>${esc(f.name)}</h1><small>${new Date(f.date).toLocaleString('ja-JP')} · ${new Blob([f.content]).size.toLocaleString()} bytes</small></div><pre class="file-preview">${esc(f.content)}</pre><div class="pd-file-actions"><button data-action="fileEdit">${A.icon('edit')}編集</button><button data-action="fileDownload">${A.icon('download')}保存</button><button data-action="pdFileDuplicate">${A.icon('layers')}複製</button></div>${f.name.toLowerCase().endsWith('.json')?'<button class="pd-text-button pd-wide" data-action="pdFileFormat">JSONを整形</button>':''}<button class="pd-text-button pd-wide" data-action="pdFileVersions">変更履歴</button>`,button('fileDelete','ファイルを削除','trash'),'filesHome');}
 // Keep the bounded history unchanged if the corresponding file write fails.
 function replaceFileWithHistory(rows,previous){
  if(!previous)return A.fileModel.replace(rows);
  const history=list('fileVersions');
  if(!A.save('fileVersions',[{id:A.id(),fileId:previous.id,name:previous.name,content:previous.content,date:previous.date},...history].slice(0,30)))return false;
  if(A.fileModel.replace(rows))return true;
  A.save('fileVersions',history);
  return false;
 }
 function fileEditor(id){const f=A.fileModel.get().find(x=>x.id===id);A.form(f?'ファイルを編集':'ファイルを作成',field('ファイル名','name',f?.name||'新しいファイル.txt','text','required maxlength="80"')+select('フォルダ','folder',[['','未分類'],...fileFolders().map(x=>[x,x])],f?.folder||(fileFolder==='all'?'':fileFolder))+`<label class="form-label" for="pd-file-content">内容</label><textarea class="text-input pd-file-editor" id="pd-file-content" name="content" rows="12" maxlength="100000">${esc(f?.content||'')}</textarea>`,v=>{if(!v.name.trim()||!/\.(txt|md|json|csv)$/i.test(v.name)){A.toast('TXT・MD・JSON・CSVの名前にしてください');return false;}if(new Blob([v.content]).size>100*1024){A.toast('100KB以下にしてください');return false;}const next={...f,...v,name:v.name.trim(),id:f?.id||A.id(),date:Date.now()},rows=f?A.fileModel.get().map(x=>x.id===f.id?next:x):[next,...A.fileModel.get()];if(!replaceFileWithHistory(rows,f&&(f.content!==next.content||f.name!==next.name)?f:null))return false;openFile(next.id);});}
 A.apps.files.render=files;A.actions.filesHome=files;A.actions.fileOpen=el=>openFile(el.dataset.id);A.actions.fileNew=()=>fileEditor();A.actions.fileEdit=()=>fileEditor(fileCurrent);A.currentTextFile=()=>$('.file-preview')?A.fileModel.get().find(x=>x.id===fileCurrent):null;
 A.actions.fileDownload=()=>{const f=A.fileModel.get().find(x=>x.id===fileCurrent);if(f)download(f.name,f.content);};A.actions.fileDelete=()=>A.confirm('ファイルを削除？','このファイルと変更履歴を削除します。',()=>{if(!A.fileModel.replace(A.fileModel.get().filter(x=>x.id!==fileCurrent)))return;A.save('fileVersions',list('fileVersions').filter(x=>x.fileId!==fileCurrent));files();});
 A.actions.pdFileKind=el=>{fileKind=el.dataset.id;files();};A.actions.pdFileDuplicate=()=>{const f=A.fileModel.get().find(x=>x.id===fileCurrent);if(f){const copy={...f,id:A.id(),name:f.name.replace(/(\.[^.]+)$/,' コピー$1'),date:Date.now()};if(A.fileModel.replace([copy,...A.fileModel.get()]))openFile(copy.id);}};
 A.actions.pdFileFormat=()=>{const f=A.fileModel.get().find(x=>x.id===fileCurrent);if(!f)return;try{const content=JSON.stringify(JSON.parse(f.content),null,2);fileEditor(f.id);$('#pd-file-content').value=content;}catch{A.toast('JSONの形式を確認してください');}};
 A.actions.pdFileFolders=()=>A.overlay(`${A.overlayTitle('フォルダ')}<div class="pd-menu">${fileFolders().map(x=>`<div class="pd-folder-row"><span>${esc(x)}</span>${button('pdFileFolderDelete','フォルダを削除','trash',x)}</div>`).join('')}<button data-action="pdFileFolderNew">＋ フォルダを作成</button></div>`);A.actions.pdFileFolderNew=()=>A.form('フォルダを作成',field('名前','name','','text','required maxlength="40"'),v=>{const name=v.name.trim();if(!name||name==='all')return false;if(!A.save('fileFolders',[...new Set([...fileFolders(),name])]))return false;fileFolder=name;files();});A.actions.pdFileFolderDelete=el=>A.confirm('フォルダを削除？','ファイルは未分類に移動します。',()=>{const name=el.dataset.id;if(!A.fileModel.replace(A.fileModel.get().map(x=>x.folder===name?{...x,folder:''}:x)))return;A.save('fileFolders',fileFolders().filter(x=>x!==name));fileFolder='all';files();});
 A.actions.pdFileVersions=()=>A.overlay(`${A.overlayTitle('変更履歴')}<div class="pd-menu">${list('fileVersions').filter(x=>x.fileId===fileCurrent).map(v=>`<button data-action="pdFileRestore" data-id="${v.id}"><span>${new Date(v.date).toLocaleString('ja-JP')}<small>${esc(v.name)}</small></span>${A.icon('refresh')}</button>`).join('')||'<p>履歴はありません</p>'}</div>`);
 A.actions.pdFileRestore=el=>{const v=list('fileVersions').find(x=>x.id===el.dataset.id),f=A.fileModel.get().find(x=>x.id===fileCurrent);if(!v||!f||v.fileId!==f.id)return;A.confirm('この内容に戻す？','名前と内容を復元します。現在の状態も履歴に残します。',()=>{if(replaceFileWithHistory(A.fileModel.get().map(x=>x.id===f.id?{...x,name:v.name,content:v.content,date:Date.now()}:x),f))openFile(f.id);});};
 A.actions.fileImport=()=>{const input=document.createElement('input');input.type='file';input.multiple=true;input.accept='.txt,.md,.json,.csv';const folder=fileFolder==='all'?'':fileFolder;input.onchange=async()=>{const selected=[...input.files].slice(0,20),added=[];let rejected=0;for(const f of selected){if(f.size>100*1024||!/\.(txt|md|json|csv)$/i.test(f.name)){rejected++;continue;}try{added.push({id:A.id(),name:f.name,content:await f.text(),folder,date:Date.now()});}catch{rejected++;}}if(added.length&&!A.fileModel.replace([...added,...A.fileModel.get()]))return;if(A.current==='files')files();A.toast(`${added.length}件を読み込みました${rejected?' · '+rejected+'件は対象外':''}`);};input.click();};

 // An explicit local export complements per-app downloads without external uploads.
 const settings=A.apps.settings.render;
 const enhancedSettings=()=>{settings();$('.profile-card')?.insertAdjacentHTML('afterend',`<div class="group-card">${A.row('download','データを書き出す','','pdDataExport','','#809cae')}${A.row('files','保存容量','','pdStorage','','#a38eae')}</div>`);};
 A.apps.settings.render=enhancedSettings;A.actions.settingsHome=enhancedSettings;
 A.actions.pdDataExport=()=>{const data={};for(const key of Object.keys(localStorage).filter(k=>k.startsWith('aura.')))try{data[key.slice(5)]=JSON.parse(localStorage.getItem(key));}catch{data[key.slice(5)]=localStorage.getItem(key);}download('aura-data-'+day()+'.json',JSON.stringify({app:'aura',version:'4.4.0',exportedAt:new Date().toISOString(),data},null,2),'application/json');};
 A.actions.pdStorage=()=>{const groups={};for(const key of Object.keys(localStorage).filter(k=>k.startsWith('aura.'))){const name=key.slice(5),label=/photo/i.test(name)?'写真':/note/i.test(name)?'メモ':/file/i.test(name)?'ファイル':/sketch/i.test(name)?'スケッチ':/journal/i.test(name)?'日記':/expense/i.test(name)?'家計簿':/reading/i.test(name)?'読書':/focus/i.test(name)?'集中':/event|calendar/i.test(name)?'カレンダー':/shopping/i.test(name)?'買い物':/weather/i.test(name)?'天気':/map/i.test(name)?'地図':/habit/i.test(name)?'習慣':/contact/i.test(name)?'連絡先':/reminder/i.test(name)?'リマインダー':/conversion/i.test(name)?'単位換算':/dailyIntention/i.test(name)?'今日':/2048|snake|memory|blocks|mines|reversi|breaker|sudoku|arcade/i.test(name)?'ゲーム':'その他';groups[label]=(groups[label]||0)+new Blob([localStorage.getItem(key)]).size;}const sizes=Object.entries(groups).map(([label,bytes])=>({label,bytes})).sort((a,b)=>b.bytes-a.bytes),sum=sizes.reduce((n,x)=>n+x.bytes,0);page('保存容量',`<div class="pd-storage-total"><strong>${(sum/1024).toFixed(1)}<small>KB</small></strong><span>このブラウザのauraデータ</span></div><div class="pd-storage-list">${sizes.map(x=>`<div><span>${esc(x.label)}</span><strong>${(x.bytes/1024).toFixed(1)}KB</strong><i style="width:${Math.max(1,x.bytes/(sum||1)*100)}%"></i></div>`).join('')}</div><button class="secondary-button pd-wide" data-action="pdDataExport">データを書き出す</button>`,'','settingsHome');};
 const settingToggle=A.actions.settingToggle;A.actions.settingToggle=el=>{settingToggle(el);if(!$('#settings-brightness'))enhancedSettings();};
 const priorSearch=A.searchAdditional;
 A.searchAdditional=q=>(priorSearch?.(q)||'')+[['files','ファイル',A.fileModel.get().filter(x=>(x.name+' '+x.content).toLowerCase().includes(q)).slice(0,4),'pdSearchFile'],['calendar','予定',A.eventModel.get().filter(x=>(x.title+' '+x.place).toLowerCase().includes(q)).slice(0,4),'pdSearchEvent']].map(([app,title,rows,action])=>rows.length?`<p class="spotlight-label">${title}</p><div class="search-content-group">${rows.map(x=>`<button data-action="${action}" data-id="${esc(x.id)}">${A.icon(app)}<span><strong>${esc(x.name||x.title)}</strong><small>${esc(x.date?String(x.date):'')}</small></span>${A.icon('arrow')}</button>`).join('')}</div>`:'').join('');
 A.actions.pdSearchFile=el=>{A.open('files');openFile(el.dataset.id);};A.actions.pdSearchEvent=el=>{A.open('calendar');A.actions.calendarEdit(el);};
})();
