'use strict';
(() => {
const A=window.Aura,$=A.$,esc=A.escape,icon=A.icon;
const timeString=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.floor(Math.max(0,s)%60)).padStart(2,'0')}`;
// Calculator uses an arithmetic state machine, never eval.
let calc={entry:'0',previous:null,operator:null,fresh:false,expression:'',lastOp:null,lastOperand:null},calcHistory=A.load('calcHistory',[]);
const opLabel={'+':'+','-':'−','*':'×','/':'÷'};
function calcApp(){A.statusTheme(true);$('#app-screen').classList.add('calc-app');A.view(A.nav('計算機',`<button data-action="calcHistory" style="color:#d3ba95" aria-label="計算履歴">${icon('clock')}</button>`)+`<div class="calc-display"><div class="calc-expression" id="calc-expression">${esc(calc.expression)}</div><div class="calc-result" id="calc-result">${esc(calc.entry)}</div></div><div class="calc-keypad">${[['AC','clear','utility'],['+/−','sign','utility'],['%','percent','utility'],['÷','/','operator'],['7','7',''],['8','8',''],['9','9',''],['×','*','operator'],['4','4',''],['5','5',''],['6','6',''],['−','-','operator'],['1','1',''],['2','2',''],['3','3',''],['+','+','operator'],['0','0','zero'],['.','.',''],['=','=','operator']].map(([label,v,c])=>`<button class="calc-key ${c}" data-action="calcKey" data-value="${v}">${label}</button>`).join('')}</div>`);const keydown=e=>{if(A.current!=='calculator'||!$('#overlay').hidden||!$('#calc-result')||e.target.closest('input,textarea,select,[contenteditable="true"]'))return;let v=e.key;if(v==='Enter')v='=';if(v==='Backspace'){e.preventDefault();calc.entry=calc.entry.length>1?calc.entry.slice(0,-1):'0';updateCalc();return;}if(v==='Delete')v='clear';if('0123456789.+-*/='.includes(v)||v==='clear'){e.preventDefault();pressCalc(v);}};document.addEventListener('keydown',keydown);A.cleanups.push(()=>document.removeEventListener('keydown',keydown));}
function compute(a,b,op){if(op==='/'&&b===0)return null;return op==='+'?a+b:op==='-'?a-b:op==='*'?a*b:a/b;}
function formatNumber(n){return n===null||!Number.isFinite(n)?'エラー':String(+n.toPrecision(12));}
function updateCalc(){if($('#calc-result')){$('#calc-result').textContent=calc.entry;$('#calc-result').style.fontSize=calc.entry.length>10?'37px':calc.entry.length>7?'49px':'';$('#calc-expression').textContent=calc.expression;}}
function pressCalc(v){A.haptic();if(v==='clear'){calc={entry:'0',previous:null,operator:null,fresh:false,expression:'',lastOp:null,lastOperand:null};}
else if(/^\d$/.test(v)){if(calc.fresh||calc.entry==='エラー'){calc.entry=v;calc.fresh=false;}else if(calc.entry.length<13)calc.entry=calc.entry==='0'?v:calc.entry+v;}
else if(v==='.'){if(calc.fresh||calc.entry==='エラー'){calc.entry='0.';calc.fresh=false;}else if(!calc.entry.includes('.'))calc.entry+='.';}
else if(v==='sign'){if(calc.entry!=='0'&&calc.entry!=='エラー')calc.entry=calc.entry.startsWith('-')?calc.entry.slice(1):'-'+calc.entry;}
else if(v==='percent'){calc.entry=formatNumber(Number(calc.entry)/100);}
else if(['+','-','*','/'].includes(v)){const value=Number(calc.entry);if(!Number.isFinite(value))return;if(calc.operator!==null&&!calc.fresh){calc.entry=formatNumber(compute(calc.previous,value,calc.operator));calc.previous=Number(calc.entry);}else calc.previous=value;calc.operator=v;calc.expression=`${calc.entry} ${opLabel[v]}`;calc.fresh=true;}
else if(v==='='){const op=calc.operator||calc.lastOp;if(op){const a=calc.operator?calc.previous:Number(calc.entry),b=calc.operator?Number(calc.entry):calc.lastOperand;const expression=`${a} ${opLabel[op]} ${b}`;calc.entry=formatNumber(compute(a,b,op));calc.expression=expression+' =';calc.lastOp=op;calc.lastOperand=b;calc.previous=null;calc.operator=null;calc.fresh=true;calcHistory.unshift({expression,result:calc.entry});calcHistory=calcHistory.slice(0,30);A.save('calcHistory',calcHistory);}}
updateCalc();}
A.apps.calculator.render=calcApp;A.actions.calcKey=el=>pressCalc(el.dataset.value);A.actions.calcHistory=()=>A.overlay(`${A.overlayTitle('計算履歴')}<div>${calcHistory.map(h=>`<div style="padding:16px 4px;border-bottom:1px solid #ffffff20;text-align:right"><small style="color:#ffffff70;font-size:12px">${esc(h.expression)}</small><strong style="display:block;font-size:25px;font-weight:400;margin-top:7px">${esc(h.result)}</strong></div>`).join('')||'<p style="font-size:12px;color:#fffa">履歴はまだありません。</p>'}</div><button class="control-tile" data-action="calcClearHistory" style="width:100%;margin-top:20px">履歴をクリア</button>`);A.actions.calcClearHistory=()=>{calcHistory=[];A.save('calcHistory',[]);A.actions.calcHistory();};
// Phone: offline call simulation and local history.
const phoneContacts=[{name:'美咲',number:'09012345678',initial:'美',color:'#bf9f92'},{name:'陽',number:'08023456789',initial:'陽',color:'#8ba394'},{name:'aura サポート',number:'0120000000',initial:'a.',color:'#a494b6'},{name:'自宅',number:'0312345678',initial:'家',color:'#8cacc3'}];
let dial='',phoneTab='keypad',callTimer=null,callStarted=0,callNumber='',callLog=A.load('callLog',[]),toneContext=null;
const phoneTabs=()=>A.tabs([{id:'favorites',icon:'star',name:'よく使う項目',action:'phoneTab',value:'favorites'},{id:'recent',icon:'clock',name:'履歴',action:'phoneTab',value:'recent'},{id:'contacts',icon:'user',name:'連絡先',action:'phoneTab',value:'contacts'},{id:'keypad',icon:'grid',name:'キーパッド',action:'phoneTab',value:'keypad'}],phoneTab);
function phone(){A.statusTheme(false);A.view(A.nav('電話','<span class="demo-label">ローカルデモ</span>')+`<div class="app-content" style="padding-bottom:10px" id="phone-content"></div>`+phoneTabs());const el=$('#phone-content');if(phoneTab==='keypad'){el.innerHTML=`<div class="dial-display" id="dial-display">${esc(dial)}</div><p style="text-align:center;font-size:9px;color:#acafb7;margin:0 0 13px">通話はシミュレーションです</p><div class="dial-keypad">${['1','2','3','4','5','6','7','8','9','*','0','#'].map((n,i)=>`<button class="dial-key" data-action="dialKey" data-value="${n}">${n}<small>${['','ABC','DEF','GHI','JKL','MNO','PQRS','TUV','WXYZ','','+',''][i]||'&nbsp;'}</small></button>`).join('')}</div><div class="dial-actions"><button class="call-button" data-action="phoneCall" aria-label="デモ通話を開始">${icon('phone')}</button><button class="dial-delete" data-action="dialDelete" aria-label="一文字削除">${icon('backspace')}</button></div>`;}else if(phoneTab==='recent'){el.innerHTML=`<h1 class="app-title">履歴</h1>${callLog.length?callLog.map(c=>`<button class="list-row" data-action="callFromLog" data-number="${esc(c.number)}"><span class="row-icon">${icon('phone')}</span><span class="row-main"><strong>${esc(c.name)}</strong><small>発信 · デモ通話 · ${c.duration}秒</small></span><span class="row-value">${new Date(c.date).toLocaleDateString('ja-JP',{month:'numeric',day:'numeric'})}</span></button>`).join(''):A.empty('デモ通話の履歴が、ここに表示されます。','phone')}`;}else{el.innerHTML=`<h1 class="app-title">${phoneTab==='favorites'?'よく使う項目':'連絡先'}</h1>${A.search('phone-contact-search','連絡先を検索')}<div id="phone-contact-list"></div><p class="notes-footer">すべて架空の連絡先です。</p>`;const render=q=>{$('#phone-contact-list').innerHTML=phoneContacts.filter(c=>c.name.includes(q)||c.number.includes(q)).filter((_,i)=>phoneTab!=='favorites'||i<2).map(c=>`<button class="list-row" data-action="contactCall" data-number="${c.number}"><span class="avatar" style="background:${c.color}">${c.initial}</span><span class="row-main"><strong>${c.name}</strong><small>${c.number}</small></span>${icon('phone','style="width:19px;color:#7a9b89"')}</button>`).join('')||A.empty('連絡先が見つかりません。','user');};render('');$('#phone-contact-search').oninput=e=>render(e.target.value);}}
A.apps.phone.render=()=>{phone();A.cleanups.push(()=>{if(callTimer){clearInterval(callTimer);callTimer=null;saveCall();}});};A.actions.phoneTab=el=>{phoneTab=el.dataset.value;phone();};
function getAudioContext(){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return null;toneContext=toneContext||new Audio();toneContext.resume();return toneContext;}
function dialTone(n){if(!A.settings.sound)return;try{const context=getAudioContext();if(!context)return;const gain=context.createGain();gain.gain.setValueAtTime(.025,context.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.13);gain.connect(context.destination);const key='123456789*0#'.indexOf(n);[697+Math.floor(key/3)*80,1209+(key%3)*135].forEach(f=>{const o=context.createOscillator();o.frequency.value=f;o.connect(gain);o.start();o.stop(context.currentTime+.14);o.onended=()=>o.disconnect();});setTimeout(()=>gain.disconnect(),200);}catch{}}
A.actions.dialKey=el=>{if(dial.length>=18)return;dial+=el.dataset.value;$('#dial-display').textContent=dial;dialTone(el.dataset.value);A.haptic();};A.actions.dialDelete=()=>{dial=dial.slice(0,-1);$('#dial-display').textContent=dial;};
function startCall(number){if(!number)return A.toast('番号を入力してください');callNumber=number;callStarted=Date.now();const contact=phoneContacts.find(c=>c.number===number);A.statusTheme(true);A.view(`<div class="call-screen"><span class="demo-label" style="background:#ffffff15;color:#c4ced4;margin-bottom:19px">デモ通話 · 外部接続なし</span><span class="avatar" style="width:78px;height:78px;font-size:28px;background:${contact?.color||'#677f91'}">${contact?.initial||'◉'}</span><h2>${esc(contact?.name||number)}</h2><p id="call-duration">00:00</p><div class="call-controls">${[['mic','消音'],['grid','キーパッド'],['volume','スピーカー'],['plus','追加'],['camera','ビデオ'],['user','連絡先']].map(([ic,label])=>`<button data-action="callControl" data-label="${label}" aria-pressed="false"><span>${icon(ic)}</span>${label}</button>`).join('')}</div><button class="call-button call-end" data-action="phoneEnd" aria-label="デモ通話を終了">${icon('phone')}</button><p style="font-size:9px;color:#a7b2be">実際の電話回線には接続されていません。</p></div>`);clearInterval(callTimer);callTimer=setInterval(()=>{if($('#call-duration'))$('#call-duration').textContent=timeString((Date.now()-callStarted)/1000);},300);}
function saveCall(){if(!callNumber)return;callLog.unshift({number:callNumber,name:phoneContacts.find(c=>c.number===callNumber)?.name||callNumber,date:Date.now(),duration:Math.floor((Date.now()-callStarted)/1000)});callLog=callLog.slice(0,40);A.save('callLog',callLog);callNumber='';}
A.actions.phoneCall=()=>startCall(dial);A.actions.contactCall=el=>{dial=el.dataset.number;startCall(dial);};A.actions.callFromLog=el=>startCall(el.dataset.number);A.actions.phoneEnd=()=>{clearInterval(callTimer);callTimer=null;saveCall();phoneTab='recent';phone();};A.actions.callControl=el=>{const label=el.dataset.label;if(label==='消音'||label==='スピーカー'){el.classList.toggle('active');el.setAttribute('aria-pressed',el.classList.contains('active'));A.toast(`${label}を${el.classList.contains('active')?'オン':'オフ'}にしました（デモ）`);}else if(label==='キーパッド'){A.overlay(`${A.overlayTitle('通話中のキーパッド')}<div class="dial-keypad">${'123456789*0#'.split('').map(n=>`<button class="dial-key" style="color:#26303d" data-action="callDtmf" data-value="${n}">${n}</button>`).join('')}</div><p class="control-footer">音はこのブラウザ内だけで再生されます。</p>`);}else A.toast('この操作は通話デモでは利用できません');};A.actions.callDtmf=el=>{dialTone(el.dataset.value);A.haptic();};
// Clock: timers work while the document is open; no OS alarm integration.
let clockTab='world',stopwatch={running:false,start:0,elapsed:0,laps:[]},timer={running:false,remaining:300,end:0},alarms=A.load('alarms',[{id:'alarm-1',time:'07:00',label:'ゆっくり、目覚めよう',enabled:false},{id:'alarm-2',time:'08:30',label:'一日をはじめる',enabled:false}]);let alarmLast='',clockInterval=null;
const clockTabs=()=>A.tabs([{id:'world',icon:'globe',name:'世界時計',action:'clockTab',value:'world'},{id:'alarm',icon:'alarm',name:'アラーム',action:'clockTab',value:'alarm'},{id:'stopwatch',icon:'timer',name:'ストップウォッチ',action:'clockTab',value:'stopwatch'},{id:'timer',icon:'clock',name:'タイマー',action:'clockTab',value:'timer'}],clockTab);
const stopwatchElapsed=()=>stopwatch.elapsed+(stopwatch.running?Date.now()-stopwatch.start:0);
function stopwatchFormat(ms){return `${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(Math.floor(ms/10)%100).padStart(2,'0')}`;}
function clock(){A.statusTheme(false);A.view(A.nav('時計',clockTab==='alarm'?`<button data-action="alarmAdd" aria-label="アラームを追加">${icon('plus')}</button>`:'')+`<div class="app-content" id="clock-content"></div>`+clockTabs());const el=$('#clock-content');
if(clockTab==='world')el.innerHTML=`<h1 class="app-title">同じ今、違う時間。</h1><p class="app-subtitle">世界のどこかでも、新しい一日が。</p>${[['東京','Asia/Tokyo','あなたの小さな世界'],['ニューヨーク','America/New_York','AMERICA'],['ロンドン','Europe/London','EUROPE'],['パリ','Europe/Paris','EUROPE'],['シドニー','Australia/Sydney','OCEANIA']].map(([name,zone,desc])=>`<div class="clock-world"><div><small>${desc}</small><h3>${name}</h3></div><strong data-timezone="${zone}"></strong></div>`).join('')}`;
else if(clockTab==='alarm')el.innerHTML=`<h1 class="app-title">おはよう、世界。</h1><p class="app-subtitle">このページが開いている間にお知らせします。<br>バックグラウンドや端末のロック中は動作を保証しません。</p>${alarms.map(a=>`<div class="alarm-row"><div><strong class="alarm-time" style="color:${a.enabled?'inherit':'#a9aab3'}">${a.time}</strong><small>${esc(a.label)} · 毎日</small></div><button class="toggle ${a.enabled?'on':''}" data-action="alarmToggle" data-id="${a.id}" aria-label="${a.time}のアラーム" aria-pressed="${a.enabled}"></button><button class="delete-small" data-action="alarmDelete" data-id="${a.id}" aria-label="アラーム削除">×</button></div>`).join('')}`;
else if(clockTab==='stopwatch')el.innerHTML=`<h1 class="app-title">一瞬を、刻む。</h1><div class="stopwatch-display" id="stopwatch-display">${stopwatchFormat(stopwatchElapsed())}</div><div class="stopwatch-actions"><button class="round-action" data-action="stopwatchLap">${stopwatch.running?'ラップ':'リセット'}</button><button class="round-action ${stopwatch.running?'stop':'start'}" data-action="stopwatchToggle">${stopwatch.running?'停止':'開始'}</button></div><div id="lap-list">${stopwatch.laps.map((l,i)=>`<div class="lap-row"><span>ラップ ${stopwatch.laps.length-i}</span><span>${stopwatchFormat(l)}</span></div>`).join('')}</div>`;
else el.innerHTML=`<h1 class="app-title">ひと息の、時間。</h1><p class="app-subtitle">ページを開いている間にお知らせします。</p>${timer.running?`<div class="timer-ring" id="timer-display">${timeString((timer.end-Date.now())/1000)}</div>`:`<div class="timer-picker"><input type="number" id="timer-minutes" min="0" max="180" value="${Math.floor(timer.remaining/60)}" aria-label="分">分<input type="number" id="timer-seconds" min="0" max="59" value="${timer.remaining%60}" aria-label="秒">秒</div><p class="setting-description" style="text-align:center;margin-bottom:45px">コーヒーを淹れる、ストレッチをする。<br>小さな時間を、大切に。</p>`}<div class="stopwatch-actions"><button class="round-action" data-action="timerReset">リセット</button><button class="round-action ${timer.running?'stop':'start'}" data-action="timerToggle">${timer.running?'一時停止':'開始'}</button></div><div class="game-toolbar" style="justify-content:center;margin-top:25px">${[1,3,5,10].map(m=>`<button data-action="timerPreset" data-value="${m}" style="background:#e4e5eb;color:#8b8d99">${m}分</button>`).join('')}</div>`;
updateClockView();}
function updateClockView(){if(A.current!=='clock')return;A.$$('[data-timezone]').forEach(el=>el.textContent=new Date().toLocaleTimeString('en-GB',{timeZone:el.dataset.timezone,hour:'2-digit',minute:'2-digit'}));if($('#stopwatch-display'))$('#stopwatch-display').textContent=stopwatchFormat(stopwatchElapsed());if($('#timer-display'))$('#timer-display').textContent=timeString(Math.ceil((timer.end-Date.now())/1000));}
function beep(){try{const c=getAudioContext();if(!c)return;for(let i=0;i<3;i++){const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*.35;o.frequency.value=880;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.1,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+.23);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+.25);o.onended=()=>{o.disconnect();g.disconnect();};}}catch{}}
function alarmNotice(title){A.network?.clockNotice(title);beep();A.overlay(`${A.overlayTitle('時計')}<div style="text-align:center;margin-top:80px">${icon('alarm','style="width:65px;height:65px;margin:0 auto 30px;color:#e8c6a3"')}<h2 style="font-size:28px;font-weight:400">${esc(title)}</h2><p style="font-size:12px;color:#c7bdc7">小さな時間を、大切に。</p><button class="primary-button" data-action="closeOverlay" style="background:#c4a383;margin-top:40px">閉じる</button></div>`);}
A.clockTick=()=>{updateClockView();if(timer.running&&Date.now()>=timer.end){timer.running=false;timer.remaining=0;if(A.current==='clock'&&clockTab==='timer')clock();alarmNotice('タイマーが終了しました');}const n=new Date(),minute=n.toTimeString().slice(0,5),key=n.toDateString()+minute;if(key!==alarmLast){alarmLast=key;const alarm=alarms.find(a=>a.enabled&&a.time===minute);if(alarm)alarmNotice(alarm.label||'アラーム');}};
A.apps.clock.render=()=>{clock();clearInterval(clockInterval);clockInterval=setInterval(updateClockView,45);A.cleanups.push(()=>clearInterval(clockInterval));};A.actions.clockTab=el=>{clockTab=el.dataset.value;clock();};
A.actions.stopwatchToggle=()=>{if(stopwatch.running){stopwatch.elapsed=stopwatchElapsed();stopwatch.running=false;}else{stopwatch.start=Date.now();stopwatch.running=true;}clock();};A.actions.stopwatchLap=()=>{if(stopwatch.running)stopwatch.laps.unshift(stopwatchElapsed());else stopwatch={running:false,start:0,elapsed:0,laps:[]};clock();};
A.actions.timerToggle=()=>{if(timer.running){timer.remaining=Math.max(0,Math.ceil((timer.end-Date.now())/1000));timer.running=false;}else{const min=+$('#timer-minutes').value,sec=+$('#timer-seconds').value;if(!Number.isFinite(min)||!Number.isFinite(sec)||min<0||min>180||sec<0||sec>59)return A.toast('0〜180分、0〜59秒で指定してください');const total=Math.floor(min*60+sec);if(!total)return A.toast('時間を指定してください');timer.remaining=total;timer.end=Date.now()+total*1000;timer.running=true;try{getAudioContext();}catch{}}clock();};A.actions.timerReset=()=>{timer={running:false,remaining:300,end:0};clock();};A.actions.timerPreset=el=>{timer={running:false,remaining:+el.dataset.value*60,end:0};clock();};A.actions.alarmToggle=el=>{const a=alarms.find(a=>a.id===el.dataset.id);a.enabled=!a.enabled;A.save('alarms',alarms);if(a.enabled){try{getAudioContext();}catch{}}clock();};A.actions.alarmDelete=el=>{alarms=alarms.filter(a=>a.id!==el.dataset.id);A.save('alarms',alarms);clock();};A.actions.alarmAdd=()=>A.form('新しいアラーム','<label class="form-label">時刻</label><input class="text-input" type="time" name="time" value="07:00" required><label class="form-label">ラベル</label><input class="text-input" name="label" placeholder="一日をはじめよう" maxlength="60">',v=>{alarms.push({id:A.id(),...v,enabled:true});A.save('alarms',alarms);try{getAudioContext();}catch{}clock();});
// Health is sample/manual data, not measurements or medical advice.
let health=A.load('health',{steps:6240,minutes:24,water:1200});
function healthApp(){const move=Math.min(health.steps/8000,1),exercise=Math.min(health.minutes/30,1);A.view(A.nav('ヘルスケア',`<button data-action="healthAdd" aria-label="記録を追加">${icon('plus')}</button>`)+`<div class="app-content"><h1 class="app-title">自分を、たいせつに。</h1><p class="app-subtitle">今日の、小さな積み重ね。 <span class="demo-label">サンプル</span></p><div class="health-hero"><div class="activity-rings"><svg viewBox="0 0 140 140"><circle cx="70" cy="70" r="58" fill="none" stroke="#5e2635" stroke-width="11"/><circle cx="70" cy="70" r="58" fill="none" stroke="#f75381" stroke-width="11" stroke-dasharray="${move*364} 364" stroke-linecap="round"/><circle cx="70" cy="70" r="43" fill="none" stroke="#354921" stroke-width="11"/><circle cx="70" cy="70" r="43" fill="none" stroke="#b8e643" stroke-width="11" stroke-dasharray="${exercise*270} 270" stroke-linecap="round"/><circle cx="70" cy="70" r="28" fill="none" stroke="#1d454b" stroke-width="11"/><circle cx="70" cy="70" r="28" fill="none" stroke="#67d9e3" stroke-width="11" stroke-dasharray="132 176" stroke-linecap="round"/></svg><span>♡</span></div><div><div class="activity-stat"><small>ムーブ</small><strong>${Math.round(health.steps*.042)} <span style="font-size:10px">kcal</span></strong></div><div class="activity-stat"><small>エクササイズ</small><strong>${health.minutes} <span style="font-size:10px">/ 30分</span></strong></div><div class="activity-stat"><small>スタンド</small><strong>9 <span style="font-size:10px">/ 12時間</span></strong></div></div></div><article class="health-card"><h3>♧　歩数</h3><strong>${health.steps.toLocaleString()}</strong> <small>歩</small><div class="bar-chart">${[48,67,52,86,73,94,Math.min(100,health.steps/90)].map((v,i)=>`<div><span style="height:${v}%"></span>${['月','火','水','木','金','土','日'][i]}</div>`).join('')}</div></article><article class="health-card"><h3 style="color:#67a1c9">◉　水分補給</h3><strong>${health.water.toLocaleString()}</strong> <small>/ 2,000 ml</small><div class="progress-track" style="background:#ecf1f7;margin:15px 0"><span style="width:${Math.min(100,health.water/20)}%;background:#8bb9dd"></span></div><button class="secondary-button" data-action="healthWater" style="width:100%;background:#eaf3fa;color:#699abd">+ コップ一杯（200ml）</button></article><article class="health-card"><h3 style="color:#a58bc5">☾　睡眠</h3><strong>7<small>時間</small> 32<small>分</small></strong><p class="setting-description" style="padding:0">ゆっくり休めた夜。サンプルの睡眠記録。</p></article><p class="setting-description">表示はサンプルと手入力の記録です。端末のセンサーや医療サービスとは連携していません。ムーブは歩数からのデモ推計値です。</p></div>`);}
A.healthData=()=>({...health});
A.apps.health.render=healthApp;A.actions.healthWater=()=>{health.water+=200;A.save('health',health);healthApp();A.haptic();};A.actions.healthAdd=()=>A.form('アクティビティを記録',`<label class="form-label">今日の歩数</label><input class="text-input" type="number" name="steps" min="0" max="100000" value="${health.steps}" required><label class="form-label">運動した時間（分）</label><input class="text-input" type="number" name="minutes" min="0" max="1440" value="${health.minutes}" required>`,v=>{health.steps=+v.steps;health.minutes=+v.minutes;A.save('health',health);healthApp();});
// Wallet holds fictional balance only, with no payment integrations.
let wallet=A.load('wallet',{balance:3240,transactions:[{id:'tx1',title:'喫茶 余白',amount:-580,date:Date.now()-3600000},{id:'tx2',title:'青葉駅 → 緑町駅',amount:-220,date:Date.now()-7200000},{id:'tx3',title:'デモチャージ',amount:2000,date:Date.now()-86400000}]});
function walletApp(){A.view(A.nav('ウォレット')+`<div class="app-content"><h1 class="app-title">軽やかに、出かけよう。</h1><p class="app-subtitle">架空の交通系カード <span class="demo-label">DEMO ONLY</span></p><div class="wallet-card"><h3>mori.</h3><small>GO A LITTLE FURTHER.</small><strong>¥${wallet.balance.toLocaleString()}</strong><span>•••• 2048</span></div><div class="wallet-actions"><button class="secondary-button" data-action="walletCharge" style="background:#e3ede8;color:#739082">＋ デモチャージ</button><button class="secondary-button" data-action="walletPay" style="background:#e3ede8;color:#739082">デモで支払う</button></div><p class="section-label">最近のご利用（シミュレーション）</p>${wallet.transactions.slice(0,15).map(t=>`<div class="transaction-row"><div><strong>${esc(t.title)}</strong><small>${new Date(t.date).toLocaleDateString('ja-JP',{month:'short',day:'numeric'})} · デモ取引</small></div><span style="color:${t.amount>0?'#72a080':'inherit'}">${t.amount>0?'+':'−'} ¥${Math.abs(t.amount).toLocaleString()}</span></div>`).join('')}<p class="setting-description" style="margin-top:23px">このカードや残高は架空のものです。実際のお金、決済、交通機関での利用とは関係ありません。個人情報やカード番号は入力しないでください。</p></div>`);}
A.apps.wallet.render=walletApp;A.actions.walletCharge=()=>A.form('デモ残高を追加','<p>実際のお金は使用しません。</p><label class="form-label">金額（デモ）</label><select class="text-input" name="amount"><option value="1000">¥1,000</option><option value="3000">¥3,000</option><option value="5000">¥5,000</option></select>',v=>{wallet.balance+=+v.amount;wallet.transactions.unshift({id:A.id(),title:'デモチャージ',amount:+v.amount,date:Date.now()});A.save('wallet',wallet);walletApp();A.toast('デモ残高を追加しました');},'デモチャージ');A.actions.walletPay=()=>A.form('デモのお買いもの','<p>お好きなものを選んでみてください。</p><label class="form-label">購入するもの（架空）</label><select class="text-input" name="item"><option value="coffee">喫茶 余白 · コーヒー ¥580</option><option value="train">青葉線 · 乗車 ¥220</option><option value="book">栞の書店 · 文庫本 ¥820</option></select>',v=>{const items={coffee:['喫茶 余白',580],train:['青葉線 デモ乗車',220],book:['栞の書店',820]},[title,amount]=items[v.item];if(wallet.balance<amount){A.toast('デモ残高が足りません。チャージしてください。');return false;}wallet.balance-=amount;wallet.transactions.unshift({id:A.id(),title,amount:-amount,date:Date.now()});A.save('wallet',wallet);walletApp();A.toast('デモ支払いが完了しました（実際の決済なし）');},'デモ支払い');
// Local text file CRUD and client-side downloads.
let files=A.load('files',[{id:'file-welcome',name:'はじめに.txt',content:'auraへようこそ。\n\nこのファイルアプリでは、テキストファイルを作成・保存・読み込むことができます。\n\n端末にあるすべてのファイルにはアクセスしません。\n選択して読み込んだテキストだけを、このブラウザに保存します。\n\nダウンロードボタンから、実際の端末に保存できます。',date:Date.now()},{id:'file-journey',name:'小さな旅の計画.md',content:'# 次の週末\n\n## 持っていくもの\n- 読みかけの本\n- カメラ\n- 小さなノート\n\n## やってみたいこと\n1. 知らない道を歩く\n2. 喫茶店でひと休み\n3. 空の写真を一枚撮る\n\n急がなくても、大丈夫。',date:Date.now()-86400000}]);let selectedFile=null;
function filesApp(){const bytes=new Blob([JSON.stringify(files)]).size;A.view(A.nav('ファイル',`<button data-action="fileNew" aria-label="ファイル作成">${icon('plus')}</button>`)+`<div class="app-content"><h1 class="app-title">ここに、しまって。</h1><p class="app-subtitle">大切なものの、小さな居場所。</p><div class="storage-card"><header><span>このaura内のテキスト</span><small>${(bytes/1024).toFixed(1)} KB · ${files.length}ファイル</small></header><div class="storage-bar"><span></span><span></span><span></span></div><p>ブラウザ内保存 · 端末本体の容量表示ではありません</p></div>${A.search('file-search','ファイルを検索')}<div class="files-grid" id="files-grid"></div><button class="primary-button" data-action="fileImport" style="margin-top:22px">${icon('download')}テキストを読み込む</button><button class="secondary-button" data-action="fileExportNotes" style="width:100%;margin-top:10px">保存済みメモをJSONで書き出す</button><p class="setting-description" style="margin-top:17px">対応形式：TXT・MD・JSON・CSV（100KB以下）。選択したファイルだけを読み込みます。</p></div>`);const render=q=>{$('#files-grid').innerHTML=files.filter(f=>f.name.includes(q)).map(f=>`<button class="file-tile" data-action="fileOpen" data-id="${f.id}">${icon('document')}<h3>${esc(f.name)}</h3><small>${new Blob([f.content]).size.toLocaleString()} bytes</small></button>`).join('')||'<p class="empty-state" style="grid-column:span 2">ファイルがありません。</p>';};render('');$('#file-search').oninput=e=>render(e.target.value);}
function openFile(id){const f=files.find(f=>f.id===id);if(!f)return;selectedFile=id;A.view(A.nav(esc(f.name),`<button data-action="fileDelete" aria-label="ファイル削除">${icon('trash')}</button>`,'filesHome','戻る')+`<div class="app-content"><p class="section-label">${new Blob([f.content]).size.toLocaleString()} BYTES · TEXT DOCUMENT</p><pre class="file-preview">${esc(f.content)}</pre><button class="primary-button" data-action="fileDownload" style="margin-top:20px">${icon('download')}端末に保存する</button><button class="secondary-button" data-action="fileEdit" style="width:100%;margin-top:10px">編集する</button></div>`);}
A.currentTextFile=()=>$('.file-preview')?files.find(f=>f.id===selectedFile):null;
A.importTextFile=(name,content)=>{const next=[{id:A.id(),name,content,date:Date.now()},...files];if(!A.save('files',next))return false;files=next;return true;};
A.apps.files.render=filesApp;A.actions.filesHome=filesApp;A.actions.fileOpen=el=>openFile(el.dataset.id);A.actions.fileDownload=()=>{const f=files.find(f=>f.id===selectedFile);if(f)A.download(new Blob([f.content],{type:'text/plain;charset=utf-8'}),f.name);};A.actions.fileNew=()=>fileEditor();A.actions.fileEdit=()=>fileEditor(selectedFile);
function fileEditor(id){const f=files.find(f=>f.id===id);A.form(f?'ファイルを編集':'新しいテキスト',`<label class="form-label">ファイル名</label><input class="text-input" name="name" value="${esc(f?.name||'新しいファイル.txt')}" required maxlength="80"><label class="form-label">内容</label><textarea class="text-input" name="content" style="height:240px" maxlength="100000">${esc(f?.content||'')}</textarea>`,v=>{if(f){f.name=v.name;f.content=v.content;f.date=Date.now();}else files.unshift({id:A.id(),...v,date:Date.now()});A.save('files',files);filesApp();});}
A.actions.fileDelete=()=>A.confirm('ファイルを削除','このaura内からファイルを削除します。',()=>{files=files.filter(f=>f.id!==selectedFile);A.save('files',files);filesApp();});A.actions.fileImport=()=>{const input=document.createElement('input');input.type='file';input.accept='.txt,.md,.json,.csv,text/plain,application/json';input.onchange=async()=>{const f=input.files[0];if(!f)return;if(f.size>100*1024)return A.toast('100KB以下のテキストファイルを選択してください');if(!/\.(txt|md|json|csv)$/i.test(f.name))return A.toast('TXT・MD・JSON・CSVに対応しています');try{const content=await f.text();files.unshift({id:A.id(),name:f.name,content,date:Date.now()});A.save('files',files);if(A.current==='files')filesApp();A.toast('ファイルを読み込みました');}catch{A.toast('ファイルを読み込めませんでした');}};input.click();};A.actions.fileExportNotes=()=>{const notes=A.load('notes',[]);A.download(new Blob([JSON.stringify({app:'aura',exportedAt:new Date().toISOString(),notes},null,2)],{type:'application/json'}),'aura-notes.json');A.toast('保存済みメモを書き出しました');};
})();
