'use strict';
(() => {
const A=window.Aura,$=A.$,esc=A.escape,icon=A.icon;
const UI=A.workbench;
const timeString=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.floor(Math.max(0,s)%60)).padStart(2,'0')}`;
// Calculator uses an arithmetic state machine, never eval.
let calc={entry:'0',previous:null,operator:null,fresh:false,expression:'',lastOp:null,lastOperand:null},calcHistory=A.load('calcHistory',[]);
const opLabel={'+':'+','-':'−','*':'×','/':'÷'};
function calcApp(){A.statusTheme(true);$('#app-screen').classList.add('calc-app');A.view(A.nav('計算機',`<button data-action="calcHistory" style="color:#d3ba95" aria-label="計算履歴">${icon('clock')}</button>`)+`<div class="calc-display"><div class="calc-expression" id="calc-expression">${esc(calc.expression)}</div><div class="calc-result" id="calc-result">${esc(calc.entry)}</div></div><div class="calc-keypad">${[['AC','clear','utility'],['+/−','sign','utility'],['%','percent','utility'],['÷','/','operator'],['7','7',''],['8','8',''],['9','9',''],['×','*','operator'],['4','4',''],['5','5',''],['6','6',''],['−','-','operator'],['1','1',''],['2','2',''],['3','3',''],['+','+','operator'],['0','0','zero'],['.','.',''],['=','=','operator']].map(([label,v,c])=>`<button class="calc-key ${c}" data-action="calcKey" data-value="${v}">${label}</button>`).join('')}</div>`);const keydown=e=>{if(A.current!=='calculator'||!$('#overlay').hidden||!$('#calc-result')||e.target.closest('input,textarea,select,[contenteditable="true"]'))return;let v=e.key;if(v==='Enter')v='=';if(v==='Backspace'){e.preventDefault();calc.entry=calc.entry.length>1?calc.entry.slice(0,-1):'0';updateCalc();return;}if(v==='Delete')v='clear';if('0123456789.+-*/='.includes(v)||v==='clear'){e.preventDefault();pressCalc(v);}};document.addEventListener('keydown',keydown);A.cleanups.push(()=>document.removeEventListener('keydown',keydown));}
function compute(a,b,op){if(op==='/'&&b===0)return null;return op==='+'?a+b:op==='-'?a-b:op==='*'?a*b:a/b;}
function formatNumber(n){return n===null||!Number.isFinite(n)?'エラー':String(+n.toPrecision(12));}
function updateCalc(){if($('#calc-result')){$('#calc-result').textContent=calc.entry;$('#calc-result').style.fontSize=calc.entry.length>10?'37px':calc.entry.length>7?'49px':'';$('#calc-expression').textContent=calc.expression;}}
function pressCalc(v){A.haptic();if(v==='clear'){calc={entry:'0',previous:null,operator:null,fresh:false,expression:'',lastOp:null,lastOperand:null};}
else if(/^\d$/.test(v)){if(calc.fresh||calc.entry==='エラー'){calc.entry=v;calc.fresh=false;}else if(calc.entry.length<13)calc.entry=calc.entry==='0'?v:calc.entry+v;}
else if(v==='.'){if(calc.fresh||calc.entry==='エラー'){calc.entry='0.';calc.fresh=false;}else if(!calc.entry.includes('.'))calc.entry+='.';}
else if(v==='sign'){if(calc.entry!=='0'&&calc.entry!=='エラー')calc.entry=calc.entry.startsWith('-')?calc.entry.slice(1):'-'+calc.entry;}
else if(v==='percent'){calc.entry=formatNumber(Number(calc.entry)/100);}
else if(['+','-','*','/'].includes(v)){const value=Number(calc.entry);if(!Number.isFinite(value))return;if(calc.operator!==null&&!calc.fresh){calc.entry=formatNumber(compute(calc.previous,value,calc.operator));calc.previous=Number(calc.entry);}else calc.previous=value;calc.operator=v;calc.expression=`${calc.entry} ${opLabel[v]}`;calc.fresh=true;}
else if(v==='='){const op=calc.operator||calc.lastOp;if(op){const a=calc.operator?calc.previous:Number(calc.entry),b=calc.operator?Number(calc.entry):calc.lastOperand;const expression=`${a} ${opLabel[op]} ${b}`;calc.entry=formatNumber(compute(a,b,op));calc.expression=expression+' =';calc.lastOp=op;calc.lastOperand=b;calc.previous=null;calc.operator=null;calc.fresh=true;calcHistory.unshift({expression,result:calc.entry});calcHistory=calcHistory.slice(0,30);A.save('calcHistory',calcHistory);}}
updateCalc();}
A.apps.calculator.render=calcApp;A.actions.calcKey=el=>pressCalc(el.dataset.value);A.actions.calcHistory=()=>A.overlay(`${A.overlayTitle('計算履歴')}<div>${calcHistory.map(h=>`<div style="padding:16px 4px;border-bottom:1px solid #ffffff20;text-align:right"><small style="color:#ffffff70;font-size:12px">${esc(h.expression)}</small><strong style="display:block;font-size:25px;font-weight:400;margin-top:7px">${esc(h.result)}</strong></div>`).join('')||'<p style="font-size:12px;color:#fffa">履歴はまだありません。</p>'}</div><button class="control-tile" data-action="calcClearHistory" style="width:100%;margin-top:20px">履歴をクリア</button>`);A.actions.calcClearHistory=()=>{calcHistory=[];A.save('calcHistory',[]);A.actions.calcHistory();};
// Phone: offline call simulation and local history.
const phoneContacts=[{name:'美咲',number:'09012345678',initial:'美',color:'#bf9f92'},{name:'陽',number:'08023456789',initial:'陽',color:'#8ba394'},{name:'aura サポート',number:'0120000000',initial:'a.',color:'#a494b6'},{name:'自宅',number:'0312345678',initial:'家',color:'#8cacc3'}];
let dial='',phoneTab='keypad',callTimer=null,callStarted=0,callNumber='',callLog=A.load('callLog',[]),toneContext=null;
const phoneTabs=()=>A.tabs([{id:'favorites',icon:'star',name:'よく使う項目',action:'phoneTab',value:'favorites'},{id:'recent',icon:'clock',name:'履歴',action:'phoneTab',value:'recent'},{id:'contacts',icon:'user',name:'連絡先',action:'phoneTab',value:'contacts'},{id:'keypad',icon:'grid',name:'キーパッド',action:'phoneTab',value:'keypad'}],phoneTab);
function phone(){A.statusTheme(false);A.view(A.nav('電話','<span class="demo-label">ローカルデモ</span>')+`<div class="app-content" style="padding-bottom:10px" id="phone-content"></div>`+phoneTabs());const el=$('#phone-content');if(phoneTab==='keypad'){el.innerHTML=`<div class="dial-display" id="dial-display">${esc(dial)}</div><p style="text-align:center;font-size:9px;color:#acafb7;margin:0 0 13px">通話はシミュレーションです</p><div class="dial-keypad">${['1','2','3','4','5','6','7','8','9','*','0','#'].map((n,i)=>`<button class="dial-key" data-action="dialKey" data-value="${n}">${n}<small>${['','ABC','DEF','GHI','JKL','MNO','PQRS','TUV','WXYZ','','+',''][i]||'&nbsp;'}</small></button>`).join('')}</div><div class="dial-actions"><button class="call-button" data-action="phoneCall" aria-label="デモ通話を開始">${icon('phone')}</button><button class="dial-delete" data-action="dialDelete" aria-label="一文字削除">${icon('backspace')}</button></div>`;}else if(phoneTab==='recent'){el.innerHTML=`<h1 class="app-title">履歴</h1>${callLog.length?callLog.map(c=>`<button class="list-row" data-action="callFromLog" data-number="${esc(c.number)}"><span class="row-icon">${icon('phone')}</span><span class="row-main"><strong>${esc(c.name)}</strong><small>発信 · デモ通話 · ${c.duration}秒</small></span><span class="row-value">${new Date(c.date).toLocaleDateString('ja-JP',{month:'numeric',day:'numeric'})}</span></button>`).join(''):A.empty('デモ通話の履歴が、ここに表示されます。','phone')}`;}else{el.innerHTML=`<h1 class="app-title">${phoneTab==='favorites'?'よく使う項目':'連絡先'}</h1>${A.search('phone-contact-search','連絡先を検索')}<div id="phone-contact-list"></div><p class="notes-footer">すべて架空の連絡先です。</p>`;const render=q=>{$('#phone-contact-list').innerHTML=phoneContacts.filter(c=>c.name.includes(q)||c.number.includes(q)).filter((_,i)=>phoneTab!=='favorites'||i<2).map(c=>`<button class="list-row" data-action="contactCall" data-number="${c.number}"><span class="avatar" style="background:${c.color}">${c.initial}</span><span class="row-main"><strong>${c.name}</strong><small>${c.number}</small></span>${icon('phone','style="width:19px;color:#7a9b89"')}</button>`).join('')||A.empty('連絡先が見つかりません。','user');};render('');$('#phone-contact-search').oninput=e=>render(e.target.value);}}
A.apps.phone.render=()=>{phone();A.cleanups.push(()=>{if(callTimer){clearInterval(callTimer);callTimer=null;saveCall();}});};A.actions.phoneTab=el=>{phoneTab=el.dataset.value;phone();};
function getAudioContext(){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return null;toneContext=toneContext||new Audio();toneContext.resume();return toneContext;}
function dialTone(n){if(!A.settings.sound)return;try{const context=getAudioContext();if(!context)return;const gain=context.createGain();gain.gain.setValueAtTime(.025,context.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.13);gain.connect(context.destination);const key='123456789*0#'.indexOf(n);[697+Math.floor(key/3)*80,1209+(key%3)*135].forEach(f=>{const o=context.createOscillator();o.frequency.value=f;o.connect(gain);o.start();o.stop(context.currentTime+.14);o.onended=()=>o.disconnect();});setTimeout(()=>gain.disconnect(),200);}catch{}}
A.actions.dialKey=el=>{if(dial.length>=18)return;dial+=el.dataset.value;$('#dial-display').textContent=dial;dialTone(el.dataset.value);A.haptic();};A.actions.dialDelete=()=>{dial=dial.slice(0,-1);$('#dial-display').textContent=dial;};
function startCall(number){if(!number)return A.toast('番号を入力してください');callNumber=number;callStarted=Date.now();const contact=phoneContacts.find(c=>c.number===number);A.statusTheme(true);A.view(`<div class="call-screen"><span class="demo-label" style="background:#ffffff15;color:#c4ced4;margin-bottom:19px">デモ通話 · 外部接続なし</span><span class="avatar" style="width:78px;height:78px;font-size:28px;background:${contact?.color||'#677f91'}">${contact?.initial||'◉'}</span><h2>${esc(contact?.name||number)}</h2><p id="call-duration">00:00</p><div class="call-controls">${[['mic','消音'],['grid','キーパッド'],['volume','スピーカー'],['plus','追加'],['camera','ビデオ'],['user','連絡先']].map(([ic,label])=>`<button data-action="callControl" data-label="${label}" aria-pressed="false"><span>${icon(ic)}</span>${label}</button>`).join('')}</div><button class="call-button call-end" data-action="phoneEnd" aria-label="デモ通話を終了">${icon('phone')}</button><p style="font-size:9px;color:#a7b2be">実際の電話回線には接続されていません。</p></div>`);clearInterval(callTimer);callTimer=setInterval(()=>{if($('#call-duration'))$('#call-duration').textContent=timeString((Date.now()-callStarted)/1000);},300);}
function saveCall(){if(!callNumber)return;callLog.unshift({number:callNumber,name:phoneContacts.find(c=>c.number===callNumber)?.name||callNumber,date:Date.now(),duration:Math.floor((Date.now()-callStarted)/1000)});callLog=callLog.slice(0,40);A.save('callLog',callLog);callNumber='';}
A.actions.phoneCall=()=>startCall(dial);A.actions.contactCall=el=>{dial=el.dataset.number;startCall(dial);};A.actions.callFromLog=el=>startCall(el.dataset.number);A.actions.phoneEnd=()=>{clearInterval(callTimer);callTimer=null;saveCall();phoneTab='recent';phone();};A.actions.callControl=el=>{const label=el.dataset.label;if(label==='消音'||label==='スピーカー'){el.classList.toggle('active');el.setAttribute('aria-pressed',el.classList.contains('active'));A.toast(`${label}を${el.classList.contains('active')?'オン':'オフ'}にしました（デモ）`);}else if(label==='キーパッド'){A.overlay(`${A.overlayTitle('通話中のキーパッド')}<div class="dial-keypad">${'123456789*0#'.split('').map(n=>`<button class="dial-key" style="color:#26303d" data-action="callDtmf" data-value="${n}">${n}</button>`).join('')}</div><p class="control-footer">音はこのブラウザ内だけで再生されます。</p>`);}else A.toast('この操作は通話デモでは利用できません');};A.actions.callDtmf=el=>{dialTone(el.dataset.value);A.haptic();};
// Clock: timers work while the document is open; no OS alarm integration.
let clockTab='world',stopwatch={running:false,start:0,elapsed:0,laps:[]},timer={running:false,remaining:300,end:0},alarms=A.load('alarms',[{id:'alarm-1',time:'07:00',label:'ゆっくり、目覚めよう',enabled:false},{id:'alarm-2',time:'08:30',label:'一日をはじめる',enabled:false}]);let alarmLast='',clockInterval=null;
const clockTabs=()=>A.tabs([{id:'world',icon:'globe',name:'世界時計',action:'clockTab',value:'world'},{id:'alarm',icon:'alarm',name:'アラーム',action:'clockTab',value:'alarm'},{id:'stopwatch',icon:'timer',name:'ストップウォッチ',action:'clockTab',value:'stopwatch'},{id:'timer',icon:'clock',name:'タイマー',action:'clockTab',value:'timer'}],clockTab);
const stopwatchElapsed=()=>stopwatch.elapsed+(stopwatch.running?Date.now()-stopwatch.start:0);
function stopwatchFormat(ms){return `${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(Math.floor(ms/10)%100).padStart(2,'0')}`;}
function clock(){A.statusTheme(false);A.view(A.nav('時計',clockTab==='alarm'?`<button data-action="alarmAdd" aria-label="アラームを追加">${icon('plus')}</button>`:'')+`<div class="app-content" id="clock-content"></div>`+clockTabs());const el=$('#clock-content');
if(clockTab==='world')el.innerHTML=`<h1 class="app-title">同じ今、違う時間。</h1><p class="app-subtitle">世界のどこかでも、新しい一日が。</p>${[['東京','Asia/Tokyo','あなたの小さな世界'],['ニューヨーク','America/New_York','AMERICA'],['ロンドン','Europe/London','EUROPE'],['パリ','Europe/Paris','EUROPE'],['シドニー','Australia/Sydney','OCEANIA']].map(([name,zone,desc])=>`<div class="clock-world"><div><small>${desc}</small><h3>${name}</h3></div><strong data-timezone="${zone}"></strong></div>`).join('')}`;
else if(clockTab==='alarm')el.innerHTML=`<h1 class="app-title">おはよう、世界。</h1><p class="app-subtitle">このページが開いている間にお知らせします。<br>バックグラウンドや端末のロック中は動作を保証しません。</p>${alarms.map(a=>`<div class="alarm-row"><div><strong class="alarm-time" style="color:${a.enabled?'inherit':'#a9aab3'}">${a.time}</strong><small>${esc(a.label)} · 毎日</small></div><button class="toggle ${a.enabled?'on':''}" data-action="alarmToggle" data-id="${a.id}" aria-label="${a.time}のアラーム" aria-pressed="${a.enabled}"></button><button class="delete-small" data-action="alarmDelete" data-id="${a.id}" aria-label="アラーム削除">×</button></div>`).join('')}`;
else if(clockTab==='stopwatch')el.innerHTML=`<h1 class="app-title">一瞬を、刻む。</h1><div class="stopwatch-display" id="stopwatch-display">${stopwatchFormat(stopwatchElapsed())}</div><div class="stopwatch-actions"><button class="round-action" data-action="stopwatchLap">${stopwatch.running?'ラップ':'リセット'}</button><button class="round-action ${stopwatch.running?'stop':'start'}" data-action="stopwatchToggle">${stopwatch.running?'停止':'開始'}</button></div><div id="lap-list">${stopwatch.laps.map((l,i)=>`<div class="lap-row"><span>ラップ ${stopwatch.laps.length-i}</span><span>${stopwatchFormat(l)}</span></div>`).join('')}</div>`;
else el.innerHTML=`<h1 class="app-title">ひと息の、時間。</h1><p class="app-subtitle">ページを開いている間にお知らせします。</p>${timer.running?`<div class="timer-ring" id="timer-display">${timeString((timer.end-Date.now())/1000)}</div>`:`<div class="timer-picker"><input type="number" id="timer-minutes" min="0" max="180" value="${Math.floor(timer.remaining/60)}" aria-label="分">分<input type="number" id="timer-seconds" min="0" max="59" value="${timer.remaining%60}" aria-label="秒">秒</div><p class="setting-description" style="text-align:center;margin-bottom:45px">コーヒーを淹れる、ストレッチをする。<br>小さな時間を、大切に。</p>`}<div class="stopwatch-actions"><button class="round-action" data-action="timerReset">リセット</button><button class="round-action ${timer.running?'stop':'start'}" data-action="timerToggle">${timer.running?'一時停止':'開始'}</button></div><div class="game-toolbar" style="justify-content:center;margin-top:25px">${[1,3,5,10].map(m=>`<button data-action="timerPreset" data-value="${m}" style="background:#e4e5eb;color:#8b8d99">${m}分</button>`).join('')}</div>`;
updateClockView();}
function updateClockView(){if(A.current!=='clock')return;A.$$('[data-timezone]').forEach(el=>el.textContent=new Date().toLocaleTimeString('en-GB',{timeZone:el.dataset.timezone,hour:'2-digit',minute:'2-digit'}));if($('#stopwatch-display'))$('#stopwatch-display').textContent=stopwatchFormat(stopwatchElapsed());if($('#timer-display'))$('#timer-display').textContent=timeString(Math.ceil((timer.end-Date.now())/1000));}
function beep(){try{const c=getAudioContext();if(!c)return;for(let i=0;i<3;i++){const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*.35;o.frequency.value=880;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.1,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+.23);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+.25);o.onended=()=>{o.disconnect();g.disconnect();};}}catch{}}
function alarmNotice(title){A.network?.clockNotice(title);beep();A.overlay(`${A.overlayTitle('時計')}<div style="text-align:center;margin-top:80px">${icon('alarm','style="width:65px;height:65px;margin:0 auto 30px;color:#e8c6a3"')}<h2 style="font-size:28px;font-weight:400">${esc(title)}</h2><p style="font-size:12px;color:#c7bdc7">小さな時間を、大切に。</p><button class="primary-button" data-action="closeOverlay" style="background:#c4a383;margin-top:40px">閉じる</button></div>`);}
A.clockTick=()=>{updateClockView();if(timer.running&&Date.now()>=timer.end){timer.running=false;timer.remaining=0;if(A.current==='clock'&&clockTab==='timer')clock();alarmNotice('タイマーが終了しました');}const n=new Date(),minute=n.toTimeString().slice(0,5),key=n.toDateString()+minute;if(key!==alarmLast){alarmLast=key;const alarm=alarms.find(a=>a.enabled&&a.time===minute);if(alarm)alarmNotice(alarm.label||'アラーム');}};
A.apps.clock.render=()=>{clock();clearInterval(clockInterval);clockInterval=setInterval(updateClockView,45);A.cleanups.push(()=>clearInterval(clockInterval));};A.actions.clockTab=el=>{clockTab=el.dataset.value;clock();};
A.actions.stopwatchToggle=()=>{if(stopwatch.running){stopwatch.elapsed=stopwatchElapsed();stopwatch.running=false;}else{stopwatch.start=Date.now();stopwatch.running=true;}clock();};A.actions.stopwatchLap=()=>{if(stopwatch.running)stopwatch.laps.unshift(stopwatchElapsed());else stopwatch={running:false,start:0,elapsed:0,laps:[]};clock();};
A.actions.timerToggle=()=>{if(timer.running){timer.remaining=Math.max(0,Math.ceil((timer.end-Date.now())/1000));timer.running=false;}else{const min=+$('#timer-minutes').value,sec=+$('#timer-seconds').value;if(!Number.isFinite(min)||!Number.isFinite(sec)||min<0||min>180||sec<0||sec>59)return A.toast('0〜180分、0〜59秒で指定してください');const total=Math.floor(min*60+sec);if(!total)return A.toast('時間を指定してください');timer.remaining=total;timer.end=Date.now()+total*1000;timer.running=true;try{getAudioContext();}catch{}}clock();};A.actions.timerReset=()=>{timer={running:false,remaining:300,end:0};clock();};A.actions.timerPreset=el=>{timer={running:false,remaining:+el.dataset.value*60,end:0};clock();};A.actions.alarmToggle=el=>{const a=alarms.find(a=>a.id===el.dataset.id);a.enabled=!a.enabled;A.save('alarms',alarms);if(a.enabled){try{getAudioContext();}catch{}}clock();};A.actions.alarmDelete=el=>{alarms=alarms.filter(a=>a.id!==el.dataset.id);A.save('alarms',alarms);clock();};A.actions.alarmAdd=()=>A.form('新しいアラーム','<label class="form-label">時刻</label><input class="text-input" type="time" name="time" value="07:00" required><label class="form-label">ラベル</label><input class="text-input" name="label" placeholder="一日をはじめよう" maxlength="60">',v=>{alarms.push({id:A.id(),...v,enabled:true});A.save('alarms',alarms);try{getAudioContext();}catch{}clock();});
// Manual daily journal. Historical bars come only from stored entries.
let health=A.load('health',{steps:6240,minutes:24,water:1200}),healthDate=UI.day(new Date()),healthMetric='steps';
const healthDefaults={steps:8000,minutes:30,water:2000};
const healthMetrics=[['steps','歩数','歩',100000],['minutes','運動','分',1440],['water','水分','ml',20000]];
function healthDays(){return health.days||{[health.date||UI.day(new Date())]:{steps:health.steps||0,minutes:health.minutes||0,water:health.water||0,source:'legacy'}};}
function healthEntry(){return healthDays()[healthDate]||{steps:0,minutes:0,water:0};}
function saveHealthDay(value){const next={...health,...(healthDate===UI.day(new Date())?value:{}),date:UI.day(new Date()),days:{...healthDays(),[healthDate]:{...value,source:'manual'}}};if(!A.save('health',next))return false;health=next;return true;}
function healthApp(){
 const entry=healthEntry(),goals=health.goals||healthDefaults,days=healthDays();
 const week=Array.from({length:7},(_,i)=>{const d=new Date(healthDate+'T12:00:00');d.setDate(d.getDate()-6+i);return {key:UI.day(d),label:d.getDate()};});
 const max=Math.max(goals[healthMetric],...week.map(d=>days[d.key]?.[healthMetric]||0));
 A.view(A.nav('ヘルスケア',`<button data-action="healthAdd" aria-label="記録を追加">${icon('plus')}</button>`)+`<div class="app-content work-app health-work"><span class="work-eyebrow">A LITTLE BETTER, EVERY DAY</span><h1 class="app-title">自分を、たいせつに。</h1><div class="journal-date"><button data-action="healthDay" data-value="-1" aria-label="前日">‹</button><label>記録する日<input id="health-date" type="date" value="${healthDate}" max="${UI.day(new Date())}" aria-label="記録する日"></label><button data-action="healthDay" data-value="1" ${healthDate>=UI.day(new Date())?'disabled':''} aria-label="翌日">›</button></div><div class="wellness-hero"><div class="wellness-rings">${healthMetrics.map(([key,label],i)=>`<svg viewBox="0 0 160 160" aria-label="${label} ${Math.round(entry[key]/goals[key]*100)}%"><circle cx="80" cy="80" r="${65-i*17}" class="ring-track"/><circle cx="80" cy="80" r="${65-i*17}" style="--ring-color:${['#e783a5','#a9bf72','#79bfc4'][i]}" pathLength="100" stroke-dasharray="${Math.min(100,entry[key]/goals[key]*100)} 100"/></svg>`).join('')}<span>${icon('heart')}</span></div><div><small>${entry.source==='legacy'?'以前の記録 / サンプル含む':'手入力の記録'}</small><h2>${healthDate===UI.day(new Date())?'今日のあなた。':UI.date(healthDate)}</h2><p>比べるのは、昨日の自分。</p>${UI.button('healthGoals','目標を編集')}</div></div><div class="metric-cards">${healthMetrics.map(([key,label,unit])=>`<button class="metric-card" data-action="healthMetric" data-value="${key}" aria-pressed="${healthMetric===key}"><small>${label}</small><strong>${entry[key].toLocaleString()}</strong><span>${unit} / ${goals[key].toLocaleString()}</span></button>`).join('')}</div><article class="insight-card"><header><h3>7日間の${healthMetrics.find(m=>m[0]===healthMetric)[1]}</h3><small>記録のない日は —</small></header><div class="journal-chart">${week.map(d=>`<button data-action="healthSelectDay" data-value="${d.key}" aria-label="${d.key} ${days[d.key]?.[healthMetric]??'記録なし'}"><span>${days[d.key]?.[healthMetric]??'—'}</span><div><i style="height:${(days[d.key]?.[healthMetric]||0)/max*100}%"></i></div><small>${d.label}日</small></button>`).join('')}</div></article><article class="insight-card water-card"><div><h3>水分を記録</h3><p>${entry.water.toLocaleString()} / ${goals.water.toLocaleString()} ml</p></div>${UI.button('healthWater','＋ 200 ml')}</article><div class="work-toolbar">${UI.button('healthAdd','この日の記録を編集')}${UI.button('healthDeleteDay','この日の記録を削除')}</div><p class="work-note">手入力の生活記録です。自動計測・診断ではありません。<br>過去バージョンの記録にはサンプルが含まれます。</p></div>`);
 $('#health-date').onchange=e=>{if(e.target.value&&e.target.value<=UI.day(new Date())){healthDate=e.target.value;healthApp();}};
}
A.healthData=()=>({...health,days:healthDays()});A.apps.health.render=()=>{healthDate=UI.day(new Date());healthApp();};
A.actions.healthDay=el=>{const d=new Date(healthDate+'T12:00:00');d.setDate(d.getDate()+Number(el.dataset.value));if(UI.day(d)<=UI.day(new Date())){healthDate=UI.day(d);healthApp();}};
A.actions.healthSelectDay=el=>{healthDate=el.dataset.value;healthApp();};A.actions.healthMetric=el=>{healthMetric=el.dataset.value;healthApp();};
A.actions.healthWater=()=>{const e=healthEntry();if(e.water+200>20000)return A.toast('1日の記録上限は20,000 mlです');if(saveHealthDay({...e,water:e.water+200}))healthApp();};
A.actions.healthAdd=()=>A.form('アクティビティを記録',`<p>${UI.date(healthDate)}の合計を入力します。</p>`+healthMetrics.map(([key,label,unit,max])=>UI.field(`${label}（${unit}）`,key,healthEntry()[key],'number',`required min="0" max="${max}" step="1"`)).join(''),v=>{const value=Object.fromEntries(healthMetrics.map(([key])=>[key,Number(v[key])]));if(healthMetrics.some(([key,,,max])=>!Number.isInteger(value[key])||value[key]<0||value[key]>max))return false;if(!saveHealthDay(value))return false;healthApp();});
A.actions.healthGoals=()=>A.form('自分のペースを決める',healthMetrics.map(([key,label,unit,max])=>UI.field(`${label}（${unit}）`,key,(health.goals||healthDefaults)[key],'number',`required min="1" max="${max}" step="1"`)).join(''),v=>{const goals=Object.fromEntries(healthMetrics.map(([key])=>[key,Number(v[key])]));if(healthMetrics.some(([key,,,max])=>!Number.isInteger(goals[key])||goals[key]<1||goals[key]>max))return false;const next={...health,goals};if(!A.save('health',next))return false;health=next;healthApp();});
A.actions.healthDeleteDay=()=>A.confirm('この日の記録を削除','選択した日の手入力記録を削除します。',()=>{const days={...healthDays()};delete days[healthDate];const next={...health,days,...(healthDate===UI.day(new Date())?{steps:0,minutes:0,water:0}:{})};if(A.save('health',next)){health=next;healthApp();}});
// Wallet holds fictional balance only, with no payment integrations.
let wallet=A.load('wallet',{balance:3240,transactions:[{id:'tx1',title:'喫茶 余白',amount:-580,date:Date.now()-3600000},{id:'tx2',title:'青葉駅 → 緑町駅',amount:-220,date:Date.now()-7200000},{id:'tx3',title:'デモチャージ',amount:2000,date:Date.now()-86400000}]});
let walletTab='card',walletFilter='all';
function walletApp(){if(walletTab==='insights')return walletInsights();A.view(A.nav('ウォレット')+`<div class="app-content work-app wallet-work">${UI.chips([['card','カード'],['insights','利用レポート']],walletTab,'walletTab')}<h1 class="app-title">軽やかに、出かけよう。</h1><p class="app-subtitle">架空の交通系カード <span class="demo-label">DEMO ONLY</span></p><div class="wallet-card"><h3>mori.</h3><small>GO A LITTLE FURTHER.</small><strong>¥${wallet.balance.toLocaleString()}</strong><span>•••• 2048</span></div><div class="wallet-actions"><button class="secondary-button" data-action="walletCharge" style="background:#e3ede8;color:#739082">＋ デモチャージ</button><button class="secondary-button" data-action="walletPay" style="background:#e3ede8;color:#739082">デモで支払う</button></div><p class="section-label">最近のご利用（シミュレーション）</p>${wallet.transactions.slice(0,15).map(t=>`<button class="transaction-row transaction-button" data-action="walletReceipt" data-id="${esc(t.id)}"><div><strong>${esc(t.title)}</strong><small>${new Date(t.date).toLocaleDateString('ja-JP',{month:'short',day:'numeric'})} · デモ取引</small></div><span style="color:${t.amount>0?'#72a080':'inherit'}">${t.amount>0?'+':'−'} ¥${Math.abs(t.amount).toLocaleString()}</span></button>`).join('')}<p class="setting-description" style="margin-top:23px">このカードや残高は架空のものです。実際のお金、決済、交通機関での利用とは関係ありません。個人情報やカード番号は入力しないでください。</p></div>`);}
A.apps.wallet.render=walletApp;A.actions.walletCharge=()=>A.form('デモ残高を追加','<p>実際のお金は使用しません。</p><label class="form-label">金額（デモ）</label><select class="text-input" name="amount"><option value="1000">¥1,000</option><option value="3000">¥3,000</option><option value="5000">¥5,000</option></select>',v=>{const next={...wallet,balance:wallet.balance+Number(v.amount),transactions:[{id:A.id(),title:'デモチャージ',amount:Number(v.amount),date:Date.now()},...wallet.transactions]};if(!A.save('wallet',next))return false;wallet=next;walletApp();A.toast('デモ残高を追加しました');},'デモチャージ');A.actions.walletPay=()=>A.form('デモのお買いもの','<p>お好きなものを選んでみてください。</p><label class="form-label">購入するもの（架空）</label><select class="text-input" name="item"><option value="coffee">喫茶 余白 · コーヒー ¥580</option><option value="train">青葉線 · 乗車 ¥220</option><option value="book">栞の書店 · 文庫本 ¥820</option></select>',v=>{const items={coffee:['喫茶 余白',580],train:['青葉線 デモ乗車',220],book:['栞の書店',820]},[title,amount]=items[v.item];if(wallet.balance<amount){A.toast('デモ残高が足りません。チャージしてください。');return false;}const next={...wallet,balance:wallet.balance-amount,transactions:[{id:A.id(),title,amount:-amount,date:Date.now()},...wallet.transactions]};if(!A.save('wallet',next))return false;wallet=next;walletApp();A.toast('デモ支払いが完了しました（実際の決済なし）');},'デモ支払い');
A.actions.walletTab=el=>{walletTab=el.dataset.value;walletApp();};
const walletCategory=t=>t.amount>0?'チャージ':/喫茶|コーヒー/.test(t.title)?'カフェ':/駅|乗車|線/.test(t.title)?'交通':/書店|本/.test(t.title)?'書籍':'その他';
function walletInsights(){
 const month=UI.day(new Date()).slice(0,7),monthly=wallet.transactions.filter(t=>UI.day(new Date(t.date)).startsWith(month)),spent=-monthly.filter(t=>t.amount<0).reduce((n,t)=>n+t.amount,0),budget=wallet.budget||10000;
 const list=wallet.transactions.filter(t=>walletFilter==='all'||(walletFilter==='out'?t.amount<0:t.amount>0));
 A.view(A.nav('利用レポート')+`<div class="app-content work-app wallet-work">${UI.chips([['card','カード'],['insights','利用レポート']],walletTab,'walletTab')}<span class="work-eyebrow">YOUR MONTH IN LITTLE MOMENTS</span><h1 class="app-title">お金の流れを、知る。</h1><p class="app-subtitle">${month} · 架空のお金のシミュレーション</p><article class="spending-hero"><small>今月のデモ支出</small><strong>¥${spent.toLocaleString()}</strong><p>デモ予算 ¥${budget.toLocaleString()} · ${spent>budget?'予算超過':'残り ¥'+(budget-spent).toLocaleString()}</p><div class="progress-track"><span style="width:${Math.min(100,spent/budget*100)}%"></span></div>${UI.button('walletBudget','デモ予算を変更')}</article><article class="insight-card"><h3>カテゴリ別</h3>${['カフェ','交通','書籍','その他'].map(category=>{const total=-monthly.filter(t=>t.amount<0&&walletCategory(t)===category).reduce((n,t)=>n+t.amount,0);return `<div class="category-stat"><span>${category}</span><div><i style="width:${spent?total/spent*100:0}%"></i></div><strong>¥${total.toLocaleString()}</strong></div>`;}).join('')}</article>${UI.chips([['all','全履歴'],['out','支払い'],['in','チャージ']],walletFilter,'walletFilter')}${list.map(t=>`<button class="transaction-row transaction-button" data-action="walletReceipt" data-id="${esc(t.id)}"><div><strong>${esc(t.title)}</strong><small>${new Date(t.date).toLocaleDateString('ja-JP')} · ${walletCategory(t)}</small></div><span>${t.amount>0?'+':'−'} ¥${Math.abs(t.amount).toLocaleString()}</span></button>`).join('')||A.empty('利用履歴はありません。','wallet')}<p class="work-note">実際の銀行・決済とは接続していません。</p></div>`);
}
A.actions.walletFilter=el=>{walletFilter=el.dataset.value;walletInsights();};
A.actions.walletBudget=()=>A.form('月のデモ予算',UI.field('金額（架空の円）','budget',wallet.budget||10000,'number','required min="1" max="1000000" step="1"'),v=>{const budget=Number(v.budget);if(!Number.isInteger(budget)||budget<1||budget>1000000)return false;const next={...wallet,budget};if(!A.save('wallet',next))return false;wallet=next;walletInsights();});
A.actions.walletReceipt=el=>{const t=wallet.transactions.find(t=>t.id===el.dataset.id);if(!t)return;A.overlay(`${A.overlayTitle('デモ利用明細')}<div class="demo-receipt"><span>SIMULATION RECEIPT</span><h2>${esc(t.title)}</h2><strong>${t.amount>0?'+':'−'} ¥${Math.abs(t.amount).toLocaleString()}</strong><p>${new Date(t.date).toLocaleString('ja-JP')}</p><hr><p>カテゴリ：${walletCategory(t)}</p><p>取引ID：${esc(t.id)}</p><small>これは架空の取引です。<br>領収書や決済の証明として利用できません。</small></div>`);};
// Local text file CRUD and client-side downloads.
let files=A.load('files',[{id:'file-welcome',name:'はじめに.txt',content:'auraへようこそ。\n\nこのファイルアプリでは、テキストファイルを作成・保存・読み込むことができます。\n\n端末にあるすべてのファイルにはアクセスしません。\n選択して読み込んだテキストだけを、このブラウザに保存します。\n\nダウンロードボタンから、実際の端末に保存できます。',date:Date.now()},{id:'file-journey',name:'小さな旅の計画.md',content:'# 次の週末\n\n## 持っていくもの\n- 読みかけの本\n- カメラ\n- 小さなノート\n\n## やってみたいこと\n1. 知らない道を歩く\n2. 喫茶店でひと休み\n3. 空の写真を一枚撮る\n\n急がなくても、大丈夫。',date:Date.now()-86400000}]);let selectedFile=null;
let fileFolder='all',fileQuery='',fileSort='date';
let folders=A.load('fileFolders',[{id:'documents',name:'ドキュメント'},{id:'projects',name:'プロジェクト'}]);
function saveFiles(next){if(!A.save('files',next))return false;files=next;return true;}
function filesApp(){
 const bytes=new Blob([JSON.stringify(files)]).size;
 A.view(A.nav('ファイル',`<button data-action="fileNew" aria-label="ファイル作成">${icon('plus')}</button>`)+`<div class="app-content work-app files-work"><span class="work-eyebrow">A PLACE FOR EVERYTHING</span><h1 class="app-title">ここに、しまって。</h1><div class="storage-card"><header><span>このaura内のテキスト</span><small>${(bytes/1024).toFixed(1)} KB · ${files.length}ファイル</small></header><div class="storage-bar"><span></span><span></span><span></span></div><p>ブラウザ内保存 · 端末本体の容量表示ではありません</p></div>${A.search('file-search','名前・ファイルの内容を検索')}${UI.chips([['all','すべて'],['starred','スター'],...folders.map(f=>[f.id,f.name])],fileFolder,'fileFolder')}<div class="work-toolbar">${UI.button('fileFolderNew','フォルダを作成')}<select id="file-sort" class="work-select" aria-label="ファイルの並べ替え"><option value="date">更新順</option><option value="name">名前順</option><option value="size">サイズ順</option></select>${folders.some(f=>f.id===fileFolder)?UI.button('fileFolderDelete','フォルダ削除'):''}</div><div class="files-grid" id="files-grid"></div><button class="primary-button" data-action="fileImport" style="margin-top:22px">${icon('download')}テキストを読み込む</button><button class="secondary-button" data-action="fileExportNotes" style="width:100%;margin-top:10px">保存済みメモをJSONで書き出す</button><p class="work-note">TXT・MD・JSON・CSV（100KB以下）。<br>選択したファイルのみ、このブラウザに保存します。</p></div>`);
 const render=()=>{
 const list=files.filter(f=>(fileFolder==='all'||fileFolder==='starred'&&f.starred||f.folder===fileFolder)&&(f.name+' '+f.content).toLowerCase().includes(fileQuery.toLowerCase())).sort((a,b)=>fileSort==='name'?a.name.localeCompare(b.name,'ja'):fileSort==='size'?new Blob([b.content]).size-new Blob([a.content]).size:b.date-a.date);
 $('#files-grid').innerHTML=list.map(f=>`<button class="file-tile" data-action="fileOpen" data-id="${esc(f.id)}">${icon('document')}<span class="file-kind">${esc(f.name.split('.').at(-1).toUpperCase().slice(0,6))}${f.starred?' · ★':''}</span><h3>${esc(f.name)}</h3><small>${new Blob([f.content]).size.toLocaleString()} bytes · ${new Date(f.date).toLocaleDateString('ja-JP',{month:'numeric',day:'numeric'})}</small></button>`).join('')||'<div class="work-empty">'+A.empty('ファイルがありません。<br>＋から作成、または読み込んでみましょう。','files')+'</div>';
 };
 $('#file-search').value=fileQuery;$('#file-search').oninput=e=>{fileQuery=e.target.value;render();};$('#file-sort').value=fileSort;$('#file-sort').onchange=e=>{fileSort=e.target.value;render();};render();
}
function openFile(id){
 const f=files.find(f=>f.id===id);if(!f)return;selectedFile=id;
 A.view(A.nav(esc(f.name),`<button data-action="fileDelete" aria-label="ファイル削除">${icon('trash')}</button>`,'filesHome','戻る')+`<div class="app-content work-app"><div class="file-detail-heading">${icon('document')}<div><h2>${esc(f.name)}</h2><p>${new Blob([f.content]).size.toLocaleString()} bytes · ${esc(folders.find(x=>x.id===f.folder)?.name||'未分類')}</p></div></div><div class="work-toolbar">${UI.button('fileStar',f.starred?'★ スター済み':'☆ スター')}${UI.button('fileMove','移動')}${UI.button('fileDuplicate','複製')}</div><pre class="file-preview">${esc(f.content)}</pre><button class="primary-button" data-action="fileDownload" style="margin-top:20px">${icon('download')}端末に保存する</button><button class="secondary-button" data-action="fileEdit" style="width:100%;margin-top:10px">編集する</button><p class="work-note">最終更新 ${new Date(f.date).toLocaleString('ja-JP')}</p></div>`);
}
A.currentTextFile=()=>$('.file-preview')?files.find(f=>f.id===selectedFile):null;
A.importTextFile=(name,content)=>saveFiles([{id:A.id(),name,content,date:Date.now()},...files]);
A.apps.files.render=filesApp;A.actions.filesHome=filesApp;A.actions.fileOpen=el=>openFile(el.dataset.id);
A.actions.fileFolder=el=>{fileFolder=el.dataset.value;filesApp();};
A.actions.fileDownload=()=>{const f=files.find(f=>f.id===selectedFile);if(f)A.download(new Blob([f.content],{type:'text/plain;charset=utf-8'}),f.name);};
A.actions.fileNew=()=>fileEditor();A.actions.fileEdit=()=>fileEditor(selectedFile);
function fileEditor(id){const f=files.find(f=>f.id===id);A.form(f?'ファイルを編集':'新しいテキスト',UI.field('ファイル名','name',f?.name||'新しいファイル.txt','text','required maxlength="80"')+UI.select('保存先','folder',[['','未分類'],...folders.map(f=>[f.id,f.name])],f?.folder|| (folders.some(x=>x.id===fileFolder)?fileFolder:''))+`<label class="form-label">内容<textarea class="text-input" name="content" style="height:240px" maxlength="100000">${esc(f?.content||'')}</textarea></label>`,v=>{if(!/\.(txt|md|json|csv)$/i.test(v.name)||new Blob([v.content]).size>102400){A.toast('TXT・MD・JSON・CSV、100KB以下で保存してください');return false;}const entry={...f,...v,name:v.name.trim(),id:f?.id||A.id(),date:Date.now()};if(!saveFiles(f?files.map(x=>x.id===id?entry:x):[entry,...files]))return false;fileFolder='all';fileQuery='';filesApp();});}
A.actions.fileStar=()=>{if(saveFiles(files.map(f=>f.id===selectedFile?{...f,starred:!f.starred}:f)))openFile(selectedFile);};
A.actions.fileMove=()=>{const f=files.find(f=>f.id===selectedFile);if(!f)return;A.form('ファイルを移動',UI.select('移動先','folder',[['','未分類'],...folders.map(f=>[f.id,f.name])],f.folder||''),v=>{if(!saveFiles(files.map(x=>x.id===f.id?{...x,folder:v.folder}:x)))return false;openFile(f.id);});};
A.actions.fileDuplicate=()=>{const f=files.find(f=>f.id===selectedFile);if(!f)return;const copy={...f,id:A.id(),name:f.name.replace(/(\.[^.]+)$/,' のコピー$1'),date:Date.now()};if(saveFiles([copy,...files]))openFile(copy.id);};
A.actions.fileFolderNew=()=>A.form('新しいフォルダ',UI.field('名前','name','','text','required maxlength="30"'),v=>{const name=v.name.trim();if(!name)return false;if(folders.some(f=>f.name===name)){A.toast('同じ名前のフォルダがあります');return false;}const entry={id:A.id(),name},next=[...folders,entry];if(!A.save('fileFolders',next))return false;folders=next;fileFolder=entry.id;filesApp();});
A.actions.fileFolderDelete=()=>A.confirm('フォルダを削除','フォルダが空の場合のみ削除できます。中のファイルは移動してからお試しください。',()=>{if(files.some(f=>f.folder===fileFolder))return A.toast('先にフォルダ内のファイルを移動してください');const next=folders.filter(f=>f.id!==fileFolder);if(A.save('fileFolders',next)){folders=next;fileFolder='all';filesApp();}});
A.actions.fileDelete=()=>A.confirm('ファイルを削除','このaura内からファイルを削除します。',()=>{if(saveFiles(files.filter(f=>f.id!==selectedFile)))filesApp();});
A.actions.fileImport=()=>{const input=document.createElement('input');input.type='file';input.accept='.txt,.md,.json,.csv,text/plain,application/json';input.onchange=async()=>{const f=input.files[0];if(!f)return;if(f.size>102400)return A.toast('100KB以下のテキストファイルを選択してください');if(!/\.(txt|md|json|csv)$/i.test(f.name))return A.toast('TXT・MD・JSON・CSVに対応しています');try{if(!A.importTextFile(f.name,await f.text()))return;if(A.current==='files'){fileFolder='all';filesApp();}A.toast('ファイルを読み込みました');}catch{A.toast('ファイルを読み込めませんでした');}};input.click();};
A.actions.fileExportNotes=()=>{const notes=A.searchableNotes();A.download(new Blob([JSON.stringify({app:'aura',exportedAt:new Date().toISOString(),notes},null,2)],{type:'application/json'}),'aura-notes.json');A.toast('メモを書き出しました');};
})();
